### ISSUE TITLE
Add DNS66 as method for Twitch ad blocking on Android phones

### ISSUE THREAD

**Issue by itchylol742** [pixeltris/TwitchAdSolutions#101]
https://f-droid.org/packages/org.jak_linux.dns66/

Works as of Sept 16 2022

**Comment by garoto** [comment]
If ads on twitch were as simple to circumvent as blocking DNS requests, this repo would serve no purpose.

**Comment by pixeltris** [comment]
I have heard DNS proxying has worked for some people. Though this specific one looks like it's a DNS blocker as opposed to a DNS proxy out of the box looking at the README:

>## How it works
>The app establishes a VPN service, with routes for all DNS servers diverted to it. The VPN service then intercepts the packages for the servers and forwards any DNS queries that are not blacklisted.
>
>Custom upstream DNS can be configured. If the feature is turned off, the current connection's DNS servers are used. The app ships are pre-defined list of well known (mostly German) non-logging servers courtesy of the Chaos Computer Club.

Blocking DNS requests is not enough. Do you use the custom DNS feature to proxy the DNS requests? If not then it's probably not what is blocking the ads. That being said a DNS blocker would likely fix client side ads which are visibly the same as server side ads which might be what you're observing if they currently aren't enforcing server side ads in your country.

It's probably worth looking into how Twitch handles DNS lookups based on geographic location. If specific servers of theirs always resolve to no ads regardless of the source IP location it would be a viable alternative to the current proxy based solutions and avoid third party services like TTV LOL.

**Comment by TsukiZero** [comment]
Blokada 5 works fine on Android, you just have to be sure that its "VPN" is set to always on.

**Comment by pixeltris** [comment]
I'm going to close this but if you want to add it to the `full-list.md` feel free to make a PR.
