### ISSUE TITLE
Add support for Brave Browser Shield

### ISSUE THREAD

**Issue by dpthegrey** [pixeltris/TwitchAdSolutions#103]
Brave Browser has inbuilt option to block Trackers, ads and more known as [Brave Shield](https://brave.com/shields/). 

[Brave Shield](https://brave.com/shields/) implements most of ad blocking and tracker protection inbuilt without having the need of using [uBlock](https://github.com/gorhill/uBlock) and works pretty well. 

If we can make this project work with [Brave Shield](https://brave.com/shields/) we can have one less extension which will be helpful for devices to save resources which are used by having multiple extensions.

**Comment by pixeltris** [comment]
I don't have any plans of looking at this.
