### ISSUE TITLE
Stream feed freeze and quality selector box randomly showing up.

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#104]
The stream feed randomly may freeze when "blocking midrolls" happens, the audio will go on but the video will remain static, even after the blocking is done, requiring a player refresh to fix.

Randomly when joining a stream the quality selector appears on the top left of the stream, obstructing the feed until the player is interacted with.

**Comment by JappeHallunken** [comment]
Same for me since today, Maybe twitch changed something?

**Comment by pixeltris** [comment]
Issue with Firefox. I'm not going to be doing anything extra with `vaft` so I'm leaving it as-is. If there are similar issues with the new `video-swap-new` script feel free to make a new issue.
