### ISSUE TITLE
Twitch ads appearing since today again using vaft script

### ISSUE THREAD

**Issue by AeonFX** [pixeltris/TwitchAdSolutions#105]
I'm using the latest vaft script via Tampermonkey.
Since today mid-roll ads started to appear again.
I didn't see any pre-rolls ads yet only mid stream seem to happen.

**Comment by Gundor** [comment]
same problem with vaft script with ublock.
Pre rolls ads happened

**Comment by AeonFX** [comment]
I don't know what was happening, maybe twitch was testing stuff but I haven't seen them again. I've only seen them twice in a single stream. Not seen them in any other stream since then. If they still exist they seem to be pretty rare for now.

**Comment by jkroepke** [comment]
for me, the behaivor exists since weeks including today

**Comment by AeonFX** [comment]
> same problem with vaft script with ublock. Pre rolls ads happened
I just saw my pre-roll ads being correctly blocked, so this seems to be working for me. If you consistently get ads you could try a plain userscript manager extension like tampermonkey. After all ublocks jscriptlet injection is for advanced users only and it always felt like ublock is not made to properly handle userscripts (even though it was/is working if specially formatted to its syntax)

**Comment by pundoo** [comment]
This mid-roll ads are getting so annoying. I'm getting them on 'low-res' (480p) version as well.

**Comment by AeonFX** [comment]
Honestly I just did get mid-rolls in a stream that were correctly getting blocked. Haven't seen mid-rolls for some time now, so it seem everything is working correctly on my side.
