### ISSUE TITLE
Adguard premium, purple-adblock / TwitchAdSolutions Userscript / dns user filter method for blocking ads 

### ISSUE THREAD

**Issue by Itsfadixx** [pixeltris/TwitchAdSolutions#107]
My adguard twitch adblock config =
https://cdn.discordapp.com/attachments/1034562428303851621/1034964038171492413/adguard_settings_4.0.79_2710_015451.json

config v2=
https://cdn.discordapp.com/attachments/1034562428303851621/1035985733330161734/adguard_settings_4.0.79_2910_213346.json

used userscript extensions
and dns purple-adblock
with the help of the ||spade.sci.twitch.tv^ user dns filter
We managed to disable the ads in twitchapp/orange-tv /twitchmod,, Working as of October 27 2022
update:
For the mean time, some people have problems with the purple adblock dns server that starts with 45.131****
So i added a server
It's not adblock related, But it's meant to block twitch ads
Since twitch ads don't serve in these countries
For example / Iraq, My country dosent have ads,

So for now we used this dns provider, form this
website

We used
195.133.222.66
and
82.129.16.208

For the mean time, one fo the dudes didn't get the dns of purple adblock to work, He tired this dns servers, It worked for him with 0 ads

OrangeTV / TwitchMod community manager.
itsfadixx.

**Comment by Itsfadixx** [comment]
used userscript extensions
and dns purple-adblock
with the help if the ||spade.sci.twitch.tv^ user dns filter
We managed to disable the ads in twitchapp/orange-tv /twitchmod,, Working as of October 27 2022

**Comment by Itsfadixx** [comment]
update:
For the mean time, some people have problems with the purple adblock dns server that starts with 45.131****
So i added a server
It's not adblock related, But it's meant to block twitch ads
Since twitch ads don't sever in these countries
For example / Iraq, My country dosent have ads,

So for now we used this dns provider, form this
[website ](https://public-dns.info/nameserver/iq.html)

We used
195.133.222.66
and
82.129.16.208


For the mean time, one fo the dudes didn't see the dns of purple adblock to work, He tired this dns servers, It worked for him with 0 ads

**Comment by arthurbolsoni** [comment]
If you are using the proxy of purple like dns it no gonna work. its is only to get twitch m3u8 withot ads. dns is something else.

**Comment by pixeltris** [comment]
I'm going to close this but if you want to add it to the `full-list.md` feel free to make a PR.
