### ISSUE TITLE
chat box cursor moves to begining of message upon action of ad-blocking

### ISSUE THREAD

**Issue by randomnumbergen** [pixeltris/TwitchAdSolutions#108]
at the begining of the ad-blocking process and at the end of the ad-blocking the text cursor is moved to the start of the message box.
this practically makes typing a message during the ad-blocking process very difficult, and if not paying close attention results in incomprehensible messages being sent out.

interestingly the movement of the text cursor occurs only after one inital character is typed where the cursor was before the ad-blocking process began, after which it invariably jumps to the start of the message entry box.

this behaviour is not present if the chat box isn't selected during ad-blocking.

**Comment by pixeltris** [comment]
I'm going to assume this is on Firefox. There's a player quality change code for vaft under Firefox which involves invoking player elements. I don't have any plans of touching vaft moving forward so I'm closing this.
