### ISSUE TITLE
Twitch Stream stops on AD

### ISSUE THREAD

**Issue by TsinJu** [pixeltris/TwitchAdSolutions#112]
Still no Ads, but Twitch Stream stops now on ads (Ads Blocking Announcement in right corner) and continues after with uBlock solution

"Applying a script (uBlock Origin)"

**Comment by EldritchEevee** [comment]
Unfortunately for you, that script no longer works properly.

**Comment by fin98** [comment]
> Unfortunately for you, that script no longer works properly.

You have nothing better to do than to "take the piss" out of people here cause you seem to have found a way to make it work/ different fork? 

This isn't your local discord man. People here show their issues, let them known they also have it or help with a solution, not declaring they got a fix and explicitly say they're not going to share.

Get a grip

**Comment by knakamura8** [comment]
@TsinJu I have experienced similar hiccups.  Console log shows `AVC finishFrame called without active frame` when it occurs.  Stream will freeze for ~2-3 seconds, but ads will be successfully blocked.  Far better than experiencing ads, although I have only encountered this intermittent hitching recently.

**Comment by gecko4t** [comment]
He wasn't talking to you, but to the other guy that just decided to announce that the script no longer works without contributing at all, so before going off with the insults try to understand, this isn't Twitter.

**Comment by krystian3w** [comment]
Maybe he don't know nothing about JavaScript and network requests, then may lost years to learn programming language and how works server requests.

**Comment by pixeltris** [comment]
Closing in favor of https://github.com/pixeltris/TwitchAdSolutions/issues/114

**Comment by krystian3w** [comment]
Possible lock conversation to collaborators as too hejted.
