### ISSUE TITLE
Notify Swap userscript new not working

### ISSUE THREAD

**Issue by juliocoliveira** [pixeltris/TwitchAdSolutions#115]
I'm getting this on the start of every steam.
![image](https://user-images.githubusercontent.com/6606725/202872139-ae517c3a-e1d9-433d-a2e7-2e401e4a360b.png)
And also getting the purple commercial in progress screen: 
![image](https://user-images.githubusercontent.com/6606725/202872299-8e3e243b-8f1c-4e80-aa79-4526a1d34fb8.png)

Also the update and download path on the script is wrong: is set to https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-swap-new/notify-swap-new.user.js that does not exists, the right one is: 
https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/video-swap-new/video-swap-new.user.js

**Comment by pixeltris** [comment]
Working as intended.
