### ISSUE TITLE
Dyn scripts don't work since 1/13

### ISSUE THREAD

**Issue by extesy** [pixeltris/TwitchAdSolutions#12]
Looks like none of the dyn- family scripts work anymore since yesterday. I always get "network error" from the player when it tries to play ads. Disabling userscript fixes the issue.

**Comment by Suprcheese** [comment]
FWIW, I'm running dyn-skip-ublock-origin.js and I am seeing neither ads nor network errors.

**Comment by extesy** [comment]
I've just tried ublock version of dyn-skip-midroll-alt and it doesn't work either.

**Comment by pixeltris** [comment]
I'm currently not being served ads so it's difficult for me to test. However, some of those scripts behave differently to each other and will break in different ways.

@Suprcheese if you aren't served ads you wont see ads and wont see network errors as the scripts aren't modifying anything. You also wont see ads if you disable the script.

It looks like the `access_token` api endpoint has been removed which will break `dyn` / `dyn-video-swap`. It will also break `dyn-skip-midroll-alt` if the "skip" portion of that one fails. Switching to the gql api should fix `dyn`.

How is `dyn-skip-midroll-alt` broken? Does it give a network error? If it gives an infinite reload, did you ever have it working previously without infinite reload?

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/commit/4bc4274478ab57729352b63e10024280df45e490 should fix `dyn`, `dyn-video-swap`, `dyn-skip-midroll-alt` (the "alt" portion). I'm unable to test the skipping portion of the `dyn-skip` variants as I'm not being served ads.

**Comment by 0x263b** [comment]
Change the version number in the userscripts so Tampermonkey downloads the updated versions

**Comment by extesy** [comment]
The latest fix works perfectly (for now) so I'm closing the issue. Thanks a lot, @pixeltris!

**Comment by gwarser** [comment]
Resources should be updated with "uBlock filters". So if you click on clock next to "uBlock filters" and update, they should also update.
