### ISSUE TITLE
VAFT odd bug

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#122]
So, it sometimes succeeds in bypassing Midrolls, but has a TERRIBLE bug: it keeps the Ad Timer, the Blocking Ad message, and resets the player every 3~10 seconds, along with the timer.

**Comment by pixeltris** [comment]
It would be better to make an issue here which is where the code of vaft is pulled from https://github.com/cleanlock/VideoAdBlockForTwitch/issues
