### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by sk8rslim** [pixeltris/TwitchAdSolutions#123]
Ads getting through on all methods lately even TTV LoL or Lol Pro

**Comment by TsukiZero** [comment]
ads or the "commercial break" screen?

**Comment by sk8rslim** [comment]
Ads randomly getting through during mid-rolls. pre-rolls are being blocked by TTV Lol.

**Comment by sk8rslim** [comment]
Like I hit f5 and they go away again... but it is annoying that is happening... Been like this for two days so far.

**Comment by pixeltris** [comment]
Not something I can help with I'm afraid. None of the solutions are perfect.
