### ISSUE TITLE
Streamlink custom twitch.py

### ISSUE THREAD

**Issue by Sokoloft** [pixeltris/TwitchAdSolutions#125]
Hello,

A user by the name of "[Abject-File5319](https://www.reddit.com/user/Abject-File5319/)" on reddit made streamlink work with ttv lol and luminous-ttv. An edit of the full-list.md file should be made. Including that you need to edit your twitch.py file to either work with ttv.lol api or luminous-ttv for streamlink. This prevents the commercial break purple screen. The following are links to the two paste bins. If the user wants a copy of the original streamlink file, don't save it in the plugins dir. 

[luminous-ttv](https://pastebin.com/1pZxxC2W)
[ttv.lol](https://pastebin.com/xTWRBq40)
[reddit post](https://www.reddit.com/r/Streamlink/comments/yr29jz/comment/ixeuzeq/)
EDIT: This is old information. Refer to the github repo in my post below.

**Comment by Sokoloft** [comment]
The modified script has been added to a github repo [here](https://github.com/2bc4/streamlink-ttvlol).

**Comment by garbb** [comment]
I think it is worth mentioning also that there are links from that github repo to
[Luminous TTV server](https://github.com/AlyoshaVasilieva/luminous-ttv) and [Luminous TTV browser extension](https://github.com/AlyoshaVasilieva/luminous-ttv-ext) which you you can download and use on windows to get playlist via russia with Hola network which i just tested and this appears to work to avoid ads in the browser without having to rely on TTVLOL proxy being up.

**Comment by Sokoloft** [comment]
> I think it is worth mentioning also that there are links from that github repo to [Luminous TTV server](https://github.com/AlyoshaVasilieva/luminous-ttv) and [Luminous TTV browser extension](https://github.com/AlyoshaVasilieva/luminous-ttv-ext) which you you can download and use on windows to get playlist via russia with Hola network which I just tested and this appears to work to avoid ads in the browser without having to rely on TTVLOL proxy being up.

I have a PR awaiting approval that links to the github repo in my prior post. [This one](https://github.com/2bc4/streamlink-ttvlol). So that people viewing the full-list.md will see it under the streamlink entry. You can also use luminous-ttv server with that modified twitch.py file with streamlink.

**Comment by pixeltris** [comment]
Closing as the PR has been merged. I'm not sure how many people check the full list but hopefully that should be useful to those that do.
