### ISSUE TITLE
vaft when blocking ads, only the stream quality settings open

### ISSUE THREAD

**Issue by aleex5** [pixeltris/TwitchAdSolutions#130]
can this be solved?
![Screenshot 2022-12-20 at 04-25-27 Twitch](https://user-images.githubusercontent.com/35360938/208608169-84db931b-1b67-470b-97ab-3753c2ad52c7.png)

**Comment by placchio** [comment]
Im also having this bug on my vaft. 
@LightningW9 Sorry for the mention, but i saw your comment in the other thread ( #131 ) and how you find a solution for the script (i dont know anything about scripting and coding but somehow i was able to modify the line u pointed out and copy-paste it to pastebin, which btw i didnt even know also works on ublock)
anyway i was wondering if you have any idea on how to fix this other bug, thanks.

**Comment by LightningW9** [comment]
There is a patch here but idk if it's worth merging or not. I still get the purple screen on pre-roll and also mid-roll for some streamers but for streamers where it does work, I don't get stuttering or settings window opening.
https://github.com/LightningW9/TwitchAdSolutions/commit/49905ead0904c255ac4393aa97a080fdf0ef1eb0

**Comment by placchio** [comment]
Thanks for replying.
The thing is, since the specific vaft script i use somehow works for me (its like an old one), i dont want to completely change it with the risk of not working anymore like the other scripts.
Is there a way to only change the part related to the settings window opening? 
Like i said i dont know anything about coding so i wouldnt know which specific lines to look.
Thanks again.

**Comment by aleex5** [comment]
> There is a patch here but idk if it's worth merging or not. I still get the purple screen on pre-roll and also mid-roll for some streamers but for streamers where it does work, I don't get stuttering or settings window opening. [LightningW9@49905ea](https://github.com/LightningW9/TwitchAdSolutions/commit/49905ead0904c255ac4393aa97a080fdf0ef1eb0)

it solves the problem of showing the quality configuration window, but it has a problem when blocking ads, when it changes to 480p resolution, sometimes it stays loading for a couple of seconds before changing the resolution, I don't know if this can be improved.

**Comment by pixeltris** [comment]
Removed the thing which clicks this in https://github.com/pixeltris/TwitchAdSolutions/commit/05c023ff1c5b20e96b698df8503770b59c97f356

**Comment by pixeltris** [comment]
@LightningW9 that code sounds good if it fixes freezing issues. Feel free to make a PR.
