### ISSUE TITLE
video-swap-new no longer blocking as on December 28

### ISSUE THREAD

**Issue by RetiredDinosaur** [pixeltris/TwitchAdSolutions#131]
The game of cat and mouse continues. Twitch have worked around video-swap-new (ublock) and I'm seeing ads again :(

Edit. tried vaft (ublock) and I also get ads served

**Comment by pixeltris** [comment]
To clarify; do you see ads or this screen:

![image](https://user-images.githubusercontent.com/6952411/209838971-b96df812-9b07-4a55-b817-474c003b74e2.png)

If you see this it's expected and mentioned in the README. If you see actual ads could you state if you see them on prerolls, midrolls, or both?

**Comment by RetiredDinosaur** [comment]
Sorry for being vague, it's pre-roll ads and no I don't see the screen in your image

![pre-roll](https://user-images.githubusercontent.com/35304665/209840753-7d685216-bef6-41ff-aabf-677cdac0c061.JPG)

**Comment by FlareHeart** [comment]
I am also seeing ads both pre-rolls AND mid-rolls. Full ads. Not the purple screen. Has been happening for a few days now.

**Comment by pixeltris** [comment]
Okay, I'm currently seeing the ad break message. I'll keep an eye out and see what can be done when I see ads.

**Comment by RetiredDinosaur** [comment]
Thanks for your continued work on the project!

**Comment by RetiredDinosaur** [comment]
You may be onto something. Can confirm my UBO is on 1.46.0

**Comment by FlareHeart** [comment]
"Need to change application/javascript to text/javascript at the top"

Where is this? At the top of where? I don't see that setting, but I am on that version of uBO. (1.46.0)

**Comment by pixeltris** [comment]
@LightningW9 good spot, thanks. Closing as this should fix the problem.
