### ISSUE TITLE
Ads with VAFT 

### ISSUE THREAD

**Issue by Nerxxy** [pixeltris/TwitchAdSolutions#132]
![image](https://user-images.githubusercontent.com/37718547/210501626-d0876857-0f84-4626-8a1b-0b8ccbbaf7c9.png)
as of about 6hrs ago ive been getting ads with vaft.

on latest ublock dev build 1.46.1b4. could it just be downtime?

**Comment by aleex5** [comment]
adds

**Comment by TsukiZero** [comment]
It could also be ublock itself being temporarily unloaded. It happens sometimes on Firefox and there's no known cause, but there's kind of a tell: if you try to open the ublock menu, it will take longer to load or not load at all.

**Comment by Nerxxy** [comment]
> It could also be ublock itself being temporarily unloaded. It happens sometimes on Firefox and there's no known cause, but there's kind of a tell: if you try to open the ublock menu, it will take longer to load or not load at all. Which is why I favor userscript over ublock resource: I can more easily see it's working or not.

Sorry, i forgot to mention i was on opera. 

Also when using the user script i get this bug where it says "<channel> is having a commercial break" text with the count down on top of the stream also a LOT of buffering and sometimes the twitch purple/pink screen

**Comment by Nerxxy** [comment]
i have also just tried changing back to the normal uBlock (not dev build) and so far im no longer getting ads on the channels i was getting ads 🤔

**Comment by TsukiZero** [comment]
unfortunately, that's normal, to see the placeholder screen. No one updated their anti-twitch-ad scripts...

**Comment by Nerxxy** [comment]
Its a shame tbh, 2 days ago i wasnt getting any ads/placeholders and as of the post everything has just been a tad buggy

**Comment by pixeltris** [comment]
Are you using a permalink? If so you'll need to grab the latest one from the README. See #131. I just tested `1.46.1b8` and it worked fine with the latest permalink (but not the old permalink as it no longer loads it).

**Comment by Nerxxy** [comment]
> Are you using a permalink? If so you'll need to grab the latest one from the README. See #131. I just tested `1.46.1b8` and it worked fine with the latest permalink (but not the old permalink as it no longer loads it).

ive tried both the permalink and userscript, as well as lol tv pro (as a last resort), not all at the same time obvsly but was still getting the commercial break screen or the "blocking ads" overlay with the purple screen or even the stream with the text of "channel is taking a break" at the top left and the time left at the top right and past few days it sometimes also just completely pauses the stream.

**Comment by Nerxxy** [comment]
when it next happens ill screen show what i mean

**Comment by Nerxxy** [comment]
![image](https://user-images.githubusercontent.com/37718547/211685992-3c5d861e-a41c-44fe-944c-f4ad9916e81d.png)
i get this with the user script, but im now on permalink and seems to be working fine for now. i was using it when u updated it but still had issues. hope it doesnt break now 🙏

**Comment by pixeltris** [comment]
>but was still getting the commercial break screen or the "blocking ads" overlay with the purple screen or even the stream with the text of "channel is taking a break"

This is expected and mentioned in the README.

**Comment by Nerxxy** [comment]
> This is expected and mentioned in the README.

ah ok i hadnt seen that bit updated, i normally just gloss over it and grab the perma link and paste it in. didnt it normally not show the commercial break?

**Comment by revunix** [comment]
I'm using [TTV LOL PRO](https://github.com/younesaassila/ttv-lol-pro/releases/tag/v1.7.0-beta.2) with this Server (https://as.luminous.dev) as primary for a few weeks. I don't see any ads.

**Comment by Nerxxy** [comment]
![image](https://user-images.githubusercontent.com/37718547/211967122-8cfbd94c-04e2-4475-a87d-0da9c349a195.png)
i have also been getting this bug, where it says that theres an ad running while also having the stream showing and being completely paused, its been like that for the last 20mins, this is using the perma link on uBlock ver 1.46.0

**Comment by Nerxxy** [comment]
Update on this, i think VAFT is broken entirely, im not even getting the purple screen just getting ads all the time, only thing that works is revunix's solution posted above

**Comment by TsukiZero** [comment]
> Update on this, i think VAFT is broken entirely, im not even getting the purple screen just getting ads all the time, only thing that works is revunix's solution posted above

It bleeds through TTV LOL PRO as well, so the cause runs deeper than that.

**Comment by Nerxxy** [comment]
> It bleeds through TTV LOL PRO as well, so the cause runs deeper than that.

Personally I've not seen one get past TTV LOL PRO, with the luminous server, yet only VAFT.

Though I do have them both running at the same time so maybe that's doing some funky shit? idk.

**Comment by TsukiZero** [comment]
No, Twitch broke something, adblocks are now defective.

**Comment by heryoff** [comment]
@

> I'm using [TTV LOL PRO](https://github.com/younesaassila/ttv-lol-pro/releases/tag/v1.7.0-beta.2) with this Server (https://as.luminous.dev) as primary for a few weeks. I don't see any ads.

Hey, sorry to bother. How did you manage to change the TTV LOL PRO default server?
(and, is there anyway to host your own?)

**Comment by TsukiZero** [comment]
It's not very straight-forward, but you in Firefox you need to go to Manage Extension, click the `...` next to the extension's toggle button, then click "Options" in the dropdown

**Comment by heryoff** [comment]
> It's not very straight-forward, but you in Firefox you need to go to Manage Extension, click the `...` next to the extension's toggle button, then click "Options" in the dropdown

thx, got it. Still having ads tho... (ru)
