### ISSUE TITLE
"Video Swap New" bugs and quirk

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#133]
Video Swap (New) sometimes causes the video feed to freeze but the audio to keep going, requiring play & pause to resume and synchronize them. This happens after the midrolls, whether they are bypassed (I'll detail this later) or not.

Sometimes the quality is lowered for no apparent reason. And I mean lowered, as in it goes from 480p to 160p. Managed to remedy this by altering the script "Twitch - Disable automatic video downscale" by CommanderRoot to set the quality to 480p30, and so far there has been no issues.

VERY frequently it increases the latency without a sign and without a fix (resetting player doesn't help, refreshing page might help, but a very distant "might" at that).

Sometimes it's possible to end a midroll streak sooner by resetting the player 10+ seconds into a midroll, but this somehow causes the player to keep refreshing every 5+ seconds until the midrolls ends (and has a huge chance of video freeze with audio going). So it might be possible to get rid of midrolls entirely by evoking a reset player at some point there.

**Comment by pixeltris** [comment]
Closing in favor of your other issue #119
