### ISSUE TITLE
Video-Swap-New SEEMS to be incompatible with Creating Clips

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#134]
Normally or with VAFT, when you click to Clip the clip creator shows the select region proper within the seek bar highlighted.

HOWEVER with VSN it shows not only a negative position, but the selected regions is far ahead of what the Create Clips shows, making it impossible to have control of what you want to clip as it messes with the timing.

**Comment by pixeltris** [comment]
Don't have an account. Wont be fixing. PRs welcome to fix it.
