### ISSUE TITLE
[New Solution] Third-party CDNs

### ISSUE THREAD

**Issue by mingyoq** [pixeltris/TwitchAdSolutions#136]
In addition to their own servers, Twitch uses third-party CDNs to deliver HLS streams. These CDNs do not seem to serve server-side injected ads. Available CDNs include:
* `akamai_{eu,na,latam,asia,korea}` (regions don't seem to have any effect as they use anycast, but further testing is needed)
* `cloudfront_{global,korea}`
* `limelight_{kt,lg,sk}` (seem like Korea-specific CDNs)

When requesting the playlist from `usher.twitch.tv`, the `force_segment_node` parameter can be used to force it to use a particular node to serve the stream. This parameter is restricted to internal networks, but this can be bypassed via setting the `X-Forwarded-For` header to `::1` (IPv6 localhost).

Therefore, by modifying the request to `https://usher.ttvnw.net/api/channel/hls/:id.m3u8`, adding `X-Forwarded-For: ::1` header and adding `force_segment_node=akamai_na` parameter, ads can be blocked.

**Comment by knakamura8** [comment]
Do Korean nodes serve at resolutions higher than 720p?

**Comment by schrobby** [comment]
I like the idea behind this, but I can't get it to work. 

I've tried setting `force_segment_node` to all of the suggested CDNs and adding the `X-Forwarded-For: ::1` header, but I still end up with a playlist that points to one of Twitch's weaver clusters on `ttvnw.net`. 

Did you make any additional adjustments not mentioned in your original post?

**Comment by aeongdesu** [comment]
seems they blocked it yesterday

**Comment by berkant** [comment]
No longer working. It's just hilarious how they keep stalking this repo.
