### ISSUE TITLE
Problem on Alternate player for twitch.tv

### ISSUE THREAD

**Issue by Bricio92** [pixeltris/TwitchAdSolutions#137]
There is too much delay between video and chat.

**Comment by EldritchEevee** [comment]
That's exactly what you get for using an adblocker.

**Comment by patheticcockroach** [comment]
Actually I use this add-on too and never noticed a delay.
Maybe check your buffering settings, these could add a significant delay if set in certain ways. Basically: smallest buffer = shortest delay (but a risk of interruptions if your internet connection isn't too stable)

**Comment by dhasial** [comment]
@EldritchEevee The internet is borderline unusable without an adblocker. Go fuck yourself.
