### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by Aryytt** [pixeltris/TwitchAdSolutions#138]
Hello, Does anyone know of a solution to block ads? I have tried all of them, but nothing works.

**Comment by heryoff** [comment]
Same here, instead when trying an adblocker I get bombarded with ads. Like 7-9

**Comment by Rachid90** [comment]
TTV used to work for me for the last week. But not now anymore.

**Comment by Aryytt** [comment]
I'm just using a VPN and connecting to Poland. That seems to be working for now.

**Comment by mirko991** [comment]
> I'm just using a VPN and connecting to Poland. That seems to be working for now.

Yes, ok, but a VPN costs. Then we can pay for Twitch Turbo and we are ok.

**Comment by heryoff** [comment]
> > I'm just using a VPN and connecting to Poland. That seems to be working for now.
> 
> Yes, ok, but a VPN costs. Then we can pay for Twitch Turbo and we are ok.

I'm using a extension that for now works, I don't even get the purple background message.
I don't really want to link it since it seems stuff from this repo get patched soon

**Comment by Pelotedeneige** [comment]
Understandable but a pain for us. At least I only have the purple screen.

**Comment by vmx-kbabenko** [comment]
Any idea which domains to send through the VPN? So far I have these:
*.twitch.tv
*.twitchcdn.net
*.ext-twitch.tv
*.twitchtv.net
And still sometimes it shows ads.
I don't wanna send all of the traffic through the VPN.

**Comment by llaurenss** [comment]
try *.hls.ttvnw.net

**Comment by LCDraws** [comment]
TTV LOL PRO is working for me

**Comment by CharisardTT** [comment]
I'm using this extension https://microsoftedge.microsoft.com/addons/detail/twitch-adblock/ebopkbdmemhbmhemdgajhagjgeiffhik but I think I'll try the new TTV LOL PRO, bc the one I have is not working smoothly anymore

**Comment by OnePunkArmy** [comment]
TTV LOL PRO not working. I'm still getting pre-roll ads.

**Comment by LCDraws** [comment]
> TTV LOL PRO not working. I'm still getting pre-roll ads.

yah, stoped working recently

**Comment by MisterSheeple** [comment]
TTV LOL PRO still works fine for me. It does occasionally fail, so just refresh the page and usually that does the trick. TTV LOL PRO's developer suggests using it in conjunction with VAFT for a higher rate of success when it comes to removing ads.

**Comment by propagandism** [comment]
https://github.com/AdguardTeam/AdGuardExtra/
