### ISSUE TITLE
TTV LOL is no longer on the Firefox Addon Store

### ISSUE THREAD

**Issue by EatingCarBatteries** [pixeltris/TwitchAdSolutions#142]
https://addons.mozilla.org/en-US/firefox/addon/ttv-lol/

![image](https://user-images.githubusercontent.com/40326108/222632605-12881600-fbac-463f-a022-8018ae9179cb.png)

**Comment by MisterSheeple** [comment]
#139 is a relevant pull that removes the Firefox links from both md files.

**Comment by propagandism** [comment]
https://github.com/AdguardTeam/AdGuardExtra/

**Comment by pixeltris** [comment]
Thanks @MisterSheeple
