### ISSUE TITLE
not gaining channle points

### ISSUE THREAD

**Issue by ranehal** [pixeltris/TwitchAdSolutions#143]
not gaining channle points

**Comment by salmon85** [comment]
started happening recently for me too

**Comment by MisterSheeple** [comment]
What ad solution(s) are you using?

**Comment by salmon85** [comment]
> > What ad solution(s) are you using?
> 
> For me, not getting points with "Alternate Player for Twitch.tv" since a few days

same as you, alt player for twitch

**Comment by ranehal** [comment]
Let me know if you find any solutions,  actually any kind of alternate player like twitch radio isn't working for lurking. I need them for lurking on low resource and bandwidth

**Comment by 64fanatic** [comment]
Same here, god Twitch is petty.

**Comment by patheticcockroach** [comment]
> Same here, god Twitch is petty.

*Amazon 👀

**Comment by Pixydidnothingwrong** [comment]
those coding cagie wagie slaves work hours on end to make sure the gentiles cant have any form of enjoyment of watching a stream without being slapped in the face with ads or so help the rabbi in charge they will brick your browser and render your brave browser uninstallable/unupdatable.

**Comment by pixeltris** [comment]
Not something I care about unfortunately.
