### ISSUE TITLE
ad block on twitch doesn´t work any more

### ISSUE THREAD

**Issue by kurt-jooss** [pixeltris/TwitchAdSolutions#146]
since a few days I get ads again using the script (uBlock Origin) and a window opens where you can choose the stream quaility. It´s the same as described in issue #130
![Screenshot 2023-04-04 at 17-07-09 Twitch](https://user-images.githubusercontent.com/129534366/229836713-6b5d9ab2-63fe-4d8c-89f8-736d29858371.png)

**Comment by kurt-jooss** [comment]
![Screenshot 2023-04-04 at 17-07-09 Twitch](https://user-images.githubusercontent.com/129534366/229836445-588f0f32-0ce1-4785-b437-0330b151f15e.png)

**Comment by Pelotedeneige** [comment]
Nope. You still have the "preparing your stream" screen. Doesn't work either.

**Comment by pixeltris** [comment]
Removed the thing that clicks the spinner in https://github.com/pixeltris/TwitchAdSolutions/commit/05c023ff1c5b20e96b698df8503770b59c97f356 (though may cause freezing)
