### ISSUE TITLE
Well, this project is dead...

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#149]
Anyone got alternatives we can rely on?

**Comment by dhasial** [comment]
It's also now semi-broken as of today, at least for VODS. I don't have an alternative at the moment.

**Comment by niftyszn** [comment]
use https://www.blocktwitchads.com/?utm_source=tabp_install

**Comment by roncli** [comment]
Also looking for an alternative, the one linked is a data farming extension, so if there are any others that are working, please share!

I used to have something like 12 monthly subscriptions going at any given time.  The moment they started their vendetta of breaking ad blockers, I cancelled all my subs and haven't paid for another one.  I hope there are others like me that stopped supporting Twitch and found other ways to support streamers until their advertising department figures it out.

**Comment by MikeKlem** [comment]
Twitch just needs to see that Ad supported streaming is not a sustainable source of revenue.
They should be concentrating their efforts on upselling the Prime subscriptions. Subscriptions to channels with strong communities, that continue to grow would be a better use of their resources.

Open Source Android App Stores have some alternatives, trying to find the same on iOS. Network level blocking like the PiHole is beyond most casual viewers

**Comment by deaglenomics** [comment]
Yes twitch staff, there is nothing to see here. You have won.





































































































































































....or maybe the methods people use now are not being released as they get patched up within days. *think-emoji*|

**Comment by MikeKlem** [comment]
https://github.com/fgl27/SmartTwitchTV

**Comment by deaglenomics** [comment]
Why not just link SoundTV ? that is also android but the difference is that it is in playstore and easily installed.

**Comment by TheEnhas** [comment]
TTV LOL PRO's newest beta is the only thing that still reliably works but as of right now it's Firefox-only. Everything else is mostly ineffective at this point.

**Comment by Yonleyn** [comment]
Any news? Because I've tried all the extensions on Chrome, and it still doesn't work. I have "Commercial Break" with 2 ads that last 30 seconds each, and it's a pain in the ass.

**Comment by ANaPhOrAX** [comment]
> TTV LOL PRO's newest beta is the only thing that still reliably works but as of right now it's Firefox-only. Everything else is mostly ineffective at this point.

ttv lol pro doesn't really do much for me tbh. I'm still getting a ton of ads even with it.

**Comment by roncli** [comment]
> ttv lol pro doesn't really do much for me tbh. I'm still getting a ton of ads even with it.

Largely because they have essentially given up as well, check their latest release notes on the beta.

**Comment by pixeltris** [comment]
PRs are welcome (both linking other solutions and new scripts). I haven't actively been looking for other solutions. I still maintain `video-swap-new`.
