### ISSUE TITLE
seeing 

### ISSUE THREAD

**Issue by ItsBluey** [pixeltris/TwitchAdSolutions#151]
these are not working im seeing ads ive tired all of them (the scripts )

**Comment by pixeltris** [comment]
Working for me. Would help you but you've provided no further info. Closing.

**Comment by ItsBluey** [comment]
what info ? i installed on ublock and instant get an ads with it both scripts i cleared cache and i reinstalled ublock and relogged in twitch ads instantly or black/blank screen both chrome and firefox
