### ISSUE TITLE
Applying a script (uBlock Origin) Issue

### ISSUE THREAD

**Issue by Gamerboi520** [pixeltris/TwitchAdSolutions#154]
Applying the following 
Navigate to the uBlock Origin Dashboard (the extension options)
Under the My filters tab add twitch.tv##+js(twitch-videoad).
Under the Settings tab, enable I am an advanced user, then click the cog that appears. Modify the value of userResourcesLocation from unset to the full url of the solution you wish to use (if a url is already in use, add a space after the existing url). e.g. userResourcesLocation https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js
To ensure uBlock Origin loads the script I recommend that you disable/enable the uBlock Origin extension (or restart your browser).

Causes twitch to be stuck on a loading screen (forever it seems) 

![image_2023-06-01_151955288](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/17b04882-16e8-422f-b241-7de4fbc6a290)
![image_2023-06-01_152017546](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/4e87d3ff-4fb5-4ec1-a895-bef7c1c3eee1)
![image_2023-06-01_152043882](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/009601df-232c-4715-9505-408d7ad6f197)

**Comment by gwarser** [comment]
Try the final URL after redirection: `https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js`.
