### ISSUE TITLE
video-swap-new is not reseting quality

### ISSUE THREAD

**Issue by DiegoAce** [pixeltris/TwitchAdSolutions#156]
I'm using the newest ublock permalink for firefox. It seems to correctly switch to 360p whenever an ad would show, but then it never switches back to source quality. After the ad the video flashes black as if the video player resets, but it stays on 360p. Is this intended? Can this be fixed?

**Comment by pixeltris** [comment]
Side effect of the lower res stream and the player reset. I did actually fix this before on another solution by using the original m3u8 and swapping out all of the stream urls with the 360p which preserves the resolution list. I'll probably do the same when I get the chance, or if someone wants to do it PRs are welcome.

https://github.com/pixeltris/TwitchAdSolutions/blob/05c13983eb15c966810d93473a96c28aefc7aea0/notify-swap/notify-swap.user.js#L318-L330

**Comment by fin98** [comment]
Tried the video swap one yesterday & it works 1/10 times when loading in a stream, 9/10 it just stays black trying to load. Even on the stream I'm subscribed to this issue occurred. It does work when you're already in a stream, it goes to 360p. Even now I still can't load in a stream.

Switched to Vaft just now & it doesn't seem to be happening. Just letting you know about this

**Comment by StevensND** [comment]
> Tried the video swap one yesterday & it works 1/10 times when loading in a stream, 9/10 it just stays black trying to load. Even on the stream I'm subscribed to this issue occurred. It does work when you're already in a stream, it goes to 360p. Even now I still can't load in a stream.
> 
> Switched to Vaft just now & it doesn't seem to be happening on Vaft, so I'll just be using this one.
> 
> Just letting you know about this

Using Vaft too. Working fine.

**Comment by StevensND** [comment]
> hi mate im newbie in this but may i ask where should i apply this code in ublock.

https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin

**Comment by edgardofaria** [comment]
Having the same problem using Vaft, every time it ends blocking, the quality is always on 360p.

**Comment by StevensND** [comment]
> Having the same problem using Vaft, every time it ends blocking, the quality is always on 360p.

Fork the repository and change line 61 scope.PlayerType2 = to embed

That solve the 360p to me.

**Comment by pflanzenandi** [comment]
> Having the same problem using Vaft, every time it ends blocking, the quality is always on 360p.

For me it works perfectly. But I use the userscript.

**Comment by lgrano** [comment]
Also having this issue, the ublock script(permalink) does not reset the video quality, the resolution its stuck at 360p after it swaps back to the non embed player.

**Comment by Lunarhawk** [comment]
Started using this today and it seems to still be an issue w/ ublock permalink in chrome where it stays 360p after swapping back. Were you not able to find a good fix for it?

**Comment by pixeltris** [comment]
Fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/c3663da4a9c62c87051e6666f57765319c0b3a3a
