### ISSUE TITLE
Not workin anymore with uBlock Origin

### ISSUE THREAD

**Issue by unitrix0** [pixeltris/TwitchAdSolutions#168]
The script seems to be broken for uBlock origin. It worked nicely so far but as of today not anymore. 🤷‍♂️

**Comment by lgrano** [comment]
Same issue here, ublock script is broken, was working couple days ago.

**Comment by PleasantMachine9** [comment]
This may help: https://github.com/pixeltris/TwitchAdSolutions/pull/169

Raw url for uBlock: https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/e76607bd7049598d8531b6455c6c1ba4f8036f48/vaft/vaft-ublock-origin.js

**Comment by tballas** [comment]
Still working for me, but I did update to the most recent permalink in commit 3a8954e when it was added June 1st. Only issue I've noticed is using Multistre.am sometimes muted streams unmute when it's blocking a mid-roll ad.

**Comment by unitrix0** [comment]
It's strange. I didn't change anything, now it's working again for me too.
