### ISSUE TITLE
video-swap-new uBlock Origin unmuting, muted embedded streams on multistream sites

### ISSUE THREAD

**Issue by tballas** [pixeltris/TwitchAdSolutions#170]
Using video-swap-new though uBlock Origin Chrome, on Windows 10, the most recent permalink in commit 3a8954e from June 1st, is working well for me.

One issue I've noticed is using Multistre.am sometimes muted streams unmute when it's blocking mid-roll ads. Noticed in the code that it checks and stores the muted state but for some reason it doesn't leave it muted? I have not noticed this on twitch itself.

I've noticed it also mutes, unmuted embedded streams also.

**Comment by pixeltris** [comment]
Should be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/c3663da4a9c62c87051e6666f57765319c0b3a3a
