### ISSUE TITLE
video-swap-new uBlock Origin permalink no longer working 

### ISSUE THREAD

**Issue by Gamerboi520** [pixeltris/TwitchAdSolutions#172]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/d7552660-ce3a-4366-8ef3-4a35e5aac0fb)

Forever loading than ends with Network error refresh video player.

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/d9f026d8-cab1-41f6-ad08-6adcc2fc4977)

**Comment by Gamerboi520** [comment]
Even tried  solutions from https://www.reddit.com/r/uBlockOrigin/comments/10yvx1d/ublock_origin_isnt_blocking_twitch_ads_anymore/

They also did not work
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/598b5957-f327-431c-b959-8096542b1ed4)

**Comment by Gamerboi520** [comment]
These 4 methods that i tried also did not work it keeps buffering forever
video-swap-new 
[ublock](https://github.com/pixeltris/TwitchAdSolutions/raw/master/video-swap-new/video-swap-new-ublock-origin.js) 

[ublock (permalink) (https://github.com/pixeltris/TwitchAdSolutions/raw/2bfda1e1a1c55d7b2dd4a541242acb5033644237/video-swap-new/video-swap-new-ublock-origin.js)

vaft - [ublock](https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js) 

[ublock (permalink)](https://github.com/pixeltris/TwitchAdSolutions/raw/2bfda1e1a1c55d7b2dd4a541242acb5033644237/vaft/vaft-ublock-origin.js)

**Comment by young03600** [comment]
same issue
black screen foever

**Comment by xkorsikk** [comment]
same there

**Comment by TsukiZero** [comment]
the userscript version seems to be working fine, granted I changed the playertype in the script

**Comment by DaveKap** [comment]
Only today the vaft uBlock script stopped working for me. If anyone has something working (such as the person above saying they changed playertype) please document it for the rest of us to use. Thank you!
