### ISSUE TITLE
vaft.user.js No Longer Works

### ISSUE THREAD

**Issue by Uraniumhazee** [pixeltris/TwitchAdSolutions#174]
I installed Tampermarkey plugin for Chrome and before i was using https://github.com/pixeltris/TwitchAdSolutions/blob/master/vaft/vaft.user.js for it and was working nice!

Today i saw some some ads and it no longer works!

Thanks

**Comment by TsukiZero** [comment]
Tried out on Firefox? Because Google is notoriously making a push for forced advertisement.

**Comment by pflanzenandi** [comment]
I dont see any ads and stopt using vaft therefore. Just ublock and blocked 3rd-party-frames.

**Comment by pixeltris** [comment]
Works for me on prerolls. I'm unable to test midrolls. Twitch sometimes does A/B testing with certain features which may result in ads. I'll keep an eye out.

@pflanzenandi that's not useful info given this issue is talking about a specific script.

**Comment by pflanzenandi** [comment]
@pixeltris You are right. But your git is also about Twitch Ad solutions in general. Just want to help. Maybe you want to add Ublock with 3rd-party frames blocked as a viable solution.

**Comment by pixeltris** [comment]
These solutions are for Twitch's SSAI. uBlock Origin with 3rd-party frames blocked does't prevent SSAI afaik (I just ran some tests with this setup which got ads). If you aren't seeing these types of ads it's likely they aren't being served to you for one reason or another.

**Comment by Uraniumhazee** [comment]
> Tried out on Firefox? Because Google is notoriously making a push for forced advertisement.



> no longer works on firefox as of july 31, 2023



> I dont see any ads and stopt using vaft therefore. Just ublock and blocked 3rd-party-frames.



> idk what to tell you. I installed the script through tampermonkey to use on firefox along with ublock and I'm still being forced ads



> Works for me on prerolls. I'm unable to test midrolls. Twitch sometimes does A/B testing with certain features which may result in ads. I'll keep an eye out.
> 
> @pflanzenandi that's not useful info given this issue is talking about a specific script.



> @pixeltris You are right. But your git is also about Twitch Ad solutions in general. Just want to help. Maybe you want to add Ublock with 3rd-party frames blocked as a viable solution.



> These solutions are for Twitch's SSAI. uBlock Origin with 3rd-party frames blocked does't prevent SSAI afaik (I just ran some tests with this setup which got ads). If you aren't seeing these types of ads it's likely they aren't being served to you for one reason or another.

I use both Adguard Adblocker + Tampermonkey + TwitchAdSolutions
Now there is no ad!

If i don't use Adguard Adblocker , i see adds

Thanks

**Comment by pflanzenandi** [comment]
> These solutions are for Twitch's SSAI. uBlock Origin with 3rd-party frames blocked does't prevent SSAI afaik (I just ran some tests with this setup which got ads). If you aren't seeing these types of ads it's likely they aren't being served to you for one reason or another.

[my-ublock-backup_2023-08-01_22.18.31.txt](https://github.com/pixeltris/TwitchAdSolutions/files/12233667/my-ublock-backup_2023-08-01_22.18.31.txt)
