### ISSUE TITLE
Twitch vaft script paused stream after the first mid roll ads constantly when ads starts?

### ISSUE THREAD

**Issue by RonvD** [pixeltris/TwitchAdSolutions#175]
What's happening with the Twitch vaft script? It paused the stream I watch after the first mid roll ads constantly when ads starts. I goes smoothly when the first mid roll starts when I watch a stream but than the problem starts when the second mid roll ads start. Very annoying. Someone have a solution or update for this that solved the problem?
Im using Firefox and this codes I'm using in My Filters: twitch.tv##+js(twitch-videoad) and userResourcesLocation https://raw.githubusercontent.com/rhobales/twitch-adblock/master/twitch-adblock.js in advanced settings.

**Comment by alanxummp** [comment]
im using this 
userResourcesLocation https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/2bfda1e1a1c55d7b2dd4a541242acb5033644237/video-swap-new/video-swap-new-ublock-origin.js

it doesnt pause, but i have to switch back to max quality every time the ad end, so annoyning as well i might as well just watch it on xtra. I have not find a solution yet, this is the only problem i can see.

**Comment by buckwilicker** [comment]
Try using the script that this repo provides.

https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js

Do note that this one seems to have issues as of the last week or so too. Random stream freezes requiring a refresh or video stream pauses and audio continues.

**Comment by alanxummp** [comment]
i went back give ttvlol another try and this https://github.com/younesaassila/ttv-lol-pro/discussions/130#discussioncomment-6655172  has been working flawlessly for me.
i do have nord, but it is so cheap might consider it free.

**Comment by TsukiZero** [comment]
VAFT is definitely dead. Video Swap New still works, but you need to switch the player type from "autoplay" to "embed", and even then it'll start using source quality during ads.

**Comment by pixeltris** [comment]
Consolidating all freezing / pausing / playback issues for `vaft` into #164
