### ISSUE TITLE
TTV LOL vs TTV LOL Pro

### ISSUE THREAD

**Issue by curya** [pixeltris/TwitchAdSolutions#176]
I couldn't find any information on this so I'm asking here. What's the difference between TTV LOL and TTV LOL Pro? It looks like TTV LOL hasn't been updated in years so I'd assume Pro is the new version. But if that's the case, why is the original version still linked here?

**Comment by pixeltris** [comment]
TTV LOL is a proxy which is hosted by them along with an extension for using the proxy. TTV LOL Pro was initially just UI improvements which used the same proxy. It now has support for different types of proxies. I think they both work but I haven't tried the original.

If the original version no longer works I can remove it. If it still works I'll keep it linked.
