### ISSUE TITLE
Consistent buffering with Twitch AdBlock

### ISSUE THREAD

**Issue by swiftaes** [pixeltris/TwitchAdSolutions#18]
When using the Twitch AdBlock addon for chrome I am constantly getting buffering ever few seconds on streams whether I refresh or not switch streams etc.

**Comment by pixeltris** [comment]
I'm not the developer of `Twitch AdBlock`. For issues directly related to that extension refer to https://github.com/ChoosenEye/Twitch-Adblock-Bugs/issues
