### ISSUE TITLE
Stream constantly loading when ads appear until they finish

### ISSUE THREAD

**Issue by BardicWaves** [pixeltris/TwitchAdSolutions#180]
Instead of blocking ads and allowing me to continue watching, now when ads pop the stream buffers until they are done.

**Comment by JasperKazai** [comment]
Yeah, I'm getting this too. Either have to constantly pause/unpause the stream when it's blocking ads to keep it playing, or refresh the page. But it's not consistent on every Twitch channel - some streams seem to have a 100% chance to freeze when blocking ads, and some streams it almost never happens. I don't know why that is.

**Comment by pixeltris** [comment]
Which script?

**Comment by Zero3K** [comment]
It is happening for me with VAFT.

**Comment by Rmurray2006** [comment]
except the one who made this hub didn't check thoroughly ad abruptly without trying my fix which he closed and said it did nothing. it had amazon ads that needed blocked and it did work. the author of the addon needs to think before leaping

**Comment by pixeltris** [comment]
@Rmurray2006 my apologies. If you could explain how the filters alter the application of the script in the issue you created that would be great. Ref #183

**Comment by CJStyles123** [comment]
I used the script all the way down in the readme such as changing the unset to the provided link and adding the thing to filters list and when there's an ad, my stream will freeze for like 3-5 seconds and fixed itself. It does this constantly.

**Comment by Rmurray2006** [comment]
> @Rmurray2006 my apologies. If you could explain how the filters alter the application of the script in the issue you created that would be great. Ref #183

replied under #183

**Comment by CJStyles123** [comment]
> I used the script all the way down in the readme such as changing the unset to the provided link and adding the thing to filters list and when there's an ad, my stream will freeze for like 3-10 seconds and fixed itself. It does this constantly.
> 
> Streams I've tested on:
> KaiCenat 

I've also tested this in other streams like CaseOh and Jynzxi too and get the same results. Twitch is cracking down.

**Comment by pixeltris** [comment]
Consolidating all freezing / pausing / playback issues for `vaft` into #164
