### ISSUE TITLE
Not a issue except it didnt work unless I added

### ISSUE THREAD

**Issue by Rmurray2006** [pixeltris/TwitchAdSolutions#183]
I put this in Ublock Filters with the setup included on the main page of this hub.

k.twitchcdn.net##+js(twitch-videoad)
sq-tungsten-ts.amazon-adsystem.com##+js(/noop?si=650&bidR=33Xerpb8kd7CMlzJU76l0Q&cb=1882556 twitch-videoad)
sq-tungsten-ts.amazon-adsystem.com##+js(twitch-videoad)

**Comment by pixeltris** [comment]
Those filters aren't doing anything useful.

**Comment by Rmurray2006** [comment]
the filters above containing , sq-tungsten-ts.amazon-adsystem.com are blocking the ad system completely as the twitch.tv one in the readme is no longer used. if you dont believe me. try it on a browser of choice

**Comment by Rmurray2006** [comment]
yes i kept twitch.tv there just in case but works without it with the new addition

**Comment by gwarser** [comment]
Do you see that your filters are highlighted with orange? This is warning color. In this case, it means, these resources do not exist. Your filters do nothing.

**Comment by brasqo** [comment]
Currently working with:

::: "My filters" in ublock :::
`twitch.tv##+js(twitch-videoad)`
`k.twitchcdn.net##+js(twitch-videoad)`
`sq-tungsten-ts.amazon-adsystem.com##+js(twitch-videoad)`

::: Using VideoAdBlockForTwitch-master\chrome :::
Using TTV LOL as a proxy

Only issue I'm seeing is during midroll ads. The video quality drops below max, but the video and audio continue throughout the ad.

**Comment by Rmurray2006** [comment]
> Do you see that your filters are highlighted with orange? This is warning color. In this case, it means, these resources do not exist. Your filters do nothing.

it was orange because im using ublock and a custom dark theme for the browser. it was also orange when i did the initial setup. so think again. ik whats working in front of me you dont

**Comment by pixeltris** [comment]
`twitch.tv##+js(twitch-videoad)` This will inject the script you provide in `userResourcesLocation` when you navigate to twitch.tv, right? And that is the only requirement for the script to function.

These:

```
k.twitchcdn.net##+js(twitch-videoad)
sq-tungsten-ts.amazon-adsystem.com##+js(/noop?si=650&bidR=33Xerpb8kd7CMlzJU76l0Q&cb=1882556 twitch-videoad)
sq-tungsten-ts.amazon-adsystem.com##+js(twitch-videoad)
```

Don't apply the script for me. I'm honestly not 100% sure what the requirements for script injection are but I assume the `twitch.tv` part of `twitch.tv##+js(twitch-videoad)` must match the `document.location` (the page url) in order for the script to inject. So your filters wont ever inject the script unless I'm mistaken.

**Comment by Rmurray2006** [comment]
> `twitch.tv##+js(twitch-videoad)` This will inject the script you provide in `userResourcesLocation` when you navigate to twitch.tv, right? And that is the only requirement for the script to function.
> 
> These:
> 
> ```
> k.twitchcdn.net##+js(twitch-videoad)
> sq-tungsten-ts.amazon-adsystem.com##+js(/noop?si=650&bidR=33Xerpb8kd7CMlzJU76l0Q&cb=1882556 twitch-videoad)
> sq-tungsten-ts.amazon-adsystem.com##+js(twitch-videoad)
> ```
> 
> Don't apply the script for me. I'm honestly not 100% sure what the requirements for script injection are but I assume the `twitch.tv` part of `twitch.tv##+js(twitch-videoad)` must match the `document.location` (the page url) in order for the script to inject. So your filters wont ever inject the script unless I'm mistaken.

not gonna matter cause you don't wana try it. i have 0 ads now. gl with the hub i guess. you said unless im mistaken proving you didnt even try. its biased by assumption. i can see it on my screen right now and its working because its blocking amazon

**Comment by pixeltris** [comment]
I did try it as I mentioned in my previous post. Those filters don't inject the script for me. This gets logged to the console on script injection:

https://github.com/pixeltris/TwitchAdSolutions/blob/e8ff2b03a579532b36adc4319cde043cecc0d0c8/vaft/vaft-ublock-origin.js#L271

Without `twitch.tv##+js(twitch-videoad)`, the script doesn't get injected for me.
