### ISSUE TITLE
VAFT should also remove the ads from VODs

### ISSUE THREAD

**Issue by Zero3K** [pixeltris/TwitchAdSolutions#184]
*subject*

**Comment by zGato** [comment]
Use uBlock Origin for VODs. Or modify the script yourself.

**Comment by pixeltris** [comment]
Out of scope for this project. Use a regular ad blocker for these.

**Comment by Zero3K** [comment]
Maybe someone else could add this functionality to it.

**Comment by zGato** [comment]
Open source code, do it yourself.
