### ISSUE TITLE
TTV LOL + TTV LOL PRO No longer working

### ISSUE THREAD

**Issue by 21Sully** [pixeltris/TwitchAdSolutions#186]
The TTV LOL extensions normal and pro version no longer working. Constantly buffering/crashing the stream

**Comment by revunix** [comment]
Buy your own [proxy](https://proxy6.net/en/?r=467594) (i recommend a china proxy 100% no ads), then will work TTV LOL Pro perfectly.

**Comment by pixeltris** [comment]
Potential buffering issues on proxies are already mentioned in the README.

**Comment by MrGoatsy** [comment]
> Buy your own [proxy](https://proxy6.net/en/?r=467594) (i recommend a china proxy 100% no ads), then will work TTV LOL Pro perfectly.

DO NOT CLICK THIS LINK, IT IS A REFERRAL SCAM.

**Comment by revunix** [comment]
> DO NOT CLICK THIS LINK, IT IS A REFERRAL SCAM.

@MrGoatsy Tell me, where is the scam?

**Comment by rloutrel** [comment]
I do not undersstand your initial solution and won't test it (I though it was a kind of joke from) but I think, remove r=467594 at the end of your link, which is your reference on their system and @MrGoatsy supposed it is used for sponsoring concern.

Then it would be a scam and no more a referral scam.

Not making a scam would be to list a set of similar concurrent solutions (5 is always a good number).
