### ISSUE TITLE
Prerolls on every page refresh

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/TwitchAdSolutions#188]
I'm currently getting prerolls on every page refresh. A while ago the code which would notify that ads have been watched was removed as it was no longer a requirement. The notify code is probably required again.

**Comment by DrainLife0** [comment]
+1

**Comment by pixeltris** [comment]
It looks like sending the ad watched queries still has no real impact. But you now need to download all ad `.ts` files. I'll implement something for this in `vaft` / `video-swap-new` when I get a chance.

**Comment by DaveKap** [comment]
Just started getting ads again today. Looking forward to your solution. Thanks as always for the hard work!

**Comment by pixeltris** [comment]
Fixed. It requests the ad .ts files a bit faster than it probably should (1 per m3u8 request which is about 1 per second) but it should be fine.

> Just started getting ads again today

This issue was for "Blocking ads" banner on every page refresh. If you actually see ads then there's an issue with the script being applied (I've seen this a few times when testing the uBlock Origin script... no idea why it happens).

**Comment by DrainLife0** [comment]
It's not working for me; I keep getting periodic ads on Twitch and every time I switch streams.

**Comment by pixeltris** [comment]
You have to wait for the full duration of the "Blocking ads" banner for them to accept that an ad has been watched. Once they have accepted it you shouldn't see the ad banner as you browse through streams for a period of as little as 5 minutes or up to several days / weeks.

If you actually see ads instead of the "Blocking ads" banner then there's an issue with the script being applied.

**Comment by Holteman** [comment]
Im also getting ads with correct installed script. 
Had to reinstall ubo due to YT ads as per official recommendations, somehow this broke my twitch settings and I dont know for sure what my working settings before were :(
But tried now with both vaft and videoswapnew, twitch.tv##+js(twitch-videoad) in filters, still lets initial ads through.

**Comment by RedSnt** [comment]
For some reason the new VAFT UBO permalink didn't seem to trigger consistently, I didn't get the "Blocking ads" banner or anything just now, but the userscript version seemingly trigger correctly, so that's nice. I appreciate that there are different versions 🤗
