### ISSUE TITLE
Shows stream as being "Offline" while they are actually online.

### ISSUE THREAD

**Issue by Yannickvdv** [pixeltris/TwitchAdSolutions#19]
Steps to reproduce:
- Go to any live stream (yes, I've tested multiple)
- Notice it doesn't show the stream while being live

Example image:
![afbeelding](https://user-images.githubusercontent.com/22369014/110779069-6868bd80-8263-11eb-85fa-29e16b678bd2.png)

Fix: 
Turn off Twitch AdBlock in extensions and refresh.

I'm using the Firefox version of Twitch AdBlock
Guessing this is Twitch's newest way of preventing adblock?

**Comment by ChoosenEye** [comment]
could you try it again?
should be working now

**Comment by Yannickvdv** [comment]
It hasn't changed. Would clearing cache/cookies be necessary to try again? 

Here's my version;

![afbeelding](https://user-images.githubusercontent.com/22369014/110806318-3ca90000-8282-11eb-9dbc-6cca75fe2381.png)

**Comment by ChoosenEye** [comment]
Check your Time on your system. if it's more than 5 minutes off to Realtime the Extension won't work.

**Comment by Yannickvdv** [comment]
The time on my system is consistent with realtime. The extension also worked fine yesterday and I have not edited anything on my system/in my firefox.

**Comment by ChoosenEye** [comment]
just tested some things around, can't reproduce this error on my end currently.

**Comment by Raydor** [comment]
Today I started to get this, exactly the same as op mentioned :(

**Comment by ChoosenEye** [comment]
Try to disable IPv6 then it should work.

the Problem is most times that the Auth to my System is made by ipv4 or v6 and the Stream Request is done vice-versa with the other one.

Then you can't get a playlist from my servers back and get the Offline Screen.

**Comment by ChoosenEye** [comment]
For any further Details look here: https://github.com/ChoosenEye/Twitch-Adblock-Bugs
