### ISSUE TITLE
vaft and video-swap-new no longer working (firefox)

### ISSUE THREAD

**Issue by xunkar** [pixeltris/TwitchAdSolutions#190]
May be related to this https://github.com/pixeltris/TwitchAdSolutions/issues/187

Suddenly started having ads a couple days ago, midrolls and prerolls. I'm using uBlock Origin and FFZ. Disabling FFZ makes no difference.

**Comment by pixeltris** [comment]
Related to #185 / #181

With `video-swap-new` enabled do you see `hookWorkerFetch` logged to the console when opening a stream? If you type `window.reloadTwitchPlayer` into the console does it print `undefined`? If so the script isn't being applied.

For some reason under uBlock Origin the script can sometimes stop being injected. If you purge all caches / update it should start working again.

**Comment by xunkar** [comment]
You are correct. I had tried to disable/enable ublock but it wasn't enough. Purging the cache indeed does the trick, thank you.
