### ISSUE TITLE
Streams constantly fail to continue in the last few days

### ISSUE THREAD

**Issue by MathiasFH** [pixeltris/TwitchAdSolutions#191]
Hello,
I've noticed in the last few days that streams constantly suddenly fail to continue and require a refresh.  Often every couple of seconds. This seems clearly connected to ads trying to play. It is possible they changed something so there are hick ups. It should probably be investigated.

For info, I used the option "Applying a script (uBlock Origin)" (in Chrome) to avoid ads.

Adding the script to uBlock was the only solution that ever worked for me for more than a few days. I've been happy with it for 1-2 months.

**Comment by pixeltris** [comment]
If you're using the `vaft` script it has issues with midroll ads #164 / #175 / #180 / #187

The `vaft` script is aggressive in trying to display a clean full resolution stream ASAP. This messes with the stream sequencing and it breaks in various ways.

> It should probably be investigated

I don't have any plans of improving that script. The recommended script is `video-swap-new`.

I'm going to close this as there are 3+ open issues of varying degrees of the same problem.

**Comment by MathiasFH** [comment]
The issue apeared to have disappeared for me after a restart and maybe some cleanups...
