### ISSUE TITLE
With vaft twitch stop collecting points

### ISSUE THREAD

**Issue by SzymenL0K0** [pixeltris/TwitchAdSolutions#194]
as Titele. after yesterday changes it still block ads but stop collecting points and drops. When i disable ublock i can collect it normally. (ublock 1.52.2 and firefox 118.0.2)

**Comment by pixeltris** [comment]
Does it work if you have ublock enabled but the script disabled? Someone had a similar problem in the past #95

**Comment by SzymenL0K0** [comment]
I have javascripts and other enabled.
I have betterttv too i forgot to mentioned it in first post. no other addons who works with twitch.

I try to link old vaft and its still do not work. When i set      userResourcesLocation unset it start to work normally

**Comment by SzymenL0K0** [comment]
To be clear what i mean. I do not change anything here :D 
![obraz](https://github.com/pixeltris/TwitchAdSolutions/assets/35821006/5e7c5d4d-bec5-457b-88d5-63ad9f61e633)

**Comment by SzymenL0K0** [comment]
> Does it work if you have ublock enabled but the script disabled? Someone had a similar problem in the past #95

When i disable javascripts the whole twitch don't wont to load. It stuck at this 
![obraz](https://github.com/pixeltris/TwitchAdSolutions/assets/35821006/ac9f8bb5-8260-4be6-92f4-544998bfe538)

**Comment by SzymenL0K0** [comment]
idk what happends. I try many things and they dont work but now it starts working. I will comment if something will change
