### ISSUE TITLE
Stream stuck in bad quality during ad blocking with ublock perma link

### ISSUE THREAD

**Issue by reyhanAmrc** [pixeltris/TwitchAdSolutions#195]
Hello,

When i use the filter in ublock the stream is stuck at super low resolution when the blocking ad sign is appearing but after that it goes to 1080p, do you have any idea why it's happening please ?

I'm on chrome last version.

**Comment by pixeltris** [comment]
That's how it works. I should probably update the README at some point as it currently states there's no stream playback during ads which is no longer the case.
