### ISSUE TITLE
[Doc] Eventually update the documentation to reflect the state of a userscript

### ISSUE THREAD

**Issue by Harest** [pixeltris/TwitchAdSolutions#197]
Hello,

Just a little message regarding the documentation (`full-list.md`) stating userscripts being not up-to-date and probably not working anymore:

> Web browser scripts (uBlock Origin / userscript)
These haven't been updated in a while and probably don't work.

[My script](https://greasyfork.org/en/scripts/371186-twitch-mute-ads-and-optionally-hide-them) has been working since the beginning, even during the long period where i didn't updated it _(as i didn't have ads for a while so my script didn't trigger, except in new private tabs i used to check if it was still working)_. Since it's not a script blocking completely the ads _(just muting, and hiding if wanted)_, it wasn't targeted and they didn't change the way i have been hooking my ads detection.  

_On a side note, i updated it recently as i started to have ads again and saw they added more often the smaller video player top right, so i decided to add a little function to activate the sound of it during an ad. I wanted to add a function to manage PiP to stop one if the user wants to hide the ads but sadly Firefox doesn't support it yet, it'll in December, so i'll see at that time to add this improvement._

**Comment by pixeltris** [comment]
Sorry about that. Its been a while since I looked through the solutions / checked the state of things. I'll update that when I get the chance.

**Comment by Harest** [comment]
It's still working on my side and nobody reported me any issue (but we all know most don't bother doing so).  
If you've time, feel free to tell me what you eventually had in your console log as error, or what behavior it had to make it not working (and the browser used, i'm only testing under Firefox, and tested a bit with Edge for the PiP part).

**Comment by pixeltris** [comment]
Ah it did actually work. I didn't realize it polls at 500ms. I must have seen the ad / heard the audio and instantly closed the tab.

There was a PR here a while ago which used a MutationObserver instead of polling which might be an idea for quickly muting/hiding the ads without having to poll faster #16

**Comment by syndenbock** [comment]
I highly recommend using MutationObservers, they are much more performant as they don't rely on polling and you can "listen" to very specific changes inside the DOM tree,
