### ISSUE TITLE
Intrusive "Twitch advertising survey" banner appears after about 30 minutes of runtime

### ISSUE THREAD

**Issue by TheOpponent** [pixeltris/TwitchAdSolutions#198]
![0012500](https://github.com/pixeltris/TwitchAdSolutions/assets/8432212/560cc83b-e65a-40d4-b6bd-0f3351267e82)

On many channels, the banner above appears by shrinking the entire picture to slide in on the bottom and staying on screen for over a minute. I am using the `vaft` uBlock script permalink and a personal proxy in an ad-free country. It can be dismissed and its element hidden with a uBlock cosmetic rule, but it's extremely disruptive to the viewing experience, like a border promotion on television, and reappears when watching a different channel. Is it possible for the solutions in this repository to prevent this from occurring?

**Comment by pixeltris** [comment]
The scripts here focus on the SSAI. I imagine a better cosmetic rule could fix the banner offsetting things. I'm not able to help with that though unfortunately.
