### ISSUE TITLE
Rename userscript

### ISSUE THREAD

**Issue by danbopes** [pixeltris/TwitchAdSolutions#2]
If you rename your userscript to ...`.user.js`, it would facilitate much easier install, as tampermonkey/greasemonkey see those, and will attempt to auto install the userscript.

**Comment by pixeltris** [comment]
Oops yea that would make sense. https://github.com/pixeltris/TwitchAdSolutions/commit/23b2ebbd460f91a3e55cd1f23af09e68d71c8870 should resolve this.
