### ISSUE TITLE
notify-strip stopped working

### ISSUE THREAD

**Issue by Rage-X** [pixeltris/TwitchAdSolutions#20]
Just received a full ad (not purple screen) with notify-strip (dyn-skip-midroll-alt). Refreshed/reloaded but still getting ads on all streams. Have been using it for months with no issue.

**Comment by pixeltris** [comment]
`notify-strip` still seems to be working for me atm. Twitch tends to roll things out with A/B testing so I'll take a look when I can.

**Comment by TheHungryGeek** [comment]
It doesn't work in my office where there is a static IP, but it appears to work at home where there's a dynamic IP. Wonder if that has anything to do with it. Switched to the Chrome extension instead in the meantime.

**Comment by pixeltris** [comment]
Well A/B testing isn't always location based, so minor changes in IP can result in differences. I'd assume this will be rolled out to more people soon.

**Comment by participationaward** [comment]
notify-reload didn't reload for me for the first time today, just had the ad paused but if I hit play it would actually play the ad @pixeltris

**Comment by pixeltris** [comment]
`notify-reload` should reload as soon as it detects an ad, so I guess something somewhere is broken by an upcoming change to Twitch. I will look into this when I'm able to reproduce locally.

**Comment by TsukiZero** [comment]
Having some issue with Notify-Strip as well. It doesn't play ads, but delays the stream by 5 to 10 seconds with the "waiting for ads to finish" on the corner.

**Comment by pixeltris** [comment]
I've also noticed an abnormal amount of ads being served, but they seem to be genuine (Twitch aggressively serving ads, regardless of extensions).

There are probably some issues with the m3u8 recreation which causes issues with delay. It's probably not ideal but pausing the stream for a second or so should bring the stream back to the correct place.

**Comment by TsukiZero** [comment]
Pausing the stream for a second sometimes makes things worse by means of V/A Desync. Yet another "marvel" of Twitch's developments.

**Comment by Rage-X** [comment]
As a final update I think the issue I reported has nothing to do with pixeltris's script, but a bug in the ublock dev build extension that I was using, which basically stopped working at the time after an update for some random reason. I switched back to the stable build and everything works fine.
