### ISSUE TITLE
video-swap-new (userscript) question

### ISSUE THREAD

**Issue by MonfGeiger** [pixeltris/TwitchAdSolutions#202]
my dad uses twitch, watches some streamers, collects points/bubbles/whatever the ^%#@ they (streamer in question) chooses to label them, etc...
if i get him this userscript or any other method on the list of solutions here, and/or if he has the following below ublock origin static filter list, will it negatively interfere with his point collection, or not?
[blarfeer.txt](https://github.com/pixeltris/TwitchAdSolutions/files/13373854/blarfeer.txt)

**Comment by pixeltris** [comment]
It shouldn't impact channel points but I honestly don't know much about them. People have reported channel points not working at times then working again later without any changes made.
