### ISSUE TITLE
Ads aren't getting blocked anymore

### ISSUE THREAD

**Issue by roymz** [pixeltris/TwitchAdSolutions#203]
I pasted the link twitch.tv##+js(twitch-videoad) in my filters and the permaURL vaft permalink in the userResourcesLocation. But twitch ads aren't blocked. 

I also conifugred the ublock origin youtube fix could this be interfering?

**Comment by zchilds** [comment]
Same

**Comment by gwarser** [comment]
"ublock origin youtube fix" is to have default configuration and all filter lists updated - what you did on your side?

**Comment by pixeltris** [comment]
If you type `window.reloadTwitchPlayer` and it prints `undefined` it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200

**Comment by MarrcosabTTS** [comment]
I'm getting ads on twitch

**Comment by HIMOFTHEHIMS** [comment]
Not working today 1/17/24

**Comment by bigluobo** [comment]
> If you type `window.reloadTwitchPlayer` and it prints `undefined` it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200

Where do you type that? I don't see a console comand area, also how do you purge the caches with the purge button removed???

**Comment by pixeltris** [comment]
Closing in favor of #220
