### ISSUE TITLE
Stream stays paused infinitely. 

### ISSUE THREAD

**Issue by Gamerboi520** [pixeltris/TwitchAdSolutions#204]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/aa89c849-2443-43c6-bcda-a3512cae398c)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/ecf3d5cc-d82e-4a0e-bc5a-454fccf18bb2)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/a37d4487-fedc-41ce-83cd-930999d3e035)

**Comment by Gamerboi520** [comment]
Dont ask why i have 2 youtube adblocker links lol

**Comment by Gamerboi520** [comment]
Using the other ublock perma link (not vaft) 

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/de7bede4-3b58-4a2b-bafa-534158a3cb2c)

**Comment by Gamerboi520** [comment]
Disabling this extension fixes it? after looking through the other issues its reported that this extension was causing the issue

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/deb9b306-5562-4bf9-a971-12cb1f6b49d4)

**Comment by dtrazzi** [comment]
Disabling FFZ did not fix it for me, the problem is still around. I have this happen after the stream plays for a couple minutes, then it pauses and does not resume. Reloading the page or pausing and playing the stream lets it work for another couple minutes, but it keeps happening.

**Comment by pixeltris** [comment]
I currently can't reproduce this. I tested with: 
- Firefox
- uBlock Origin + `video-swap-new` permalink
- FrankerFaceZ

I tested loading a stream with prerolls and without prerolls. Neither paused for me. I didn't test midrolls.

I'll keep an eye out though.

**Comment by zchilds** [comment]
@pixeltris I tested it recently with both Chrome and Firefox. Using TamperMoney with video-swap-new and vaft. Seemed to be broken on each. (Pausing forever)
Will test now with your setup and see if I get different results.

**Comment by EwolBash** [comment]
Using the above setup, and disabling the 7TV addon in FFZ stopped the freezing for me. Been testing for about 8 hours now, and had no reoccurrence, but it could be a coincidence. I only mention in case there is some relation.

**Comment by pflanzenandi** [comment]
video-swap-new and vaft are both working for me (violentmonkey, firefox). but I prefer vaft because it doesn't reduce video quality to 480p.

**Comment by Gamerboi520** [comment]
Its broken again

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/b7a62268-0ccc-4eae-8d84-474409687d0a)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/0e6d5090-1ce7-47ba-9264-32b95c798ad5)

**Comment by Gamerboi520** [comment]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/f97df24b-ac76-4111-a880-639e20072004)

**Comment by pixeltris** [comment]
Consolidating all freezing issues for `vaft` into #164
