### ISSUE TITLE
The ad block is no longer compatible with FFZ or 7TV

### ISSUE THREAD

**Issue by KyleB1122** [pixeltris/TwitchAdSolutions#205]
I have tried both video-swap-new and vaft and both will now randomly pause streams infinitely if you have FFZ or 7TV active as an extension. Please fix this! Thank you!

**Comment by Gamerboi520** [comment]
^ Yeah lot of people been reporting this i disabled FFZ it started working for a bit then started pausing again until i disabled 7TV

**Comment by pixeltris** [comment]
Same as #204
