### ISSUE TITLE
Video switching during adblocking

### ISSUE THREAD

**Issue by umutbalkan** [pixeltris/TwitchAdSolutions#206]
While blocking ads the stream player that I watch switch to some other stream that I am not following.
Stream that I watch: ![Screenshot 2023-11-20 230624](https://github.com/pixeltris/TwitchAdSolutions/assets/8284138/12c402d1-3f73-4649-8756-b2079022aa84)

Somehow and somewhat changed to this content
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/8284138/3ab29a18-672e-4e32-8b46-452ca03bf61f)

After blocking ads prompt reversed to normal:
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/8284138/9e18c7b7-c8ad-4681-b397-f0a90cb388e4)

I am not sure how this happens

**Comment by pixeltris** [comment]
There isn't anything in the scripts which could cause an actual page change as in your second picture. For the `video-swap-new` script there is code which triggers a player refresh when swapping the active m3u8 but I can't see anything which would cause it to pick up a different stream.

Do you have any other extensions which might be causing it?

**Comment by pixeltris** [comment]
Is this something you're able to consistently reproduce? The only thing I can think of might be this:

https://github.com/pixeltris/TwitchAdSolutions/blob/3eb915d774d9cb72acb52bd87ab3675a21d0b803/video-swap-new/video-swap-new.user.js#L226-L238

It might potentially be wiping over the `channelName` var when quickly clicking between channels but I'm not 100% sure of the scoping in this case. If it is the issue then `let` might fix it.

**Comment by umutbalkan** [comment]
I cannot reproduce it, I did nothing other than watching a stream. I am too ignorant about the tech behind this to make any reasoning, but I cannot justify how two unique channel names somewhat collide also happen to be live at the same time.
