### ISSUE TITLE
Twitch Adblock extension gone

### ISSUE THREAD

**Issue by trillex** [pixeltris/TwitchAdSolutions#21]
Twitch Adblock extension now gives you a constant "stream is offline" on any page, until you disable it. 

Their [github](https://github.com/ChoosenEye/Twitch-Adblock-Bugs), also disappeared suddenly and the extension have been pulled from both Chrome and Firefox. 

Scrubbed completely clean from the internet, which makes you think.

**Comment by ImpalaPUA** [comment]
His github still exists https://github.com/ChoosenEye/

But yea, either twitch threatened him, or they threatened github,chrome,firefox

**Comment by tonijarjour** [comment]
This is available, I dont know if its legit tho
https://chrome.google.com/webstore/detail/twitch-adblock/pjekmaedgllmfafmcnjncpkjoodholia/related

**Comment by pixeltris** [comment]
Weird... though this isn't the first time they've gone MIA. It could be that their method got patched, threats as @ImpalaPUA mentioned, or financing issues.

**Comment by pixeltris** [comment]
Closing in favor of https://github.com/pixeltris/TwitchAdSolutions/issues/22
