### ISSUE TITLE
Banner Ads Injected Into Video Stream

### ISSUE THREAD

**Issue by ls612** [pixeltris/TwitchAdSolutions#210]
Twitch has added a new ad type where it will shrink the player and show a banner ad next to the video. I'm not sure if this is at all possible to block in the same way that normal video ads are blocked. I am using the vaft script as a userscript in Tampermonkey in Firefox.

**Comment by Aspharon** [comment]
Here's a screengrab. The banner disappeared after roughly a minute, I'd say? It shrinks the feed to fit it into the space of the player without moving anything else on the page. 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/46530883/dea3623e-fdf4-47b0-b267-aa2d413b9a8a)

**Comment by TsukiZero** [comment]
There's one that pads the stream to the side too

**Comment by igloojoe** [comment]
You can block the ad element with Ublock Origin. You wont see the ad, but the player will still resize the video. Haven't found a way to prevent the resize yet.

**Comment by younesaassila** [comment]
These are served from the `edge.ads.twitch.tv` domain, which surprisingly isn't already blocked by uBlock. Until it gets added, you can just add the domain to the uBlock filter list to block it

**Comment by ls612** [comment]
Fixed by the uBO devs [https://www.reddit.com/r/uBlockOrigin/comments/18ikl6c/comment/kdejegm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](here).
