### ISSUE TITLE
Getting Ads using pixeltris

### ISSUE THREAD

**Issue by Gamerboi520** [pixeltris/TwitchAdSolutions#216]
https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/a285eeda5046a304c5eb38b958c875afca066daa/vaft/vaft-ublock-origin.js 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/253c23f5-881c-42b1-9f2d-ef8dd2ca23f3)

**Comment by Gamerboi520** [comment]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/bed8bf45-0cd2-4b79-8110-299ae622b5ef)

**Comment by xsmashx88x** [comment]
> https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/a285eeda5046a304c5eb38b958c875afca066daa/vaft/vaft-ublock-origin.js ![image](https://private-user-images.githubusercontent.com/84089845/294578646-253c23f5-881c-42b1-9f2d-ef8dd2ca23f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDgxNDksIm5iZiI6MTcwNDgwNzg0OSwicGF0aCI6Ii84NDA4OTg0NS8yOTQ1Nzg2NDYtMjUzYzIzZjUtODgxYy00MmIxLTlmMmQtZWY4ZGQyY2EyM2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzNkYTg2NzMxZjUyY2E4OWFkZjExNzZiY2NjNTY2MmVmMDUxODZlMDg3NjBmMjE5YmM5YjUyNDBkMDRlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dGVSVF5dtDGtknT5aMlJ-1anIVt9nP7bhYIk9XSAhnE)

same

**Comment by RealWu29** [comment]
use this one :
https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js

Le mar. 9 janv. 2024 à 08:45, xsmashx88x ***@***.***> a
écrit :

**Comment by RealWu29** [comment]
Dont forget this step : 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/137716219/ef02f1a9-4316-43c5-ac3d-64818e6d814c)

**Comment by Gamerboi520** [comment]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/026491e2-0304-4350-86bc-3b8f1b5c526e)

**Comment by MarioLiebisch** [comment]
It worked for months for me, but just a few moments ago got the first new ad, so I suspect they changed something.

**Comment by toned84** [comment]
same here.  I see the 'preview' window of the stream in the corner but it's not working after working very well for several months.

**Comment by pixeltris** [comment]
Have you looked at #200 or #203?

> If you type window.reloadTwitchPlayer and it prints undefined it means the script isn't loaded. Try purge caches / update. If that works then this is the same as https://github.com/pixeltris/TwitchAdSolutions/issues/200

**Comment by MarioLiebisch** [comment]
Nope, it stays `undefined` for me, no matter what I try to do (including keeping cache disabled on the Network tab of Dev Tools). However, it also seems to be working again (nothing since the ad I've mentioned above) and I also get the "Twitch adblocker is enabled" message printing to console.

**Comment by toned84** [comment]
> Have you looked at #200 or #203?
> 
> > If you type window.reloadTwitchPlayer and it prints undefined it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200

Ok, I've tried adding the script in Edge (typically I use Chrome) it worked!

But I can't figure out how to "reset" the script in Chrome.  I've tried removing the filters from uBlock and re-adding them as well as clearing twitch cache and re-logging in.... but still isn't working.

**Comment by HCL212** [comment]
> Have you looked at #200 or #203?
> 
> > If you type window.reloadTwitchPlayer and it prints undefined it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200

where are you supposed to type this? in the url? im on firefox if that matters

**Comment by Cars0419** [comment]
> > Have you looked at #200 or #203?
> > > If you type window.reloadTwitchPlayer and it prints undefined it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200
> 
> where are you supposed to type this? in the url? im on firefox if that matters
> 
> edit: nvm looks like its in the dev tools command line, but mine still shows undefined
> 
> edit2: i reset ublock origin to default settings and re-added the twitch filter and the script permalink, good for now, will update again if this doesnt work

Did this on Firefox but it still did not work... still printing undefined.

**Comment by HCL212** [comment]
> > > Have you looked at #200 or #203?
> > > > If you type window.reloadTwitchPlayer and it prints undefined it means the script isn't loaded. Try purge caches / update. If that works then this is the same as #200
> > 
> > 
> > where are you supposed to type this? in the url? im on firefox if that matters
> > edit: nvm looks like its in the dev tools command line, but mine still shows undefined
> > edit2: i reset ublock origin to default settings and re-added the twitch filter and the script permalink, good for now, will update again if this doesnt work
> 
> Did this on Firefox but it still did not work... still printing undefined.

mine still prints 'undefined' as well, but i am not getting ads anymore for now

**Comment by Lord-hayati** [comment]
I often get the pre-roll ads, but not the midrolls. is that normal?
window.reloadTwitchPlayer gives me undefined. wonder if its because of the noscript I have.

**Comment by Ghubbere** [comment]
Seems like they changed something over night, stream not loading with it enabled.

**Comment by pixeltris** [comment]
Closing in favor of #220
