### ISSUE TITLE
Vaft stopped working

### ISSUE THREAD

**Issue by J-91** [pixeltris/TwitchAdSolutions#221]
After a few months of flawlessly blocking ads it stopped working today. Anybody know who wrote the script?

**Comment by pixeltris** [comment]
If you're using the uBlock Origin script disable it and use the userscript version. See #200 / #203

**Comment by Makifun** [comment]
I also got ads a few times and the stream got stuck after a while this morning. Script was loaded as window.reloadTwitchPlayer was working. I simply cleared my cache for twitch.tv and restarted Firefox and it started working again. Fingers crossed. Using the userscript version btw.

**Comment by pixeltris** [comment]
I can reproduce this. Closing in favor of #220 as this isn't specific to vaft.
