### ISSUE TITLE
TTV LOL PRO proxy requires a username and password all of a sudden

### ISSUE THREAD

**Issue by Azingus** [pixeltris/TwitchAdSolutions#224]
The default proxy for TTV LOL PRO does not work anymore as of today. Every time I open up Twitch, I get a pop-up that tells me to give a username and password for the proxy. I already reset settings to default, but the issue persists. ADs are not being blocked anymore whatsoever.

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/43013401/fbc14c91-4ba4-4b1e-92a2-825f6493e4e7)

**Comment by younesaassila** [comment]
Yes please open issues about TTV LOL PRO on its GitHub repo. We're aware of the issue. Clicking "Sign in" without filling out the popup should work.

**Comment by Azingus** [comment]
Seems resolved now; no more pop-ups and Ads are being blocked again. 

And noted, will post on there should I run into an issue again.
