### ISSUE TITLE
Difference between vaft / video-swap-new

### ISSUE THREAD

**Issue by ComfortableMilk4454** [pixeltris/TwitchAdSolutions#227]
why does it say vaft is "The same as video-swap-new but attempts to get a clean stream faster (may suffer from more freezing / playback issues)." when for me the res of the stream during ads with vaft is far superior to that of video-swap-new's?

**Comment by zGato** [comment]
When an ad plays and resolution drops, both have the same quality.

video-swap-new
![Screenshot_174](https://github.com/pixeltris/TwitchAdSolutions/assets/88756568/22f928de-de41-4a9d-9b38-12b55a1a6cbe)

vaft
![Screenshot_175](https://github.com/pixeltris/TwitchAdSolutions/assets/88756568/830b7713-328e-47b4-9154-c68076692971)

both 360p.

**Comment by pixeltris** [comment]
When `vaft` detects an ad it constantly requests multiple different versions of the stream and uses the first clean version it finds. Sometimes this can give a high quality stream faster but it can break sequencing which introduces playback issues.

When `video-swap-new` detects an ad it forces the player to reload and switches out the m3u8 with low quality version and uses this until the ad finishes. This should be less susceptible to playback issues but there are still reports of issues.
