### ISSUE TITLE
Ads doenst block anymore

### ISSUE THREAD

**Issue by HeisenX** [pixeltris/TwitchAdSolutions#229]
Hello, for a few days I've noticed that ads have returned to normal without the ad blocker working. I'm not an expert, but I'll leave my settings here to see if anyone can help 

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/136167872/a9270e7b-930b-495f-99df-2696a501c850)

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/136167872/ab7b17fd-8e17-49eb-a39d-b2db7fde07d9)

**Comment by pixeltris** [comment]
There's already an open issue #225

As mentioned in the readme the userscript version is recommended.

**Comment by HeisenX** [comment]
> There's already an open issue #225
> 
> As mentioned in the readme the userscript version is recommended.

Hello, i've used it all and still get ads.

**Comment by HeisenX** [comment]
> There's already an open issue #225
> 
> As mentioned in the readme the userscript version is recommended.

Where do I put the perma link on ublock? Should I copy the text directly onto the filter? Thanks
