### ISSUE TITLE
low resolution when ads come out

### ISSUE THREAD

**Issue by 0x0110100001** [pixeltris/TwitchAdSolutions#231]
The broadcast resolution deteriorates during ad blocking stage. I'm using Brave browser.

**Comment by pixeltris** [comment]
I'm not sure which method you're using as you didn't say but both `video-swap-new` and `vaft` use a low resolution stream during ads. This is mentioned in the README. Try `TTV LOL PRO` for full quality throughout https://github.com/younesaassila/ttv-lol-pro
