### ISSUE TITLE
sanitization for video-swap-new-ublock-origin.js & vaft-ublock-origin.js

### ISSUE THREAD

**Issue by ryanbr** [pixeltris/TwitchAdSolutions#232]
Wanting to merge the uBO scripts into Brave. https://github.com/brave/adblock-resources/pull/160

Some sanitization issues on the script, is something can be addressed upstream? Or safe to ignore?

**Comment by pixeltris** [comment]
It doesn't look like anything too crazy to me. If you want to fix them up PRs are welcome but I'm unlikely to do that myself.

FYI I don't know how Brave's script injection works but there's some issue with the scripts randomly not getting injected with `userResourcesLocation`. Might be worth looking at #200
