### ISSUE TITLE
Video stays at lower resolution even after blocked ads finish.

### ISSUE THREAD

**Issue by XangelMusic** [pixeltris/TwitchAdSolutions#233]
So this solution would block ads as intended but also reduce the resolution of the video. After the ads are finished, the resolution would return to 1080p that I've set on the stream.

Lately however, even though the ads are blocked and finished, the video stays at lower resolution and even changing the quality setting wouldn't fix it to a higher quality. The workaround is to disable then refresh and re-enable then refresh the uBlock Origin.

Is there a fix of sorts for the quality to return to higher resolution without the workaround?

EDIT: I forgot to mention but I was using video-swap-new uBlock (Permalink) script.

**Comment by robotrono** [comment]
Same error using video-swap-new uBlock script.

**Comment by XangelMusic** [comment]
Bit of an update but I'm using the vaft ublock (permalink) script now and it works as intended.

**Comment by cavine** [comment]
Just wanted to add that I was having the same issue with the video-swap-new uBlock (Permalink) script, but swapping to the vaft one fixed it for me as well. Thanks for the fix

**Comment by pixeltris** [comment]
I'm pretty sure you're running an outdated version of the script as this behavior was noted in https://github.com/pixeltris/TwitchAdSolutions/issues/220#issuecomment-1960319000 and fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/9bd481a833341911ac39412dc4abcc41f911af8f
