### ISSUE TITLE
script stopped working

### ISSUE THREAD

**Issue by Skuyt2** [pixeltris/TwitchAdSolutions#239]
The vaft script for tampermonkey stopped working, I already reinstalled it but without success I believe an update came on Twitch and ended up taking down the script, please update.

**Comment by Dark-Dragon** [comment]
From what it seems some channels have transitioned over to different means of ad-delivery. I'm still blocking ads fine on a lot of channels, just not all. Using video-swap-new (ublock).

**Comment by Skuyt2** [comment]
I've already tried using swap in ublock origin too, but the AD is still appearing, I think it's a deal and waiting to update the script

**Comment by stevenya97** [comment]
Some more details in #236 . Pixeltris has already replied with an update, he is looking into an issue with the workers hooking functionality which is causing the script to not work atm. Seems to be a Twitch server side change

**Comment by pixeltris** [comment]
Duplicate of #236
