### ISSUE TITLE
the chrome extension doesn't work anymore on twitch

### ISSUE THREAD

**Issue by N0rvel** [pixeltris/TwitchAdSolutions#240]
twitch seems to have changed something, because the extension no longer blocks ads

**Comment by pixeltris** [comment]
If you're talking about https://github.com/cleanlock/VideoAdBlockForTwitch that isn't something I maintain. It's already in the extra list as unmaintained https://github.com/pixeltris/TwitchAdSolutions/blob/master/full-list.md#web-browser-extensions-unmaintained

**Comment by N0rvel** [comment]
oh yes, my bad !
