### ISSUE TITLE
Seems like it just stopped working again

### ISSUE THREAD

**Issue by HudeyfaA** [pixeltris/TwitchAdSolutions#241]
Worked fine after the update but seems to not be able to bybass it any longer and just immediacy plays the ad, im using Tampermonkey to run it

**Comment by ajbjc** [comment]
Having issues with it on uBlock Origin as well, it just has a "Commercial break in progress" screen, using the filters:
tv##+js(twitch-videoad)
twitch.tv##+js(twitch-videoad)

And under userResourcesLocation, I use:
https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/044d1fb3bb88a19ab718603069354d43eeba7015/vaft/vaft-ublock-origin.js

I never had issues before, but it seems to have started recently.

**Comment by 1Holy-Z** [comment]
the last week or so for me I get ads during the first half of the day and they are blocked in the afternoon/night....

**Comment by stevenya97** [comment]
I suggest trying out the userscript version of vaft. There have been issues with the ublock version before and userscript has been recommended which is what I currently use. Helps separate if it's a vaft script issue or a ublock issue. Haven't had that particular screen appear recently. Try that out(remember to revert all ublock vaft changes like userResroucesLocation and remove "twitch.tv##+js(twitch-videoad)" from filters) and report back.

**Comment by unknownids** [comment]
> I suggest trying out the userscript version of vaft. There have been issues with the ublock version before and userscript has been recommended which is what I currently use. Helps separate if it's a vaft script issue or a ublock issue. Haven't had that particular screen appear recently. Try that out(remember to revert all ublock vaft changes like userResroucesLocation and remove "twitch.tv##+js(twitch-videoad)" from filters) and report back.

I use the userscript in tampermonkey and I just got ads.

**Comment by vjt4** [comment]
> ser

same issue here.

**Comment by ajbjc** [comment]
Running through violentmonkey, it will be a black screen with a loading icon for a while, and then one of three things will happen:

1. Play the stream
2. Play an ad
3. Show the "commercial break in progress" screen

Might switch back to the other script for now

**Comment by bntaylor929** [comment]
Yesterday I disabled everything related to the vaft uBlock filter and moved over to using vaft via Tampermonkey on Chrome (userResourcesLocation unset and twitch.tv##+js(twitch-videoad) removed from filters) yet I'm still seeing mid-roll ads. No pre-rolls at least, and if I use the "Reset Player" button during an ad it goes away until another mid-roll triggers 15-30 minutes later.

My biggest issue now, and I'm pretty sure this would require significant development effort to address, is that the stream is constantly being resized to squeeze in banner ads on the right and bottom of the video frame. The ad itself is blocked in this screenshot, but the resize is very distracting:
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/45475057/ea03711b-4dc8-4d74-abf1-acd4bb2c5fb6)

I would disable uBlock (well, AdNauseum) entirely if not for this new type of ad, but as it stands I use the standard filter lists that come with uBlock by default as well as these Twitch-specific filter rules so I don't have to see the banners and other junk that Twitch plasters all over the place these days:
```
www.twitch.tv##.tw-interactable.etibmD.ineRox.ScInteractableDefault-sc-ofisyf-1.ScInteractableBase-sc-ofisyf-0
www.twitch.tv##.gbzNXq.Layout-sc-1xcs6mc-0
www.twitch.tv###directory-banner
www.twitch.tv###directory-rectangle
www.twitch.tv##div.side-nav-section.dcyYPL.Layout-sc-1xcs6mc-0:nth-of-type(3)
www.twitch.tv#@#.tw-svg
www.twitch.tv###twilight-sticky-footer-root
www.twitch.tv##.cegTsp.bTXTVH.ScCoreButtonSecondary-sc-ocjdkq-2.ScCoreButton-sc-ocjdkq-0
```

**Comment by GhostKing1337** [comment]
I tried all the filters here and the ads are still not being blocked. In fact no adblockers I have tried are working on Twitch anymore. They must have been slowly updating Twitch against the ad blockers over the last couple of weeks

**Comment by FlaminSarge** [comment]
On my end, Tampermonkey isn't even recognizing that it should load the script on Twitch pages (shows that no scripts are enabled). Did Twitch change URLs such that the script's "load on these pages" filter isn't met anymore?

**Comment by zGato** [comment]
> I tried all the filters here and the ads are still not being blocked. In fact no adblockers I have tried are working on Twitch anymore. They must have been slowly updating Twitch against the ad blockers over the last couple of weeks

TTV LOL PRO :O

**Comment by LetsPlayNintendoITA2023** [comment]
> > I tried all the filters here and the ads are still not being blocked. In fact no adblockers I have tried are working on Twitch anymore. They must have been slowly updating Twitch against the ad blockers over the last couple of weeks
> 
> TTV LOL PRO :O

yea midrolls are all gone with it

**Comment by Omarock92** [comment]
Stopped working for me today.

**Comment by Suprcheese** [comment]
Just got some ads. Using vaft uBlock.

**Comment by yassbeno** [comment]
same, today !

**Comment by pixeltris** [comment]
It's always best to be as clear as possible when saying you see ads. The important pieces of information:

1) Which script are you using
2) Are you using the userscript or uBlock Origin script. If you're using uBlock Origin version there are possible issues with applying the script so unfortunately I have to ignore any of these reports. If you're using a userscript it's also good to say what userscript manager you're using. While in theory it shouldn't matter it's useful to know so I can try the same setup.
3) Are you seeing midroll ads, preroll ads, or both. With the `video-swap-new` script it's more obvious as it says "Blocking midroll ads" when there are midrolls. `vaft` shows "Blocking ads" for both prerolls and midrolls which isn't super helpful.
4) Are you seeing actual ads or are you seeing a "commercial break" screen.
5) What web browser you're using.

Based on the original issue it sounds like they were seeing both prerolls and midrolls but comments seem to be mostly referring to midroll issues. Again being super clear is really important.

Unfortunately I don't have much time to look at Twitch streams so midrolls are hard for me to catch. I used to have a couple of streams that were on 24/7 which played ads at a consistent 8 minute interval. If anyone knows of a stream with those characteristics (on 24/7, midrolls every 8-10 minute interval without fail) that would be useful.

**Comment by viocar** [comment]
I was having preroll ads with the uBlock Origin script, but I switched to the Tampermonkey userscript and the ads stopped, so it seems like the issue may lie with uBlock Origin for now.

**Comment by therentabrain** [comment]
I'm getting some preroll ads now.  I'm using Tampermonkey.  Please let me know any info I can provide.  Is there a debug flag I can set so I can trace what the program is doing?  I would just leave that on always, I have the CPU to spare...

**Comment by therentabrain** [comment]
FWIW, my browser is now trying to contact usw23.usher.ttvnw.net.  This is new.  When I enable it, it brings up an ad or the stream.  But when I resume disabling it, it just brings up an error.

**Comment by MathiasFH** [comment]
Two weeks ago the issue appeared and then disappeared again.
Today it appeared again, but only when I click on RetroIslandGaming, who is located on Hawaii. So the issue might be region-dependent in some way or to some extent.
I'm using this uBlock script:
https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js 
And I'm getting preroll ads.
It always worked perfectly by the way, until the wider reports came in that it doesn't work (and then it worked again for two weeks). So I think one shouldn't dismiss that for it being uBlock.

**Comment by GhostKing1337** [comment]
> > I tried all the filters here and the ads are still not being blocked. In fact no adblockers I have tried are working on Twitch anymore. They must have been slowly updating Twitch against the ad blockers over the last couple of weeks
> 
> TTV LOL PRO :O

Can't use it it breaks Twitch.

**Comment by pixeltris** [comment]
Thanks for the channel link @MathiasFH. I'm able to reproduce it on that channel sometimes. They are definitely A/B testing the change.

**Comment by pixeltris** [comment]
Thanks @therentabrain for the heads up on the url info. That change is definitely breaking `vaft`. The script currently only modifies m3u8 files with urls containing the text `video-weaver`. The `video-swap-new` script modifies all m3u8 files regardless of the url so it shouldn't be impacted.

I don't know the reason for the m3u8 url check as the original author didn't leave commit messages https://github.com/ImpalaPUA/VideoAdBlockForTwitch/blame/25a0211f285e20c2458751fba3a59d4253aa7c40/content.js#L250

I think I'll just change it to what `video-swap-new` currently does and hope it doesn't break anything.

**Comment by Suprcheese** [comment]
Can confirm, I changed to video-swap-new and that solved it.

**Comment by pixeltris** [comment]
Fixed the url check in https://github.com/pixeltris/TwitchAdSolutions/commit/02447140c7522721601ac62c4fb47c7757e054d7 which should fix `vaft`.

I can't comment on the "commercial break" screen as I haven't personally seen it. Anyone still impacted by that should create a new issue for that with detailed info mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/241#issuecomment-2076744416

**Comment by therentabrain** [comment]
Thank you, glad to help.

Soapbox:
FTR, if Twitch folk are watching this thread (and I have no idea why they wouldn't be), I would be less righteous and determined if ads were less toxic.  This is an invaluable tool for a streamer.  The people I help with this stuff do quiet streams, healing streams, sleeping streams, etc.  The horror and violence based game ads have no business traumatizing their communities.  And when one is the streamer, currently streaming to dozens or hundreds of viewers, looking for something from another stream (where to raid?  are they ready for us?  or, when is an expected train coming to me?  etc) being hit with ads is a critical delay and the loud sound and bright visuals in the streamer's face intrude on the program the streamer is creating.  

As an affiliate or partner, we are the product, and we dedicate hours every day to creating and maintaining the bright warm excellencopia that keeps Twitch so magical.  To be interrupted (and often traumatized) by ads like any viewer is a constant slap in the face.  Turbo is a great idea, but to pay $144 a year to the service that is supposed to be paying us feels like another slap.
/soapbox

Thanks pixeltris :)

**Comment by zGato** [comment]
> 
> Soapbox:
> /soapbox
> 

This change, neither the last worker one, is intended to break adblock solutions, they're not targetting adblockers right now with these updates, they're just updating their backend infra and (for what it looks like) migrating away from using their own "servers" (Amazon either way) to Amazon CloudFront Video (what Kick uses basically). If they finally push this into prod completely, it will be a huge win for proxy-based solutions, we'll actually win from it.
