### ISSUE TITLE
Low quality when enabled.

### ISSUE THREAD

**Issue by rockett1** [pixeltris/TwitchAdSolutions#242]
Twitch detects adverts are being blocked and lowers the quality of the stream.

**Comment by HudeyfaA** [comment]
meant to happen, what browser do you use, and how do you implement it. it doesnt work for me at all

**Comment by rockett1** [comment]
Nevermind Im closing this, It's just when the streamer has adverts running. The stream blanks out a sec and comes on in like 480p, eventually goes back to full resolution. This is all despite having it manually set to 2160p stream quality.
