### ISSUE TITLE
No ads but something esle

### ISSUE THREAD

**Issue by Pelotedeneige** [pixeltris/TwitchAdSolutions#245]
Hello

I am having a problem those last few days. While I am watching a stream, the screen shrinks and shows black stripes all around. I assume it should be integrated ads but I am not sure. It happens sometimes every 10 minutes or so. It is very annoying.

![Twitch](https://github.com/pixeltris/TwitchAdSolutions/assets/125823221/0d2ccb59-c027-4e34-a015-4e1c25569f8b)

I am using Vaft with uBlock Origin. Is it a problem on my part ? Is it specific to my country (France) ? Is there a way to prevent this from happening ?

Thanks to everyone who can help.

**Comment by Hilosgeek** [comment]
> Ciao
> Ho un problema in questi ultimi giorni. Mentre guardo uno streaming, lo schermo si restringe e mostra strisce nere tutt'intorno. Presumo che dovrebbero essere annunci integrati ma non ne sono sicuro. Succede a volte ogni 10 minuti circa. È molto fastidioso.
> Sto usando Vaft con uBlock Origin. E' un problema da parte mia? È specifico per il mio paese (Francia)? C'è un modo per evitare che ciò accada? Grazie a tutti coloro che possono aiutare.

Hi! I don't have a solution but I had the same problem only once from Italy. I refreshed the google chrome page and it was back to normal.

**Comment by Pelotedeneige** [comment]
Thank you for your reply.

Sadly, I refreshed several times when it happened and it was still there. :(

**Comment by bntaylor929** [comment]
I don't think such ads have ever been in the scope of TwitchAdSolutions but I found a Ublock Origin filter that works for this:
`||edge.ads.twitch.tv^$xhr,domain=www.twitch.tv,important`

**Comment by Pelotedeneige** [comment]
> I don't think such ads have ever been in the scope of TwitchAdSolutions but I found a Ublock Origin filter that works for this: `||edge.ads.twitch.tv^$xhr,domain=www.twitch.tv,important`

I tried it. I thought it was working but it was just less frequent those last days. The shrinking is still here from time to time.

**Comment by bntaylor929** [comment]
Aww that's a bummer. It's worked on 100% of streams for me since setting it up but maybe they're testing different code for different groups. Here are all my Twitch filters in case I have something else doing some work:
`www.twitch.tv##.tw-interactable.etibmD.ineRox.ScInteractableDefault-sc-ofisyf-1.ScInteractableBase-sc-ofisyf-0
www.twitch.tv##.gbzNXq.Layout-sc-1xcs6mc-0
www.twitch.tv###directory-banner
www.twitch.tv###directory-rectangle
www.twitch.tv##div.side-nav-section.dcyYPL.Layout-sc-1xcs6mc-0:nth-of-type(3)
www.twitch.tv#@#.tw-svg
www.twitch.tv###twilight-sticky-footer-root
||edge.ads.twitch.tv^$xhr,domain=www.twitch.tv,important`
I'll post an update here should they come back and if/when I'm able to hide them.

**Comment by Pelotedeneige** [comment]
I'll try them to see if there is any improvement. Thank you so much for your help.

**Comment by Pelotedeneige** [comment]
> Aww that's a bummer. It's worked on 100% of streams for me since setting it up but maybe they're testing different code for different groups. Here are all my Twitch filters in case I have something else doing some work: `www.twitch.tv##.tw-interactable.etibmD.ineRox.ScInteractableDefault-sc-ofisyf-1.ScInteractableBase-sc-ofisyf-0` `www.twitch.tv##.gbzNXq.Layout-sc-1xcs6mc-0` `www.twitch.tv###directory-banner` `www.twitch.tv###directory-rectangle` `www.twitch.tv##div.side-nav-section.dcyYPL.Layout-sc-1xcs6mc-0:nth-of-type(3)` `www.twitch.tv#@#.tw-svg` `www.twitch.tv###twilight-sticky-footer-root` `||edge.ads.twitch.tv^$xhr,domain=www.twitch.tv,important` Some of these hide Twitch's own banners/bloat, and the one "#@#" rule fixes some buttons broken by one of the larger filter lists without affecting any ad blocking. I'll post an update here should the stream shrinking ads come back for me and if/when I'm able to hide them.

Nope, I added all of them and still have the issue. Maybe they are indeed testing some things. Oh well. This platform is becoming more and more tedious.

**Comment by pixeltris** [comment]
Looks like that should be handled with a filter. This repo is about solutions for Twitch's SSAI.
