### ISSUE TITLE
Twitch drops blocked

### ISSUE THREAD

**Issue by Medivha** [pixeltris/TwitchAdSolutions#248]
Twitch drops(tested on BlackDesertOnline Streams) on twitch get blocked with video-swap-new(tampermoneky - autoplay changed to embed) or AdGuard extra on Firefox. Not tested the others. Must be a change in the last 2 days, was working fine before. Also updated after to the current Firefox version to see any change but same.

Disabling video swap or adguard(not running both at the same time) extra fixes the progress of twitch drops.
Ublock origin is running at all time

Ps.: now also tested on Vaft(Tampermonkey) same problem.

Seems like twitch is detecting it and blocking twitch drops(not sure why it doesn't do it with ublock in the first place -  maybe some other problem idk)

**Comment by JeffJankowski** [comment]
Additionally, channel points are not accumulating (not sure if that's the same mechanism as Drops). 

Win 10 / Chrome 124 / Tampermonkey v2.18 / Vaft 8.0.0

**Comment by mrkorb** [comment]
Came here to say that I too have not been earning channel points or progress on watch streaks since yesterday.  I've been methodically trying to figure out which Twitch related extension or script is doing it, and video-swap-new appears to be responsible.  I have it installed as a userscript in Tampermonkey.

**Comment by VE34** [comment]
Same experience here, with video-swap-new and vaft on uBlock. Would like to add that channel points from raids are going through, just not watch streaks and the +10/+50 redeems.

**Comment by GhostKing1337** [comment]
Same problem here the Tampermonkey script causes Twitch Channel Point gain and drops to stop working.

**Comment by Johnrock191791** [comment]
I been having this problem as well. Using Ublock origin with vaft and the only way I can get points is to put my phone watching the livestream while watching the livestream on my macbook. Everything else stops gaining points like +10, +50 box redeem and watch streaks except when we're raiding

**Comment by mrkorb** [comment]
It seems that Twitch _might_ have rolled back whatever they had changed yesterday.  I am now earning channel points and watch streaks again with video-swap-new enabled.  Curious to hear from others if they are seeing the same thing, or if I somehow just got lucky on a page reload?

**Comment by VE34** [comment]
I can confirm that the watch streak and +10/+50 redeems appear to be working again, at least from my end.

**Comment by JeffJankowski** [comment]
Confirming as well. Tampermonkey+Vaft
