### ISSUE TITLE
[Question] Proxy Server

### ISSUE THREAD

**Issue by KillaBoi** [pixeltris/TwitchAdSolutions#25]
Hi there!

I'm currently working on a Proxy Server that utilizes a server located in a region where ads are not served. I'm also using an account that has Turbo enabled as a fallback (and also to test with).

I'm kind of a noob at nodejs based server development so bear with me on that whilst I ask you some questions :)

I've got the authentication working and I'm able to get designated m3u8 links in the same format as they would appear on `usher.twitch.tv` (I use the turbo enabled accounts OAuth token to request the `PlaybackAccessToken` operationName which automatically specifies `Turbo = true` and `Subscriber = true` for the streams where I am subbed, also `show_ads =  false`) which I then use when requesting the actual playlist links to a channel.

What is the best way for me to pass this onto the actual browser? Does the proxy-m3u8 ublock script/userscript currently handle the exact m38u data as it would appear from `usher.twitch.tv`?

Thanks for the help and info!

**Comment by finiteLimit** [comment]
Hey, I'm wondering which region you're using for your proxy. I am considering making a private proxy for myself, but don't know which region to purchase a VPS from.

**Comment by pixeltris** [comment]
If you wish to use the `proxy-m3u8` script I'd recommend setting `OPT_MODE_PROXY_M3U8_FULL_URL` and `OPT_MODE_PROXY_M3U8_PARTIAL_URL` to false.

You then would set `OPT_MODE_PROXY_M3U8` to your url e.g. `https://test.com/twitch/`. Requests would then be made to your server such as `https://test.com/twitch/forsen` if you were viewing `forsen`.

To that request you want to resolve and response with the main m3u8 (the one with all of the resolution links). You shouldn't have to do any additional processing on the m3u8.

Ref https://github.com/pixeltris/TwitchAdSolutions/issues/8#issuecomment-751910274

**Comment by saucettv** [comment]
If anyone with some skill is interested in creating a Node.js based server in an ad-free country and knows how to apply Javascript API methods into it (Like a cloudflare worker). I would be willing to share the code that would of been used server side and the extension code if needed. My code is cloudflare worker based, but cloudflare workers work off a similar engine and the code is fairly simple. I just don't want to have to find or pay for a server to do it. Email me at saucettv@protonmail.com if interested, I wont be asking for any money, just want this to continue. So far I heard Russia, Isreal and India don't get ads. The other problem you might have is if you get a dedicated IP. It will get flagged fairly quickly. You need to be able dynamically change this to avoid that.

**Comment by saucettv** [comment]
> 
> 
> Hi there!
> 
> I'm currently working on a Proxy Server that utilizes a server located in a region where ads are not served. I'm also using an account that has Turbo enabled as a fallback (and also to test with).
> 
> I'm kind of a noob at nodejs based server development so bear with me on that whilst I ask you some questions :)
> 
> I've got the authentication working and I'm able to get designated m3u8 links in the same format as they would appear on `usher.twitch.tv` (I use the turbo enabled accounts OAuth token to request the `PlaybackAccessToken` operationName which automatically specifies `Turbo = true` and `Subscriber = true` for the streams where I am subbed, also `show_ads = false`) which I then use when requesting the actual playlist links to a channel.
> 
> What is the best way for me to pass this onto the actual browser? Does the proxy-m3u8 ublock script/userscript currently handle the exact m38u data as it would appear from `usher.twitch.tv`?
> 
> Thanks for the help and info!

You would need to create an add-on/extension for the browser.
This would be all you need:

manifest.json file:

`{
  "description": "",
  "manifest_version": 2,
  "name": "",
  "version": "1.0",

  "permissions": [
    "webRequest",
    "webRequestBlocking",
    "https://www.twitch.tv/*",
    "https://usher.ttvnw.net/*"
  ],

  "background": {
    "scripts": ["background.js"]
  }
}`

background.js file:

`function redirectURL(requestDetails) {
  return {
    redirectUrl: "yourproxyurlhere/"+requestDetails.url.split('.m3u8')[0]
    //this will send yourproxyurlhere/usher.ttvnw.net/api/channel/hls/channelname
    //or for vods yourproxyurlhere/usher.ttvnw.net/vod/numberofvod
  };
}

chrome.webRequest.onBeforeRequest.addListener(
  redirectURL,
  {urls: ["https://usher.ttvnw.net/*"]},
  ["blocking"]
);
`

Then just zip it and become a add-on developer. You can also add icons, browser icons etc, but I just gave you what is needed to get it working. In Firrefox you can test it by going to about:debugging click on this browser and then load the zip. I would also avoid the turbo option if I was you, infact avoid anything that links to an account or device ID, randomize it.

**Comment by KillaBoi** [comment]
> Hey, I'm wondering which region you're using for your proxy. I am considering making a private proxy for myself, but don't know which region to purchase a VPS from.

Russia, have fallbacks located in India and South America as well if I ever need to use them.

And as for the other comments, they're both perfect, I'll do some testing and running once I'm a little better with my health

**Comment by saucettv** [comment]
Sounds good, if you need my server code to see if there is any differences I can send you a private gist link via email, just let me know it's you. My code has something in it that would help you I think. Would make it public but it will just give them another easier way to block it in other ways. saucettv@protonmail.com

**Comment by KillaBoi** [comment]
> Sounds good, if you need my server code to see if there is any differences I can send you a private gist link via email, just let me know it's you. My code has something in it that would help you I think. Would make it public but it will just give them another easier way to block it in other ways. [saucettv@protonmail.com](mailto:saucettv@protonmail.com)

Sure I'll email you I guess, are you running anything atm yourself?

**Comment by saucettv** [comment]
Only the 480p extension I just put out, but it's pretty lame, unless you like 480p lol.

**Comment by KillaBoi** [comment]
> Only the 480p extension I just put out, but it's pretty lame, unless you like 480p lol.

I'm also using a 480p implementation atm until I can figure out this server stuff, just sent an email to u rn

**Comment by saucettv** [comment]
Just replied with the gist link, hope it helps :)

**Comment by finiteLimit** [comment]
@pixeltris I'm curious about the method of developing a similar proxy. Would the following procedure work?

1. Obtain a server in a location that does not serve ads. 

2. Host a script that returns an `.m3u8` file, using the following line: (as well as replacing any of the necessary variables)
`var accessTokenResponse = await fetch('https://api.twitch.tv/api/channels/' + channelName + '/access_token?oauth_token=undefined&need_https=true&platform=web&player_type=' + OPT_VIDEO_SWAP_PLAYER_TYPE + '&player_backend=mediaplayer', {headers:{'client-id':CLIENT_ID}});`

3. Rewrite the `background.js` file of the previous working Twitch Adblock, and replace the previous Proxy URL with my current one.

**Comment by pixeltris** [comment]
Yes pretty much. You'll want to make sure you have the `Device-ID` header as mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/8#issuecomment-766323401

Additionally the comment above the one I linked has a the stripped down background.js without the unnecessary cookie code.

**Comment by Zibbp** [comment]
> 
> 
> @pixeltris I'm curious about the method of developing a similar proxy. Would the following procedure work?
> 
>     1. Obtain a server in a location that does not serve ads.
> 
>     2. Host a script that returns an `.m3u8` file, using the following line: (as well as replacing any of the necessary variables)
>        `var accessTokenResponse = await fetch('https://api.twitch.tv/api/channels/' + channelName + '/access_token?oauth_token=undefined&need_https=true&platform=web&player_type=' + OPT_VIDEO_SWAP_PLAYER_TYPE + '&player_backend=mediaplayer', {headers:{'client-id':CLIENT_ID}});`
> 
>     3. Rewrite the `background.js` file of the previous working Twitch Adblock, and replace the previous Proxy URL with my current one.

Have you been able to use this endpoint? I get a  410 `this API has been removed.` error.

**Comment by pixeltris** [comment]
`access_token` API endpoint was removed by Twitch. Everything goes through `gql` now, for access token that would be an `operationName` of `PlaybackAccessToken_Template` or `PlaybackAccessToken`.

**Comment by Zibbp** [comment]
I was able to get a simple server working but when trying with a host that isn't localhost such as a VPS. I receive CORS errors.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource
```
Do I need to specify an IP or CORS settings in any of the token requests?

**Comment by pixeltris** [comment]
I'm pretty sure in this case it's a badly configured server. The requests will be coming in to your server from a twitch.tv domain, so if you haven't specified that's allowed (e.g. an appropriate `Access-Control-Allow-Origin` setting such as `*` or `twitch.tv`) then the browser will complain about CORS.

**Comment by watlok** [comment]
Does anyone know where play_session_id  (playSessionId / streamid) comes from? Asking before I spend more time deep diving. It doesn't appear to be in network requests or source files in a non-obfuscated way.  I'm working on a headless client for the modern webapp and I believe this is the only thing I'm missing. Most open source projects seem to use old apis or things at risk of being deprecated/patched.

**Comment by pixeltris** [comment]
Pretty much everything goes through gql requests now (https://gql.twitch.tv/gql) which are easy enough to invoke yourself. I'm not sure what you mean by any of `play_session_id (playSessionId / streamid)`, but when viewing a stream one of the first gql requests contains a large number of operations, including:

- `UseLive` which fetches streamer name / id, and the current live broadcast id and the time it was started.
- `ChannelShell` which fetches the same info (minus broadcast time), but with the addition of viewer count.
- `UseViewCount` which fetches the viewer count.

If you can't find what you're looking for in the gql requests, then I assume it would still be an older API you're looking for.

**Comment by finiteLimit** [comment]
> 
> 
> Pretty much everything goes through gql requests now (https://gql.twitch.tv/gql) which are easy enough to invoke yourself. I'm not sure what you mean by any of `play_session_id (playSessionId / streamid)`, but when viewing a stream one of the first gql requests contains a large number of operations, including:
> 
>     * `UseLive` which fetches streamer name / id, and the current live broadcast id and the time it was started.
> 
>     * `ChannelShell` which fetches the same info (minus broadcast time), but with the addition of viewer count.
> 
>     * `UseViewCount` which fetches the viewer count.
> 
> 
> If you can't find what you're looking for in the gql requests, then I assume it would still be an older API you're looking for.

I'm just stuck on what to do in terms of a proxy server for personal use. I was going to purchase a Russian VPS, but at that point I'm spending around $10/mo, which, from my recollection, could be used to purchase an actual Twitch Turbo subscription and block ads "legally". 

I'm never going to buy that subscription, but it's just like, is it worth the effort? If it's for personal use (1 person), a single proxy server doesn't seem to be efficient, unless you really don't want to buy Twitch Turbo.

**Comment by watlok** [comment]
> Pretty much everything goes through gql requests now

This does not appear to go through gql or non-gql requests when loading a stream in a new private browsing session. Requests for m3u8 through usher have a play_session_id parameter that is not part of the jwt.  It isn't necessary to request the m3u8, but I don't want to leave it out.

**Comment by pixeltris** [comment]
Ah I see what you're referring to. I'm not sure when they introduced that, I don't remember seeing it in the past. Looks client generated to me? `p` is another parameter which has existed for years and I don't think I've seen an actual accurate generator for it.

I really wouldn't worry too much about emulating everything 1:1. Twitch changes those parameters pretty regularly without impacting things. There's also a ton of ways they can detect you as non authentic traffic if that's your concern.

**Comment by finiteLimit** [comment]
https://github.com/arthurbolsoni/Purple-adblock/

Can anyone test if this one is working? Was posted here a few days ago.

**Comment by TheEnhas** [comment]
> 
> 
> https://github.com/arthurbolsoni/Purple-adblock/
> 
> Can anyone test if this one is working? Was posted here a few days ago.

It works just fine (using Firefox here). There's no low latency mode though but I can live with that.

**Comment by arthurbolsoni** [comment]
any idea how i put low latency? i am using a russian server. maybe a on ukraine?

**Comment by pixeltris** [comment]
You need to provide the `fast_bread=true` parameter to the `usher.ttvnw.net` m3u8 request. This sets `EXT-X-TWITCH-PREFETCH` (low latency).

**Comment by arthurbolsoni** [comment]
> You need to provide the `fast_bread=true` parameter to the `usher.ttvnw.net` m3u8 request. This sets `EXT-X-TWITCH-PREFETCH` (low latency).

thanks :)

**Comment by pixeltris** [comment]
As mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/8#issuecomment-826330993 there's server code available which can be uses as-is, or be adapted based on your requirements. These cover the questions originally raised in this issue.
