### ISSUE TITLE
Twitch Ads

### ISSUE THREAD

**Issue by jthead9** [pixeltris/TwitchAdSolutions#250]
Lately I've been getting ads on twitch and I"m not sure why. But when I refresh its fine. Its just the moment they activate

**Comment by tangosox** [comment]
I'm getting ads on load and in stream right now.

**Comment by evilmaran** [comment]
same

**Comment by FabianLoRs** [comment]
Confirmed

**Comment by TenseiCho** [comment]
Can confirm I am getting ads as well with master/video-swap-new/video-swap-new-ublock-origin.js in ublock.

**Comment by stevenya97** [comment]
If you are still having issues, check out my suggestions over on #252. Cheers

**Comment by TenseiCho** [comment]
@stevenya97 appreciate it.

**Comment by jthead9** [comment]
The thing is I have everything set up properly. However if I leave a page up for too long, it won't block the ads until I refresh the page. It doesn't block ads until i manually refresh the page which is annoying to dealing with

**Comment by stevenya97** [comment]
Could mean you have multiple ad block solutions active that are conflicting with each other. Are you using uBlock or Userscript version?

**Comment by jthead9** [comment]
I'm using the ublock extension.

**Comment by jthead9** [comment]
And I don't have any other things that could block it from working

**Comment by stevenya97** [comment]
Try the userscript version. I have suggesions on #252. uBlock version is reportedly breaking(#200) randomly due to uBlock changes

**Comment by pixeltris** [comment]
Closing as I can't reproduce. userscript version is always recommended.
