### ISSUE TITLE
Video freeze

### ISSUE THREAD

**Issue by Thefreelolz** [pixeltris/TwitchAdSolutions#254]
Hi,

Starting this morning, after like 10sec into any streams, the video freezes but the audio still works odly enough.
I have been using the vaft permalink and using the newer one or other scripts have been doing the same behaviour.
Turning off UBlock for twitch has resulted in streams just staying black and indefinitely loading.

**Comment by stevenya97** [comment]
You mentioned uBlock, are you using just the uBlock version of the scripts? Ublock has a known issue rn with the vaft script where it sometimes doesn't work. You can try out the userscript versions instead which are currently more reliable. I have a couple suggestions on #252

**Comment by TsukiZero** [comment]
Happens regardless. Additionally, it sometimes freezes as soon as an adbreak starts.

**Comment by stevenya97** [comment]
Do you have multiple scripts loaded? Can happen if you have more than one script loaded i.e. both `vaft` and `video-swap-new` userscripts enabled, or both userscript and uBo script applied. Additionally disable any proxy/vpn based ad block solutions like `TTV LOL PRO`. If you are using uBo I can only suggest double checking the script url and filter have been applied. I am testing on a clean Firefox profile with Tampermonkey and only the `video-swap-new` userscript loaded and cannot replicate this. We can work through potential conflicts if it's still happening.

**Comment by TsukiZero** [comment]
It appears to depend on multiple factors (region, routing, ad type, streamer, stability streamer-server, stability server-viewer) it is hard to check...

But one thing that is a perfect constant is that latency flat out stops changing and gets stuck at an exact value when this happens, and likely buffer size might be a perfect 0 by then.

**Comment by pixeltris** [comment]
Consolidating all freezing / pausing / playback issues for `vaft` into #164
