### ISSUE TITLE
(vaft) Blocking ads often causes live streams to be stuck loading until ad is over

### ISSUE THREAD

**Issue by sham-pain** [pixeltris/TwitchAdSolutions#255]
Most of the time (maybe depending on the twitch channel?) when a mid-roll ad is being blocked, the player is stuck loading and would only continue playback when the ad is over unless manually clicking pause and play.
I took a look into the vaft script and I noticed that you have a function to pause and play after the ad is over to make sure the video is playing properly and it is "reset".

I'm not a programmer so no idea if feasible, but wouldn't it be also possible to add this:
- if there is buffering detected for let's say 2+ seconds when an ad starts playing, then have the script pause and play the video

**Comment by FurkanVG** [comment]
+1 to this. Firefox btw.

**Comment by kisiel92** [comment]
Also experiencing this in Safari

**Comment by pixeltris** [comment]
Consolidating all freezing / pausing / playback issues for `vaft` into #164
