### ISSUE TITLE
Does not work locally?

### ISSUE THREAD

**Issue by FeuFeuAngel** [pixeltris/TwitchAdSolutions#256]
Hello i download the js, renamed it to vaft js and putted the url like this in config of ublock orgin:

file:///C:/Users/CurrentUser/Documents/TwitchAd/vaft.js

cant get it to work, why?

**Comment by stevenya97** [comment]
Are you using Firefox or a Chrome based browser? Chromium supports file URI scheme if you grant the extension access. Firefox does not have this function atm afaik.

The setting under uBo extension settings in Chrome:
![setting-in-chrome](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/d0ab7499-f5b3-4ed0-973b-7b6f2eb40b6a)

**Comment by pixeltris** [comment]
Try the above advice and failing that ask at https://github.com/uBlockOrigin/uBlock-issues/issues
