### ISSUE TITLE
Not much, but I made a 480p extension for Firefox

### ISSUE THREAD

**Issue by saucettv** [pixeltris/TwitchAdSolutions#26]
Obviously the 480p option isn't great, but I made an extension for Firefox that will use the ad-free 480p version of the player. This wont be better than pixeltris's userrscript methods that try normally first, but I noticed a lot of people struggle with the userscripts, so made this quickly. So if you can stand 480p quality, this will work for you.

https://addons.mozilla.org/en-GB/firefox/addon/ad-free-but-480p-for-twitch/

Opensource and code is on Github as a gist https://gist.github.com/saucettv/06c470c4150398d4505381bfad67bf0b

Couldn't be bothered to pay the Google fee to put it on Chrome, but anyone is free to use the code and do it themselves if they have a dev account.

**Comment by gainaaa** [comment]
This permanent 480p? Or just for the duration of the ad ?

**Comment by saucettv** [comment]
Yes this will make the entire length of the stream 480p, so if you can, use the pixeltris script to get a better experience. It's more for those that don't have uBlock Tamper etc. Or don't want to use userscripts.

**Comment by pixeltris** [comment]
Awesome. Chrome would be nice, but yea not fun to pay fees! I'll add this to the list of `other solutions / projects` in the README when I get a chance.

**Comment by pixeltris** [comment]
I assume this is being superseded by `Video Ad-Block, for Twitch`, as the firefox link is gone. In case the gist is removed and someone wants this I've reupload the gist here:

[06c470c4150398d4505381bfad67bf0b-a077259b3b4e9646413b641b01f3405b1f12bf77.zip](https://github.com/pixeltris/TwitchAdSolutions/files/6372134/06c470c4150398d4505381bfad67bf0b-a077259b3b4e9646413b641b01f3405b1f12bf77.zip)
