### ISSUE TITLE
Script has Stopped Working

### ISSUE THREAD

**Issue by gzuzz187** [pixeltris/TwitchAdSolutions#260]
The script isnt working anymore(3-4 weeks). Can someone hep me?

**Comment by smjkh** [comment]
Mine just stopped working as well

**Comment by petercunha** [comment]
+1 any fixers in chat

**Comment by stevenya97** [comment]
Have you tried the suggestions over on #252 ? Mainly, try reverting uBo scripts and try out the userscript versions with TamperMonkey/ViolentMonkey. uBo is having some known issues loading the script in random cases(#200). You should be able to check the web console for `blocking ads` messages that indicate the script is running, if not appearing then likely uBo is not loading the script properly

**Comment by orangoz1** [comment]
for me what fixed it was turning on developer mode it seemed chrome automatically by default turned it off.

**Comment by pixeltris** [comment]
Closing as I can't reproduce. userscript version is always recommended.

**Comment by petercunha** [comment]
Turning off Enhanced Browsing Protection in Chrome and switching to video-swap-new fixed it for me
