### ISSUE TITLE
can you rework the twitch script to work for youtube since ublock origin is no longer working?

### ISSUE THREAD

**Issue by afroisanoreo** [pixeltris/TwitchAdSolutions#261]
its a sad day in history now that youtube implemented server side ads like twitch. 

please somehow make a script to save me from the torturous aflac and statefarm ads

**Comment by stevenya97** [comment]
Out of scope for this project, but you can wait for an official response by the repo author. 

In the meantime, you can check out the discussion over on [uBlockOrigin](https://github.com/uBlockOrigin/uAssets/issues/20586#) repo on circumventing YouTube server side ads. They have a couple of test suggestions but we are all navigating this new YT change like you, please be patient with the maintainers and don't spam that thread. Please DO make note of any filters you add as they are likely to change as we discover improved solutions. Old filters can possibly break things for you as both YT and uBlock dance back and forth. Afaik, things like timestamps do not work with the new tentative methods. SponsorBlock is also facing similar timestamp issues.

**Comment by pixeltris** [comment]
Yea this is just for Twitch ads. I imagine the main adblockers will end up handling YouTube SSAI or some new project will pop up which does.
