### ISSUE TITLE
Vaft broken in Chromium browsers

### ISSUE THREAD

**Issue by th3m** [pixeltris/TwitchAdSolutions#262]
Latest vaft permalink that fixes the "FrankerFaceZ loading issue" has broken the functionality in Chromium browsers.
Twitch streams don't load at all.

**Comment by pixeltris** [comment]
I can't reproduce. I tested Brave / Chrome. The userscript version is recommended. Ref #200

**Comment by stevenya97** [comment]
Hmm I also can't reproduce it. I tried on a fresh profile of Chrome with just uBo, FrankerFaceZ extensions and the vaft script loaded into uBo and filter added. Are you able to provide some extra details? Which streams are you seeing this on? Can you get a screenshot/recording of this happening? What other extensions are you running?

You can try these tips. Under Chrome extensions page, enable `Developer Mode` in the top right, this should reveal the `Update` button near the top of the page, click this to force check uBo update. Then toggle off/on uBo. 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/9f8b484b-1a0e-4b38-b4f3-8fc521d71241)

Afterwards, go to a twitch stream with ads and open the dev console(hit F12 on keyboard). Navigate over to `Console` and you should be seeing a message `Blocking ads`. On the video player itself, you should see a banner with the same message in the top left. Try a couple other streams. If you don't, then #200 applies to you which can randomly occur sadly. If so, Userscript is recommended. 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/3344f434-1b2d-4b9b-a92c-252378053cb8)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/df51f2f3-0f6a-4514-bb3d-9df71e6d577c)

**Comment by mjelloDev** [comment]
Having similiar problem after the latest fix of #249 

I am using chromium based browser [Cromite ](https://github.com/uazo/cromite)

**Comment by pixeltris** [comment]
Sure I can reopen this. I can't reproduce the issue with the optimizer changes. Both work for me.

Are you certain you don't have any other extensions installed and you only have one script enabled? Solutions tend to conflict with each other and produce this exact result (black screen, infinite loading wheel). `TTV LOL PRO` had some mitigations to allow the stream to load even with a script enabled but with the #249 change that is no longer the case so if you have that extension installed at the same time as the script the streams will now fail to load. See https://github.com/younesaassila/ttv-lol-pro/issues/334

**Comment by DaveKap** [comment]
Had an issue where neither of the uBlock vaft scripts were working but the userscript was working through violentmonkey (which wasn't running anything while I tried the uBlock scripts.) Unsure what's going on there, might be uBlock not loading in the scripts fast enough or being cached or something, just wanted to report my latest.

**Comment by pxia** [comment]
I had this issue that the stream wasn't loading at all. Disabling TTV LOL PRO plugin seems fixes it.

**Comment by DaveKap** [comment]
Vaft scripts are working again but every time they block the ads, the audio gets dysynced backwards by something like a quarter second.  After an hour I have to pause and play the stream to get it synced again because it's so desynced. So I'd say the Vaft scripts are still not 100% "working" unless there's some FFZ setting interrupting the process of catching up that I don't know about (unrelated to the "speed up playback to catch up" option, which is on.)
