### ISSUE TITLE
Vaft Not Working for Anyone Else?

### ISSUE THREAD

**Issue by EleZer0** [pixeltris/TwitchAdSolutions#264]
Hello! 
Using the Vaft script on tampermonkey on Firefox browser, and today is the first day in a long time no ads are blocking at all on twitch. Anyone else having this issue?
Any solutions to troubleshoot?

**Comment by stevenya97** [comment]
Are you updated to 9.0.0?

**Comment by EleZer0** [comment]
Yea it says @version 9.0.0 , weirdly enough video-swap-new seems to work for me atm, I guess I'll have to just stick with that for now.

**Comment by EleZer0** [comment]
ok idk, seems like both work again for me. Not sure what the hiccup was...
