### ISSUE TITLE
Does video-swap still play the ad in the background?

### ISSUE THREAD

**Issue by ojsl1** [pixeltris/TwitchAdSolutions#265]
ie. give ad revenue to streamers?

**Comment by zGato** [comment]
None of these scripts has ever done that AFAIK. It would also most likely be illegal and twitch would ban accounts for it.

**Comment by pixeltris** [comment]
It currently requests the ad segments on prerolls because they kept forcing prerolls on every refresh without it. I don't know if it counts towards ad revenue but I doubt it. It doesn't do it on midrolls.
