### ISSUE TITLE
Sidebar ads appearing with vaft userscript

### ISSUE THREAD

**Issue by Dickarus666** [pixeltris/TwitchAdSolutions#266]
Using google chrome, tamper monkey, vaft ver 10. Script is blocking regular ads but not the sidebar ones. Unfortunately I couldn't knab a screenshot before the sidebar ad disappeared but I'll post an update if it comes up again.

**Comment by stevenya97** [comment]
Are you referring to the channels sidebar on the left or the chat on the right? Are you able to describe the ad content/nature?  If it's a non-stream ad, likely will be covered by your browser's adblocker like uBlock Origin or Adguard for mobile devices. Update filter lists and retest. If you get that screenshot, post it here

**Comment by Dickarus666** [comment]
It's an ad that appears in the video's margin on the right side in a column. It's not part of the chat or the channels sidebar. I've only seen it twice in the past few days. Using uBlock, AdBlock, etc. seems to pause the stream intermittently so I've stopped using those.

**Comment by stevenya97** [comment]
Is it a video ad in nature or a static banner? Do they look like [these](https://www.reddit.com/r/Twitch/comments/yi35zx/twitch_finally_added_some_new_not_so_annoying_ads/)? There are also what Twitch calls `Stream Display Ads` [here](https://help.twitch.tv/s/article/stream-display-ads?language=en_US) with a couple of examples shown that might be similar to what you saw.

![000002339-11](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/fdab059c-7b1f-4427-9d52-5053f120668f)

These should be covered by an adblocker, vaft covers just the stream inserted ads. I don't see any of these new ads with vaft + uBo so try that out. Additionally uBlock, Adguard should not be pausing your stream. Double check that your `userResourcesLocation` under uBo Advanced Settings is cleared(should be 'unset') and you removed the filter from `My Filters`. Having uBo and Tampermonkey vaft scripts enabled at the same time can cause the pausing from trying to perform ad-blocking duties same time.

**Comment by Dickarus666** [comment]
That is exactly it. I didn't know vaft was only for the stream inserted ads, my mistake. The configurations aren't present, maybe uBlock wasn't the issue with the video pausing intermittently. I'll go ahead and re-enable then, thanks a bunch for the help.
