### ISSUE TITLE
Firefox Scripts broken

### ISSUE THREAD

**Issue by livvydoodlez** [pixeltris/TwitchAdSolutions#267]
I was noticing ads getting through for affiliate streamers, but not so much partner streamers, so I decided to upgrade to the latest scripts on everything for firefox.

Now that I did so, the video NEVER loads.

I'm forced to use the Twitch Alternative Player now in order to watch any stream.

**Comment by stevenya97** [comment]
Are you using uBlock Origin scripts or the userscript versions? What is the exact version you are on?

**Comment by Hotaru89** [comment]
Same issue as OP. latest firefox w/ ublock origin Version1.58.0

Was working fine until ads started to get through so I updated to https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/2eefb984c10ba64e9528b8cf4350d5fab653bd3a/video-swap-new/video-swap-new-ublock-origin.js
 & now it just never loads but if you disable it then loads.

**Comment by stevenya97** [comment]
uBlock Origin version can occasionally fail randomly, see #200. It is a known issue with uBo atm. The currently recommended ad block method by pixeltris is to use the userscript versions, which runs independently of uBo. The README has additional info. I can suggest the following:

1) There is a report from #262 that proxies can break the scripts. Disable any twitch proxy extensions temporarily(i.e. TTV LOL PRO, Alternate Player for Twitch.tv) and see if that fixes it. Multiple ad block solutions can potentially interfere with each other.

2) If you want to stay on the uBlock versions, reapply your uBo setup. Your permalink url is good, have it be the only url under `userResourcesLocation`. Make sure the filter `twitch.tv##+js(twitch-videoad)` is added to My Filters tab in the uBo settings.  Disable and reenable uBlock Origin extension. Restart your browser. It seems to be a lottery if uBo applies the script correctly.

3) If you want to use the more stable userscript versions, first REVERT any uBO applied changes from above(remove script url from Advanced Options, remove filter under My Filters). This avoids duplicate scripts running. Go ahead and install a userscript manager like [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)(open source) or [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/)(closed source). Open the link to the userscript of your choice from the README, which should prompt an install. Relaunch Firefox and test a stream out. Make sure you only have one script enabled at a time in userscript manager if you have both. You can swap between them easily to see which works best for you.
![Screenshot 2024-07-18 at 11 40 14 AM](https://github.com/user-attachments/assets/85e68282-e708-40b3-b846-29e70a22c02b)

**Comment by livvydoodlez** [comment]
Okay I wiped EVERYTHING that has to do with twitch adblocking, and I only used tampermonkey to install the vaft userscript via tampermonkey, and it DOES start to block some ads.

However, it blocks in-video ads, which also make the stream quality drop, but also doesn't stop smaller ads that also go in-video but doesn't interrupt the actual video.

The quality stays dropped until the actual ad WOULD be over, if it played. However, the issue is once another ad starts to play, the video quality drops, AND stops the video from playing. Audio still works and still continues like normal, but the actual video stops playing.

**Comment by ComfortableMilk4454** [comment]
got an ad with tampermonkey 5.1.1 with the vaft userscript:
![CleanShot 2024-07-19 at 18 29 07@2x](https://github.com/user-attachments/assets/4dd2cb80-94ce-478f-bdd3-8d48cd578921)

**Comment by ComfortableMilk4454** [comment]
also happens with violentmonkey

**Comment by stevenya97** [comment]
Do you have any other extensions running? 

Try open up the dev console(F12), do you see any messages with "Ads found, switching to backup" during ads? If not, the script is not running and there is an issue with Tampermonkey setup

**Comment by ComfortableMilk4454** [comment]
i have these extensions & ffz userscript running on twitch in addition to vaft
![CleanShot 2024-07-20 at 02 23 59@2x](https://github.com/user-attachments/assets/203b4bc7-5bc2-497d-9d83-9aca138ab1c2)
where would i find the messages in the dev console?

**Comment by ComfortableMilk4454** [comment]
nvm i went to the errors section and saw a lot of stuff:
![CleanShot 2024-07-20 at 02 33 09@2x](https://github.com/user-attachments/assets/dabc33d6-223f-401e-a9b6-3a0c9b064aca)

**Comment by ComfortableMilk4454** [comment]
@stevenya97 ^

**Comment by stevenya97** [comment]
I don't see the vaft related messages in there, is this still occurring? Something seems to be preventing the script from running.

**Comment by matirion** [comment]
Personally getting this error on both vaft and video swap new:
Script error in [Greasemonkey script https://github.com/pixeltris/TwitchAdSolutions/TwitchAdSolutions (vaft); version 10.0.0]:
TypeError: "fetch" is read-only. It seems to happen in the HookFetch function, and after the error it just doesn't run the rest of the function.

**Comment by livvydoodlez** [comment]
My apologizes that I didn't respond earlier, but it seems clearing everything out and NOT using Vaft and only the video-swap worked.

It does suck that the quality of the video drops heavily, but I'll still take that over ads, so it is working for me now.

however, as I can see you are still helping other people with other issues related, but figured i'd at least close the case with just me.
