### ISSUE TITLE
userscript, settings ublock nothing work for twitch

### ISSUE THREAD

**Issue by Owned67** [pixeltris/TwitchAdSolutions#272]
![FireShot Pro Webpage Capture 001 - 'uBlock₀ — Tableau de bord' - kccohkcpppjjkkjppopfnflnebibpida](https://github.com/user-attachments/assets/149be409-2e28-49cb-ae5b-d4771282f375)
![FireShot Pro Webpage Capture 002 - 'Réinstallation d'un script' - mfdhdgbonjidekjkjmjaneanmdmpmidf](https://github.com/user-attachments/assets/47ab52da-b7e4-47c5-8c1e-21c2c7f07917)

cleared cookie etc all and restarted opera,

getting awlays ads

**Comment by stevenya97** [comment]
Looks like you are running both the uBlock scripts and userscript. This means you are running two of the same scripts which are both trying to block the same ads streams. The README points out to NOT combine adblock solutions/scripts. Please choose one and revert/disable the other and report back. The current recommendation is to just use the userscript version as uBlock has some compatibility issues atm not loading the scripts. See #267 thread for troubleshooting tips.

**Comment by Owned67** [comment]
first time, ive onlyhte frist screenshot, after few minutes, getting ads so added second. but ok removed the one and trying only the script. Thanks!

if it don't work, will read the troubleshoot ;)

**Comment by Luigi534** [comment]
huh, the userscript is broken OR the ublock origin is broken, basically everyone is having issue lol

**Comment by xxAlex7** [comment]
> huh, the userscript is broken OR the ublock origin script is broken, basically everyone is having issue lol
> 
> and it's for both script

Yes, both are broken.. Userscript, uBlock userscript, vaft, video-swap and AdGuard Extra. Both have the same problem for me.

**Comment by Owned67** [comment]
hello, ive removed ublock and script, nothing worked properly....

ive installed other extension and working
