### ISSUE TITLE
Is there a way to whitelist specific channels when using video-swap-new?

### ISSUE THREAD

**Issue by orangecarnation** [pixeltris/TwitchAdSolutions#274]
Right what it says in the title.  There are some streamers I follow who go on break when ads are about to play anyway, so I don't mind letting ads play there, but disabling everything when I watch them and re-enabling when I go to watch somebody else sounds like a bit of a pain.  For either the userscript version or the ublock version is fine

**Comment by pixeltris** [comment]
This would be the best way to do it https://wiki.greasespot.net/Include_and_exclude_rules

Which goes in here

https://github.com/pixeltris/TwitchAdSolutions/blob/39666c7bb1446b3d5ac711d43e6b2ce5a5e54b2f/video-swap-new/video-swap-new.user.js#L1-L13
