### ISSUE TITLE
Video being reduced in size (black bars; player size remains the same)

### ISSUE THREAD

**Issue by Fe-n** [pixeltris/TwitchAdSolutions#275]
The last few days, I've noticed that sometimes the size of the video within the player will be reduced so that there are black bars on the left, right, and bottom of the player.  This does *not* seem to necessarily coincide with ads being ran.  I assume it's some promotional thing Twitch is intending to put up around the player while you watch, and that it is successfully being blocked, but the video is still changing size within the player.  Unsure if this can be avoided or not, but figured I'd mention it.

**Comment by pixeltris** [comment]
You'd need to find which filterlist is doing that and report it to the appropriate place
