### ISSUE TITLE
Brave and TwitchAdSolutions

### ISSUE THREAD

**Issue by ryanbr** [pixeltris/TwitchAdSolutions#276]
TwitchAdSolutions scriplet `vaft-ublock-origin` is included in experimental currently, and used in Beta/Nightly users for some time

Seems to work well, just want to confirm it works well with you. 

- If we enabled the twitch adblock by default, would we expect any issues? or any possible downsides? 
- We have a private AdBlock list authors Slack for devs uBO/Adguard/ABP/Brave/Ghostery etc, if you want to join. Flick me an email address to `mp3geek@gmail.com`. If you're keen

**Comment by pixeltris** [comment]
> If we enabled the twitch adblock by default, would we expect any issues? or any possible downsides?

If someone already has one of the scripts enabled as a userscript or if they have `TTV LOL PRO` enabled (https://github.com/younesaassila/ttv-lol-pro) it'll conflict and streams will fail to load (black screen with an infinite loading wheel)

I can't remember if I mentioned it but the VAFT script can be a little spammy. Worth checking the network tab of dev tools and filtering for `m3u8` and seeing if the additional requests are acceptable

There can be playback issues #164 but I'm not sure how regular they are. The issues mostly occur on midroll ads

**Comment by ryanbr** [comment]
Could the scriptlet used detect `bpaoeijjlplfjbagceilcgbkcdjbomjd ` installed and just silently exit?

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/commit/144bc99a619aff738030c7d7de1ed833d43c2514 adds Worker checks from AdGuard Extra which fixes the black screen / infinite loading wheel
