### ISSUE TITLE
Twitch ads coming back now

### ISSUE THREAD

**Issue by Johnrock191791** [pixeltris/TwitchAdSolutions#279]
Hi, is anyone getting twitch ads recently? I'm using vaft for a long time and it worked until today.

**Comment by Suprcheese** [comment]
Vaft is still blocking for me at present.

**Comment by Volneth** [comment]
I'm having the same issue, all of a sudden I started getting twitch ads again.

**Comment by Janmm14** [comment]
i did notice ads / twitch waiting screen using video-swap-new today.

**Comment by stevenya97** [comment]
Let's try to collect some more info. What browsers and script versions are you using?(uBlock Origin or userscript). Let me know if you are unsure how to check. If uBlock, what extension version are you on? If userscript, what userscript manager are you using? Are you able to post a picture of your enabled browser extensions?

I cannot currently replicate getting any twitch ads or waiting screens with Firefox 130, Violentmonkey 2.20.2, `video-swap-new` v1.3.0. If ad blocking was working previously, I suspect some of these cases may be the new [uBo 1.59.0](https://github.com/gorhill/uBlock/releases/tag/1.59.0) update and general quirks with uBo and the scripts #200 . There are some fixes and debugging suggestions in the #267 thread. The browser console should output some messages if the scripts are blocking ads properly that you can check for.

**Comment by pixeltris** [comment]
I can't reproduce. Try switching to the userscript version if you're currently using the uBlock Origin version of the script

**Comment by 64fanatic** [comment]
Vaft + Adguard Extra installed as userscripts is working. Don't add anything to Ublock Origin for now.

**Comment by stevenya97** [comment]
@64fanatic Fyi Adguard Extra is the same script/based on vaft so you may get conflicts down the line for using both on Twitch. Best to use one or the other but I understand Adguard Extra addresses a bunch of sites outside of just Twitch that you may need. If you do run into this issue, you can put an exclusion to twitch.tv for just Adguard Extra. The [README](https://github.com/AdguardTeam/AdGuardExtra?tab=readme-ov-file) has instructions on how to do that.

**Comment by zGato** [comment]
> @pixeltris Is there any way to watch by connecting to a specific server? I have playback issues with a specific server and Twitch always sends me to that server, I would like to avoid that server.

I can answer that for you and no, you'll need a proxy/VPN.

**Comment by xxAlex7** [comment]
> > 
> I can answer that for you and no, you'll need a proxy/VPN.

Thanks for the reply, I thought there was some way besides using a VPN, in that case it's better to stop using Twitch.

**Comment by Janmm14** [comment]
Today, twitch ad was blocked.
