### ISSUE TITLE
Infinite reload on 'notify-reload' solution for embed player. e.g destiny's bigscreen player 

### ISSUE THREAD

**Issue by ILikeTie** [pixeltris/TwitchAdSolutions#28]
i find notify-reload quite based and works 100% of the time, unless its on an embed player where it never stops refreshing. i can have 10 tabs open, all on the same stream in the embed and itll get past thousands of ads skipped with no success, itll just keep refreshing

just copy paste this but put any twitch channel at the end of the url https://www.destiny.gg/bigscreen#twitch/

for example, https://www.destiny.gg/bigscreen#twitch/hasnabi 
                     https://www.destiny.gg/bigscreen#twitch/pokelawls
                     https://www.destiny.gg/bigscreen#twitch/mizkif

find one thats live, and wait for an ad, and youll see. now idk if this is only for midrolls (just because off the top of my head while writing this i only remember it going off for midrolls while watching trainwrecks and nintendo directs, but it prolly happens for pre roll ads too

**Comment by pixeltris** [comment]
Each browser session is assigned a unique `Device-ID` by Twitch. This is used to determine if you've recently watched a preroll ad. You generally wont be served an ad if you've recently watched one. `notify-reload` notifies Twitch that the ad is watched and reloads the player to this effect.

For midroll ads each player reload will still be hit by an ad until the full duration of the ad is elapsed. The notification that the ad was watched isn't accepted by Twitch. As a result `notify-reload` generally wont be very effective on midrolls and you'll run into a lot of player reloads until the full duration of the ad period has elapsed (which can be several minutes long).

I would expect this behavior to be the same for both the embeded scenario and regular website. It Twitch does somewhat accept the "ad watched" notification on the main site, but not in when embeded? I'm not 100% sure in this case.

**Comment by ILikeTie** [comment]
absolutely certain. i try for how many dozens of minutes, sometimes multiple tabs refreshing at the same time and itll infinitely reload. i saw 3k ads skipped in the little ublock icon at the top right of my brower at one point just to see how long itll do it for. ill try to recreate it and post proof

**Comment by pixeltris** [comment]
The ad count indicator is probably a side effect of the player reload function. But yea reloading forever is a bug, I'll have to look at the state and see what's up with that.

**Comment by ILikeTie** [comment]
well it only reloads forever during embeds is what im saying, idk if thats fixable or not

**Comment by pixeltris** [comment]
I see what's happening:

- The embed player sends the `embed` player type. This is crux of the whole "purple screen of death" (PSOD) thing.
- `notify-reload` detects the purple screen segments as ads (as they are flagged as such) and instantly reloads the player.
- Whilst Twitch is flagging the embed player to show the PSOD, the player will get stuck in that reload loop. These periods of time which are flagged as PSOD can last upwards of 30 minutes, or even hours (or possibly days).

The fix for this would be to enforce a player type of `site`. There is actually code already to do this, but isn't hooked up https://github.com/pixeltris/TwitchAdSolutions/blob/d6d7fe3d1cb1c96c5402608e587c22648278ae8d/base/base.user.js#L36

There could be some additional code added to explicitly check for `embed` and set it to `site`. I'll consider adding this in.

**Comment by HexedHero** [comment]
I've been having this issue for the last 2 days just on normal Twitch not using any embed stream.

**Comment by pixeltris** [comment]
If you have `ttv-ublock` enabled in combination with `notify-reload` you'll run into this issue on the regular website. This is because `ttv-ublock` enforces the `embed` player type.

I wouldn't advise mixing Twitch ad blockers due to their conflicting effects.

**Comment by HexedHero** [comment]
I do not, I have https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-reload/notify-reload.user.js and that's it.

**Comment by pixeltris** [comment]
A few weeks back I had an instance where Twitch will keep serving preroll ads regardless of the "ad watched" notification. In the case of `notify-reload` this would cause an infinite reload.

You can verify if this is the case by removing `notify-reload` and seeing if you get preroll ads 100% of the time, even after fully watching each preroll.

**Comment by pixeltris** [comment]
I haven't tested but this should hopefully be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/f37af091928cc4c93375047d72195aae4b31e4bd as this now enforces the `site` player type.
