### ISSUE TITLE
Alternate Player for Twitch.tv

### ISSUE THREAD

**Issue by hitmonray** [pixeltris/TwitchAdSolutions#285]
how to keep twitch side bar while using Alternate Player for Twitch.tv???

**Comment by pixeltris** [comment]
In the description of the extension's web page it says:

> If you have problems with the extension, first read the help. To do this, in the player right click the view area, then in the menu click “Help”. If you still have questions, then in the same menu click "Send Feedback". If you cannot start the player, send an e-mail to the extension developer. The e-mail address is located somewhere on this page.
