### ISSUE TITLE
Ads leaking through 'notify-strip' / 'notify-reload'

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/TwitchAdSolutions#29]
Sometimes these scripts seem to stop working and let preroll ads through (testing on `uBlock Origin`, I'm not sure about userscript).

I'm not sure what's going on here, it seems re-applying the script "solves" the issue, but comes back some time later.

**Comment by GaroBal** [comment]
Can confirm this issue became prevalent about this week, reloading the page a couple times is a gamble whether the preroll will come up or if it is avoided

**Comment by placchio** [comment]
I also can confirm the issue. 
Im using the "Applying a solution (uBlock Origin)" thing, and today im suddenly getting ads again (in my case, mostly the ones played by the streamers). I had no ads until yesterday so seems a new problem, atleast in my case.

To try to counter it, i removed the script from Ublock to try the TTV-LOL extension, but im still getting ads anyway. Hopefully there is a fix soon :pray:

**Comment by pixeltris** [comment]
`TTV.LOL` shouldn't get ads assuming they maintain good up-time on their proxy. Alternatively try `Purple AdBlock`.

As for this issue I unfortunately haven't been able to reproduce it since making this issue. Some log points need to be added to see what's going on (e.g. the `window.Worker` hook, and various points in the `hookWorkerFetch` function).

**Comment by quepan** [comment]
it happened for one day i  turned ublock (chrome) of and on  and havent seen anything slip thru since so it was some sort of hiccup
