### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by willberhino** [pixeltris/TwitchAdSolutions#290]
Script not working for me on twitch

**Comment by willberhino** [comment]
its enabled and clicked on but ads are still rolling, it says last updated 13 days ago

**Comment by stevenya97** [comment]
Let's get some troubleshooting details. Do you use Firefox? Sounds like you are using Tampermonkey with userscript? Which script are you having issues with, `video-swap-new` or `vaft`? Are you seeing the `Blocking ads` banner in the top left of the video player during ads?
![Screenshot 2024-06-17 213939](https://github.com/user-attachments/assets/6e4d8f36-ad76-4e52-a061-1daa54ce88da)

**Comment by Myoko** [comment]
on edge browser ublock has worked well so far

**Comment by Tgod1991** [comment]
> on edge browser ublock has worked well so far

On Edge browser for me recently I get a lot of stutter and freezing. I am using Vaft which states it could cause more freezing/buffering

**Comment by TraditionalLemon** [comment]
I'm also getting ads as of a few days now, I'm running the script on chrome using ublock origin.

**Comment by stevenya97** [comment]
Unfortunately, likely an issue with uBlock as reported #200 . The script will randomly fail to load with uBo. Userscript is recommended and is more stable there.

**Comment by pixeltris** [comment]
Closing in favor of #294
