### ISSUE TITLE
Problem with Vaft

### ISSUE THREAD

**Issue by spotter226** [pixeltris/TwitchAdSolutions#292]
On Firefox, setting Vaft permalink inside uBlock, when there is an advertisement, “blocking ads” appears in the top left corner, but the video freezes and the audio continues to play.

**Comment by stevenya97** [comment]
Did you add the filter under My Filters? What browser are you using?

**Comment by spotter226** [comment]
Yes, I added the filter in my filters. The browser is Firefox 131.0.3

**Comment by pixeltris** [comment]
`vaft` is pretty unusable on firefox due to the unadressed playback problems (#164). I'd recommend `video-swap-new` under firefox.
