### ISSUE TITLE
Not working properly on Vivaldi

### ISSUE THREAD

**Issue by Silliel** [pixeltris/TwitchAdSolutions#293]
Just as a heads up, it's not working properly on Vivaldi. I have installed Ublock origin with the filters and vaft script, but it's playing adds nonetheless. I also tried TTV LOL PRO (disabling ublock origin when its running so I don't have both on the background running) and it's also not stopping adds from running. I'm not getting the "blocking ads" window at the top left either, I either see no adds (when it's working) or I get full-on adds.

**Comment by stevenya97** [comment]
No blocking ads banner usually means you have a conflict or the script isn't loading. Userscript is recommended. 

If you are on the latest version of the script you can try opening the browser console and seeing what messages pertaining to vaft appear. You can follow the steps [here](https://github.com/pixeltris/TwitchAdSolutions/issues/252#issuecomment-2145599172) if you want to diagnose it yourself. If a conflict from another script is happening, it will print to there.

**Comment by pixeltris** [comment]
Tested it and it works for me. Maybe related to #294. Try the updated script and make sure `hookWorkerFetch` gets logged to the console.
