### ISSUE TITLE
Frequent buffer issues, and this may be why:

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#295]
Line 833 has `return realFetch.apply(this, arguments);`
which appears to relate to this:
![image](https://github.com/user-attachments/assets/042038d9-b07c-49d8-b227-3a645bcd9c05)
that video-edge-306ee8.pdx01... often seems to take too long to respond, and it so happens to be when the bufferzone happens.

Any ideas?

OK, it's not the script's fault... But I can't find the cause, I tried everything.

**Comment by xxAlex7** [comment]
In the last few days I also started having buffer issues when the ad starts or ends, there is a buffer of 1s~5s and then the stream continues. I use Tampermonkey + userscript.

**Comment by stevenya97** [comment]
I believe you are referring to vaft? Might belong to #164

**Comment by TsukiZero** [comment]
It was with both (and no, not both at the same time)

**Comment by zGato** [comment]
That video-edge is just for tracking purposes (I suppose).
You can just block it with uBO and everything will continue working just fine.

**Comment by xxAlex7** [comment]
> That video-edge is just for tracking purposes (I suppose). You can just block it with uBO and everything will continue working just fine.

Yes, this is Twitch telemetry, but if you block video-edge, Twitch channel points will no longer work.

**Comment by pixeltris** [comment]
That request is handled by the window fetch hook which doesn't modify the request. The playback issues are more likely to come from the worker hook which modifies requests.
