### ISSUE TITLE
Is Twitch committing fraud in some way?

### ISSUE THREAD

**Issue by brunolm** [pixeltris/TwitchAdSolutions#296]
Does this

https://github.com/pixeltris/TwitchAdSolutions/blob/master/vaft/vaft-ublock-origin.js#L569-L586

Mean that Twitch acknowledge AD Block users as users viewing ADS?

**Comment by pixeltris** [comment]
The caller of that function is `tryNotifyTwitch` which is only called in one place which is commented out:

https://github.com/pixeltris/TwitchAdSolutions/blob/13f80faf3dffc327aa152de129f519a5ff482fc5/vaft/vaft-ublock-origin.js#L441

It used to be required to prevent prerolls from being served on every page load.

It's Twitch's job to only count genuine traffic.
