### ISSUE TITLE
[Suggestion] script that swaps the top left stream and main screen when ads play

### ISSUE THREAD

**Issue by G4-Synix** [pixeltris/TwitchAdSolutions#304]
The top left stream screen is full res if i remember correctly, and it is muted by twitch itself, it does have audio though, which can be enabled
I had been doing that before using extensions, i would turn on PiP mode on firefox on the smaller stream and unmute it, and I think some way of doing this automatically would be a viable way to avoid ads and that commercial break screen, which is the whole reason i am making this issue

**Comment by pixeltris** [comment]
There used to be a script which did that, it's either 360p or 480p but no longer works on prerolls which is why that method was removed.

**Comment by G4-Synix** [comment]
Oh makes sense, does it help with the "commercial break" thing? It could be used alongside something else if that specific screen is detected

**Comment by pixeltris** [comment]
It probably would when there are midrolls. Closing this for now but I'll keep this in mind if the current low res solution breaks.
