### ISSUE TITLE
No, alternate twitch player is a stopgap solution because it completely overhauls the UI and forces a different player and chat. I just need the bare minimum, not to see ads while they are thinking they're still being played.

### ISSUE THREAD

**Issue by Noobeley** [pixeltris/TwitchAdSolutions#306]
No, alternate twitch player is a stopgap solutions because it completely overhauls the UI and forces a different player and chat. I just need the bare minimum, not to see ads while they are thinking they're still being played.

I still want to use the normal twitch site with moderation tools, list of streamers live on the left, access to streamer's bio, and stream addons and overlays.

_Originally posted by @Noobeley in https://github.com/pixeltris/TwitchAdSolutions/issues/305#issuecomment-2521560804_

**Comment by Noobeley** [comment]
I've laid the groundwork for this, this is a greasemonkey script that pauses and mutes the stream when it detects an ad being played, which is something the other scripts fail to do:
I'm still struggling to find out a way to instead of pausing the stream ad, to instead just black out the tab, or black out the video player with a black rectangle over it, until the 30 seconds are up, and then unmute and continue.

(function () {
    'use strict';

    function checkForTextAndControlPlayer() {
        const textToFind = "stick around to support the stream!";
        const player = document.querySelector('video');
        const bodyText = document.body.innerText.toLowerCase();

        if (bodyText.includes(textToFind) && player) {
            player.muted = true;
            player.pause();
        } else if (player) {
            player.muted = false;
            player.play();
        }
    }

    const observer = new MutationObserver(() => {
        checkForTextAndControlPlayer();
    });

    observer.observe(document.body, {
        childList: true,
        subtree: true,
    });

    checkForTextAndControlPlayer();
})();

**Comment by pixeltris** [comment]
Try out https://greasyfork.org/en/scripts/415412-twitch-refresh-on-advert/code (linked in https://github.com/pixeltris/TwitchAdSolutions/blob/master/full-list.md)

It only mutes the ads by default but if you enable `disableDisplay` in the settings it'll hide the ads as well.

**Comment by pixeltris** [comment]
You might also be interested in this https://github.com/Mathnerd314/TwitchAdSolutions/blob/faa462924edf8b25d71c8d4f710710de35ae3258/mute-black/mute-black.user.js (from this PR https://github.com/pixeltris/TwitchAdSolutions/pull/16)

I'm not sure if it still works but it might help you on your way to creating the simple script you're after.

**Comment by xsmashx88x** [comment]
> You might also be interested in this https://github.com/Mathnerd314/TwitchAdSolutions/blob/faa462924edf8b25d71c8d4f710710de35ae3258/mute-black/mute-black.user.js (from this PR #16)
> 
> I'm not sure if it still works but it might help you on your way to creating the simple script you're after.

you got a way that for alternative twitch player that script can run on that, which will not change the quality when blocking ads how it does now?

**Comment by pixeltris** [comment]
The `vaft` script attempts to get a clean stream as fast as it can. The alternative is using a proxy which should always give you source quality.

**Comment by xsmashx88x** [comment]
> The `vaft` script attempts to get a clean stream as fast as it can. The alternative is using a proxy which should always give you source quality.

think he was meaning with ATP, as it kills the quality while blocking ads..

**Comment by xsmashx88x** [comment]
> `Alternate Player for Twitch.tv` doesn't use lower quality while blocking ads, it hides them as seen here [#305 (comment)](https://github.com/pixeltris/TwitchAdSolutions/issues/305#issuecomment-2521485735)

bud it does lower stream quantity

**Comment by xsmashx88x** [comment]
![image](https://github.com/user-attachments/assets/9bb457f2-5aea-4999-b303-564a85fabc08)

as can see, blocking it goes to crap when not blocking its clear

**Comment by pixeltris** [comment]
Ah ok. I haven't tested it much. Either way, getting clean high quality streams can only be obtained using proxies as mentioned above. You'd be better asking in their support pages for supporting such a thing.

**Comment by xsmashx88x** [comment]
> Ah ok. I haven't tested it much. Either way, getting clean high quality streams can only be obtained using proxies as mentioned above. You'd be better asking in their support pages for supporting such a thing.

sucks cant work in your stuff cause using normal twitch ads are blocked and stream stays clear... sometimes if having few open like using the alt player... and i guess prozy your talking is the paid ones with that lol addon?

**Comment by zGato** [comment]
> sucks cant work in your stuff cause using normal twitch ads are blocked and stream stays clear... sometimes if having few open like using the alt player... and i guess prozy your talking is the paid ones with that lol addon?

TTV LOL PRO has free public proxies available to everyone. And you can even find free proxies on the web. Now, it's not encouraged/nor recommended to use proxies you find in random places, so... getting your own is the best bet for a stable & smooth operation.

**Comment by xsmashx88x** [comment]
> > sucks cant work in your stuff cause using normal twitch ads are blocked and stream stays clear... sometimes if having few open like using the alt player... and i guess prozy your talking is the paid ones with that lol addon?
> 
> TTV LOL PRO has free public proxies available to everyone. And you can even find free ones on the web. Now, it's not encouraged nor recommended to use proxies you find in random places, so... getting your own is the best bet for a stable & smooth operation.

ya but i don't see this working with ATP

**Comment by zGato** [comment]
> > > sucks cant work in your stuff cause using normal twitch ads are blocked and stream stays clear... sometimes if having few open like using the alt player... and i guess prozy your talking is the paid ones with that lol addon?
> > 
> > 
> > TTV LOL PRO has free public proxies available to everyone. And you can even find free ones on the web. Now, it's not encouraged nor recommended to use proxies you find in random places, so... getting your own is the best bet for a stable & smooth operation.
> 
> ya but i don't see this working with ATP

We only support the desktop & mobile Twitch websites. They may add our proxy mechanism to their extension if they wish, and they can also contact me directly for explicit permission to use my proxies on their app. I don't really mind.
