### ISSUE TITLE
Video frame zooms out slightly, "Help improve Twitch" placed under video

### ISSUE THREAD

**Issue by ssateneth** [pixeltris/TwitchAdSolutions#307]
For months now, my twitch streams would randomly zoom out slightly, leaving a gap on the bottom, left, and right. It was weird and either the uBlock Origin team or VAFT team (I'm sorry, I can't remember which) would say something to the tune of that it must be some other addon causing the issue. Some other people were getting the same issue but met with the same resistance.

Today, it zoomed out again but had a new thing. A survey invitation was inserted on the bottom gap when the stream zoomed out. One the purple bar at the bottom of the survey invitation shrank to nothing, the "zoom out" went away and the stream went back to normal. Hopefully this is something to go on to get this ad fixed?

![2024-12-07_13-13-38](https://github.com/user-attachments/assets/085fe8f8-b2fb-4b47-ab09-7c9d0663c7ec)

**Comment by ssateneth** [comment]
It looks like #275 also reported the same issue of it zooming out but the survey thing is new.

**Comment by pixeltris** [comment]
Yea, this repo only deals with server side ad insertion (SSAI). Stuff like the player moving due to elements appearing is something that should be handled by an adblocking filter list or an annoyances filter list.
