### ISSUE TITLE
Please provide a feed for DNS host list for PiHole / ADGuard blocklists 

### ISSUE THREAD

**Issue by MikeKlem** [pixeltris/TwitchAdSolutions#33]
I already have host based blocking using these solutions.

The plusses are it works network-wide (PiHole) and on Mobile (My primary twitch consumption device) - ADGuard

**Comment by MikeKlem** [comment]
I’ve previously added regex blocklists, but would like to automate this by subscribing to a feed using these tools.
Ex. https://www.reddit.com/r/PrivateInternetAccess/comments/lac0tw/is_there_a_way_i_can_get_a_socks_proxy_in_eastern/

**Comment by pixeltris** [comment]
I'm clueless to the inner workings of PiHole (I've never used it myself). What you are asking is, could the solutions in this repo be converted to be used with PiHole?

Does PiHole allow for modification of traffic (http / https), or just block DNS requests? You need to modify the traffic for the solutions in this repo.

**Comment by pixeltris** [comment]
Yea, a pure DNS solution wont work as the domain name is always the same for a single stream (ad, or not). The only change is the file name of each segment (which is just a very long random / unique identifier of sorts).

**Comment by pixeltris** [comment]
I'm going to close this as it sounds like it's not feasible. Feel free to reopen if I'm wrong about this.

**Comment by MikeKlem** [comment]
Is there a supported configuration for this to be used with:
https://www.privoxy.org/
OR
https://github.com/jech/polipo

**Comment by pixeltris** [comment]
Sounds interesting, but I don't have any intentions of learning these and adding support. But feel free to take the code in this repo and adapt them as necessary.

**Comment by MikeKlem** [comment]
These would be network wide solutions, rather than a single device extension.

Thanks for the permission. What’s your license?

**Comment by pixeltris** [comment]
I haven't specified a license but I'd assume it would have to be GPL-3.0 as some snippets were taken from https://github.com/Nerixyz/ttv-tools which is licensed as such.
