### ISSUE TITLE
Broken on Chromium 90.0.4420.93

### ISSUE THREAD

**Issue by wllclngn** [pixeltris/TwitchAdSolutions#34]
Love the Extension. I'm having no issues on Chrome. However, on Chromium 90.0.4420.93 the Extension is not working. I understand the Extension might not be for Chromium users, but the issue will appear downstream on Chrome at some point, theoretically.

**Comment by pixeltris** [comment]
Which extension are you referring to?

**Comment by wllclngn** [comment]
I'm going thru the uBlock, userResourcesLocation option.

**Comment by pixeltris** [comment]
Weird, `90.0.4420.93` is a pretty recent version of chrome and should work. You'd have to diagnose the problem (there's probably errors in the console when viewing a Twitch channel).

**Comment by wllclngn** [comment]
It appears that "Purge all caches" and "Update now" in Filter lists of uBlock Origin worked currently. Apologies for not doing that before posting this issue.
