### ISSUE TITLE
Notfy Strip and Audio Latency

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#35]
Recently something Twitch did has been causing streams to repeat twice or thrice its first couple seconds and then desync the audio entirely with notify-strip.

**Comment by pixeltris** [comment]
Audio sync issues have been mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/17

At some point I will probably change the algorithm to be the same as `Video Ad-Block, for Twitch` which has a longer low resolution period, but none of the surrounding issues that `notify-strip` has (desync, stutters, freezing).

**Comment by pixeltris** [comment]
As mentioned #17 covers this. But should hopefully be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/f37af091928cc4c93375047d72195aae4b31e4bd if the issue persists comment in #17 and I'll reopen it.
