### ISSUE TITLE
notify-strip causing slideshow effect on video on any 720+ resolutions

### ISSUE THREAD

**Issue by chrcoluk** [pixeltris/TwitchAdSolutions#39]
So I have had this problem for a while and couldnt fix it, it would sometimes go away by refreshing window, the only way to prevent the slideshow effect was to drop resolution to 480p.  Audio is always normal.

I then remembered I had installed a userscript using notify-strip, disabled it and the issue has vanished but of course back to 30+ second ads on every time I jump streams, is this a known issue or unique to myself?

**Comment by pixeltris** [comment]
I haven't observed this, but you could try `Video Ad-Block, for Twitch` ([chrome](https://chrome.google.com/webstore/detail/video-ad-block-for-twitch/kgeglempfkhalebjlogemlmeakondflc) / [firefox](https://addons.mozilla.org/en-US/firefox/addon/video-ad-block-for-twitch/)) which uses the same idea as `notify-strip`, but uses a method with less technical issues after the ad period.

**Comment by saucettv** [comment]
You could also adapt the content.js file from Video Ad Block, into a userscript, if that's what you prefer. https://github.com/saucettv/VideoAdBlockForTwitch/blob/main/content.js

**Comment by chrcoluk** [comment]
Hi guys.  It might be I notice it more because twitch is really aggressively pushing ads on me.  Usually I get an ad on every 2-3 stream starts, sometimes many in a row.  Mid stream rolls, are usually anything from about once every 10 minutes to about every 2 minutes, which seems more than others get.

But it definitely stopped when I stopped using notify-strip. (got ads instead of course).

However I can confirm Video Ad-Block, for twitch works.  I can also see how often I am getting pounded with ad's as every 2-5 mins I see a skipping ad notification and it drops to 480p, but is the best solution I have seen so far.  The only time it got a bit flaky is when I seen someone in chat say he got 3 ads at once and at same time for me it was a bit flaky but on all other ad rolls it was ok. :)

Thank you to both of you and I may do the adaption.  

Interesting how we all get different frequency of ad's and different mitigations work for different people, as if twitch is deploying different mechanisms to confuse technical solution's :)

**Comment by pixeltris** [comment]
Yea, I think `notify-strip` needs to keep sending "ad watched" notification requests for a longer period as sometimes it doesn't get accepted, but the script stops sending the notifications once it sees source resolution. So pretty much every stream ends up getting the preroll, even after the expected ad duration. And as you observed, actually watching the ad results in no subsequent prerolls. `Video Ad-Block, for Twitch` might also have this bug.
