### ISSUE TITLE
[dyn-video-swap] Stream Stuck at 480p

### ISSUE THREAD

**Issue by jonyroda97** [pixeltris/TwitchAdSolutions#4]
Using: `dyn-video-swap`

I was watching a stream, using the ublock version, and went to try the script version.
Noticed it didn't show the little block, on the top left, that ublock shows when it changes to 480p.

Changed back to ublock version and now the streams are stuck at 480p always (and doesn't show the little box when using the ublock version).
Also, when changing to other stream it gets stuck on showing the previous stream (at 480p), even after the page loaded the rest of the stream that i changed to (chat, description, etc.)

If I change the solution or change to none, I can set it to 1080p but changing back to `dyn-video-swap` (whatever the version, script or ublock) it's stuck on 480p again.

What can i do to fix it?

**Comment by pixeltris** [comment]
That's odd, `dyn-video-swap` doesn't actually change the quality of the stream, it just displays a lower quality stream on top of the existing stream for the duration of the ad. It also doesn't have the ability remove the higher quality settings, if you don't visibly see the higher quality settings then something else is being applied. If you do see the higher quality settings, then maybe the lower quality stream isn't being removed after the ad.

I just tested ublock/userscript and both seem to work OK for me (I tested ublock on chrome, userscript on firefox). I didn't get the bug where the old stream displays when switching streams, but in general switching streams needs to be improved (as it doesn't handle the mini-player state change).

**Comment by TheHungryGeek** [comment]
You need to remove all the other special Twitch adblock extensions that you are using, such as the TTV ublock Chrome extension that specifically targets Twitch ads.

**Comment by jonyroda97** [comment]
I should not use ttv ublock at the same time?

**Comment by TheHungryGeek** [comment]
I think if you keep the ttv ublock on what happens is that it triggers the purple screen of death permanently, as a result you will never be able to access the high-res stream, and the 480p steam will be there covering the purple notice screen.

@pixeltris you may consider adding this in the instructions as I think a lot of your users here would have come from the ttv ublock Github.

**Comment by pixeltris** [comment]
Yea, it would probably make sense to add that to the README. I'll do so on my next commit.
