### ISSUE TITLE
somes ads is coming throo proxy call

### ISSUE THREAD

**Issue by arthurbolsoni** [pixeltris/TwitchAdSolutions#40]
somes ads is coming throo proxy call from russia or ukrania, i think that it could be the page site ads, not from the  stream broadcast. can anyone confirm it? does anyone see the purple screen with adblock proxy?

**Comment by Arecurius0** [comment]
same here. not getting the purple screen but getting ads since yesterday

**Comment by arthurbolsoni** [comment]
thanks :) i understand more now, i read that script. is awesome and work fine.

**Comment by pixeltris** [comment]
Perhaps check the result of the m3u8 (you'd need to resolve one of the m3u8 resolutions). And if you see an ad in the m3u8 you could dynamically switch to a different IP / location?

Probing the m3u8 is a good idea in general (if your bandwidth can handle it) as you'll get more insight into when ads are getting through.

**Comment by arthurbolsoni** [comment]
the problem is, that for me, i never see ads.  i watch stream every day and the ads no call. but for somes people come. 
i thought about do it. 2 proxys and switch when ads come.

**Comment by pixeltris** [comment]
It could also be that sometimes your ping page times out / is unreachable for some reason. But I somewhat doubt that.

**Comment by pixeltris** [comment]
Going to close this, sounds like the changes you made helped as there generally have been less posts about these issues.
