### ISSUE TITLE
Cookies are relevant to ads showing or not

### ISSUE THREAD

**Issue by Gallion** [pixeltris/TwitchAdSolutions#42]
I have a peculiar situation here that may be worth investigating.
I have Firefox and Chromium v.88.
I disabled all extensions in both browsers.
In both browsers I am logged into the same account and that account has Twitch Prime.
I get ads in Firefox and in Chromium in incognito mode but I don't get ads in Chromium in normal mode. My conclusion is that it has something to do with cookies.
I manually copied my Chromium Twitch cookie into Firefox. Firefox still got ads.
However, once I changed my Firefox "Browser Privacy" setting to "Standard", it stopped getting ads. I cleared cookies, logged back in without copying over the cookie and I started getting ads again.

Here is the cookie with sensitive data stripped from it : 
api_token=twilight.eeeeeeee;
auth-token=dddddddd;
last_login=2020-10-19T02:14:18Z;
login=cccccccc;
name=cccccccc;
persistent=bbbbbbbb;
server_session_id=ffffffff"
twilight-user={%22authToken%22:%22dddddddd%22%2C%22displayName%22:%22cccccccc%22%2C%22id%22:%22145430916%22%2C%22login%22:%22cccccccc%22%2C%22roles%22:{%22isStaff%22:false}%2C%22version%22:2};
twitch.lohp.countryCode=CA;
unique_id=aaaaaaaa;
unique_id_durable=aaaaaaaa;
unique_id_samesite_compat=aaaaaaaa;

Note the "twilight." prefix in the api_token entry. I think it may be relevant.

**Comment by pixeltris** [comment]
It should just be `unique_id` which had the impact. This is also referred to as `Device-Id` / `X-Device-Id`. Sometimes device ids never get ads. I'm not sure what triggers it. This is also mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/38#issuecomment-851035082

It should be possible to share such a device id with other people, but I'm not sure how long it would last as a workaround.

**Comment by saucettv** [comment]
There is also a cookie they put in now that's something like last-ad-seen then the value is the time, but I think this refers to overlay type ads, rather than the stitched ads. When testing my addon, I usually delete the unique_id each time I refresh as it also deletes the rate limit they have set to the unique id (so you get an ad every time with a new unique id). I'm working on some kind of shared but random device id that will change daily for the addon to test if it will reduce ad frequency even further, should be in the next update.

**Comment by pixeltris** [comment]
Closing this. As mentioned these cookies are known about but limited work can be done about this. In https://github.com/pixeltris/TwitchAdSolutions/commit/f37af091928cc4c93375047d72195aae4b31e4bd I implemented basic device id sharing which changes on a weekly basis, which may reduce ads depending on server implementation and number of active users.

**Comment by saucettv** [comment]
Really good work, I was trying yesterday. Ended up deleting all the work, but just realized, I used the random rolling device ID for all of the weaver requests (including the original) and it didn't work, got a pre-roll every refresh. I completely forgot about the usher request. Doh.
