### ISSUE TITLE
AdGuard is using your script, causing conflicts.

### ISSUE THREAD

**Issue by saucettv** [pixeltris/TwitchAdSolutions#44]
Just a heads up, AdGuard has a new "extensions" feature on their desktop app, one of them is called "AdGuard Extra". It basically has your older script and it causes conflicts for both of us.

Their script that they inject into the browsers: (Go straight to the bottom)

https://gist.github.com/saucettv/b6a8b6109034180dab8e6eacb522da25

I'm going to take a guess and say they won't remove it. Can you think of any way we can prevent the conflict?

**Comment by pixeltris** [comment]
I can't think of a decent way of handling that other than stating somewhere that AdGuard will conflict.

**Comment by saucettv** [comment]
Yeah, I tried a few ways but as both are hooking into the worker, it just messes it up and sometimes one loads before the other etc. I have put a warning on the descriptions of the extension. I'm suprised they are calling it AdGuard Extra though, thought they might use it as an external script to save themselves from law suits. Just thought I would let you know, as I've been getting so many reports about endless loading screens, frying my brain trying to figure it out, in the end a user helped me work it out.

**Comment by pixeltris** [comment]
I assume they call it "Extra" as it isn't a simple filter list. Similar to uBlock Origin [scriptlets.js](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js) / `userResourcesLocation`.

I think it's always loading screen along with a console error stating the URL is an invalid for a worker. So that's useful info for diagnosing the issue on the users end.

**Comment by berkant** [comment]
It was being tracked here: https://github.com/AdguardTeam/AdGuardExtra/issues/111

**Comment by saucettv** [comment]
AdGuard's response has been great, they implemented a check function to stop the conflict in their beta version of their script:

https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

The function name is isWorkerIntact, we can also implement something the same or similar to stop our conflicts.

**Comment by pixeltris** [comment]
With the way that's implemented (at the point DOM is loaded) it'll always use your hook if both are installed. If you implement a check in the same way it'll possibly be somewhat random which one it'll pick, which is bad in terms of users reporting issues.

So perhaps it's best left with the check only being only on the AdGuard side.

**Comment by saucettv** [comment]
Yeah that's a good point, hopefully they move it from beta to stable soon, there's only so many adguard responses I can manage in one day :D
