### ISSUE TITLE
Recommendations Purple AdBlock doesent exist

### ISSUE THREAD

**Issue by horst789github** [pixeltris/TwitchAdSolutions#46]
Purple AdBlock - chrome / firefox / code
looks the extension is deleted for firefox
"Oops! We can’t find that page"

**Comment by ZacharyTalis** [comment]
Was about to file this issue myself. I've still got Purple Adblock installed on Firefox, but it's [no longer available](https://addons.mozilla.org/en-US/firefox/addon/purpleadblock/) via Firefox's official Addons site.

You can still install the addon manually via its [source code](https://github.com/arthurbolsoni/Purple-adblock), if ya know how.

I've reached out to the addon's developer via Discord, I'll letcha know if I hear anything back <3

**Comment by arthurbolsoni** [comment]
not deleted, only DCMA problem with the logo

**Comment by arthurbolsoni** [comment]
7 days to fix it
