### ISSUE TITLE
notify-strip dosnt work

### ISSUE THREAD

**Issue by B1ack3ye** [pixeltris/TwitchAdSolutions#47]
The notify-strip no longer works for me. I updated to Windows 11 5 days ago and at the beginning everything worked fine, except that at the beginning of the stream I suddenly got ads, which I didn't have before.

Now I get since today (08.09.2021 | dd/mm/yyyy) again advertising during the stream and not only at the beginning.
I have checked the uBlock Origin configuration and have everything set correctly.

Google Chrome Version: 93.0.4577.63
uBlock Origin Version: 1.37.2
Windows 11 Version: Build 22000.176

Google Chrome Installed Addons:
- FrankerFaceZ
- HTTPS Everywhere
- Twitch Now (For notifications who is live)
- uBlock Origin

**Comment by pixeltris** [comment]
Still working for me for both prerolls and midrolls. Perhaps it isn't being applied for some reason.

**Comment by TheGinGear** [comment]
I just set it up myself with all add-on's except twitch now, it seems to work for me. Only other difference is running windows 10

**Comment by B1ack3ye** [comment]
Is there i-any way to view a debug log to find out what the problem might be? I don't know much about Google Chrome AddOns or network stuff with internet browsers.
