### ISSUE TITLE
`bypass` success chance?

### ISSUE THREAD

**Issue by Kein** [pixeltris/TwitchAdSolutions#49]
Tried it today a few times but it failed to bypass the ads.

**Comment by Borinius** [comment]
> 
> 
> Doesn't work for me at all

@HexedHero Make sure that you have followed the steps to add a uBlock script and also that you have no other twitch specific addons enabled.

**Comment by ryanbr** [comment]
If they change the "twitch-web-wall-mason" header, would it be easy to snoop for an updated id?

**Comment by MrGoatsy** [comment]
Bypass no longer works.

**Comment by JnTon** [comment]
I'm using Brave and after I stayed connected to a Twitch live for about half an hour it appears an ad which lasted for about 5 seconds. I think it's a type of advertising that lasts for a short time and is seen more rarely, I reported it on the related Brave issue: https://github.com/brave/adblock-lists/issues/2#issuecomment-943284080

**Comment by uBlock-user** [comment]
`server_ads:true` was always present, your scriptlet solution still worked there for 12 days, today it doesn't.

**Comment by TheEnhas** [comment]
Just got pre-rolls on a regular channel so something's definitely been changed now, reverted back to notify-strip which seems to always work for me (no pre-rolls). I used to use Purple Ads Blocker but the latency issues and random downtimes got too annoying.

**Comment by edadams** [comment]
+1 that the solution implemented in uBlock Origin no longer works at all. 😞

**Comment by edadams** [comment]
@dubesor Without wishing to be condescending, are you able to verify that the stream you were watching was actually running ads at all? Some don't. I.e., in a separate "clean" browser running in parallel, did you see ads?

I ask because I definitely had the `bypass` method working for me as recently as yesterday but today - nothing.

**Comment by dubesor** [comment]
> 
> 
> @dubesor Without wishing to be condescending, are you able to verify that the stream you were watching was actually running ads at all? Some don't. I.e., in a separate "clean" browser running in parallel, did you see ads?
> 
> I ask because I definitely had the `bypass` method working for me as recently as yesterday but today - nothing.

Yes, the long testing was on gmhikaru and dansgaming, the hopping was random whatever twitch suggested (XQC, amanrath, etc.) 100% ads with uBO disabled, none when enabled. I obviously can't record 2 hours to wait on midrolls but here at least is current preroll behaviour on fresh profiles:

[https://www.youtube.com/watch?v=tc4ljbWrhU0](url)

**Comment by Trung0246** [comment]
Looks like `twitch-web-wall-mason` trick no longer works as of today (using `streamlink https://twitch.tv/xqcow best --http-header X-Device-Id=twitch-web-wall-mason --http-header Device-ID=twitch-web-wall-mason`). Can anyone confirm? (I'm currently have U.S residential IP)

**Comment by garoto** [comment]
bypass headers still working for me with yt-dlp+mpv for skipping the pre-roll ads, but only when yt-dlp is used as the m3u8 extractor. Regular `youtube-dl (2021.06.06)` doesn't skip the pre-rolls.

**Comment by saucettv** [comment]
Seems like this is region based, or they are slowly blocking the device ID, some users it works for and some it doesn't. Personally, I tried it without Video Ad-Block and I am now getting ads and the rate limit is not being applied (it worked about a week ago), so now I'm getting an ad every single refresh when only UBlock is enabled.

I made the issue https://github.com/uBlockOrigin/uBlock-issues/issues/1789 because current users of UBlock Origin that this is affecting, will now be getting more ads with UBlock, than without it. As there has been multiple users now experiencing the same issue, including myself, I feel it should now be an optional scriptlet to prevent rate-limit issuses.

**Comment by pixeltris** [comment]
As mentioned in the referenced issue it has been removed from the uBlock Origin filter list. Purging your caches will update this. If you still have the filter in your own filter list it will still use the bypass script (or the override in `userResourcesLocation`). If you want to use an external solution make sure to remove it from your filters.

I've updated the README to state that this solution may no longer work and I've moved it to the bottom of the scripts list.

**Comment by saucettv** [comment]
Looked into this further and seems like Twitch is blacklisting user ID's from using the bypass. This can be fixed by removing the OAuth header. I added the following to the script and now I'm ad-free:

`                if (typeof init.headers['Authorization'] === 'string') {
                    init.headers['Authorization'] = '';
                }`

**Comment by garoto** [comment]
The above might explain why the bypass Headers still work with `youtube-dl` and variants, since cookies are ephemerals.

**Comment by pixeltris** [comment]
Weirdly streamlink [removed the bypass](https://github.com/streamlink/streamlink/pull/4112) and they don't use logins... unless `embed` [(which they use)](https://github.com/streamlink/streamlink/blob/5c9fa063e2200aaeb530c59a5e8ead7048334d38/src/streamlink/plugins/twitch.py#L303) combined with the bypass results in ads.

**Comment by saucettv** [comment]
Think I saw somewhere about if playerType is blank, they over-ride to SureStream. This was to block previous ad-blocking attempts when people used to use Facebook etc as playerType. So could be the embed causing it.

**Comment by saucettv** [comment]
The bypass method will most likely get patched eventually, but I'm guessing they are very busy at the moment with the whole leak thing.

**Comment by THEDARKK** [comment]
I found a bug when a channel has its vods in subonly and we are sub. it marks us that we are not sub.

**Comment by pixeltris** [comment]
Should be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/aad8946dab2bba951bb81c7730292fe595a7a6ae

**Comment by THEDARKK** [comment]
Ok, tampermonkey didn't update the script, it works thank you.

**Comment by pixeltris** [comment]
Ah I've been forgetting to bump the version on that script.

**Comment by pixeltris** [comment]
I'm seeing ads with this now.

**Comment by THEDARKK** [comment]
The same,I use notify-strip, there is less problem with ads

**Comment by saucettv** [comment]
Yeah looks like they have patched the device ID completely now.

**Comment by pixeltris** [comment]
Closing this. I'm not sure if this method actually works for anyone still, but it's still being applied by default on uBlock Origin.

As I've not seen this work for me personally for a while I'm going to remove it from the repo within 60-90 days of this comment. Perma links will still work ([ublock](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/aad8946dab2bba951bb81c7730292fe595a7a6ae/bypass/bypass-ublock-origin.js) / [userscript](https://github.com/pixeltris/TwitchAdSolutions/raw/aad8946dab2bba951bb81c7730292fe595a7a6ae/bypass/bypass.user.js)) but the ones in the README will break.
