### ISSUE TITLE
All scripts fail to have any effect

### ISSUE THREAD

**Issue by garbb** [pixeltris/TwitchAdSolutions#5]
Firefox Developer portable 73.0b12 (64-bit), Tampermonkey 4.11.6117
Maybe it is because I have an old version of firefox and/or tampermonkey, but no matter which userscript I try, ads still play and I get error(s) in the console like this:

```
Syntax error @ "TwitchAdSolutions"!
##########################
JSHINT output:
##########################

F_a/n</<@eval:3:90
c@eval:2:142
E_u/<@eval:3:259
na@eval line 1 > Function:60:410
create@eval line 1 > Function:72:221
run@eval line 1 > Function:13:205
anonymous/</</<@eval line 1 > Function:73:500
F_a/n</<@eval:3:90
c@eval:2:142
anonymous/</<@eval line 1 > Function:73:483
anonymous/<@eval line 1 > Function:73:510
TM_back@eval line 1 > Function:74:3
anonymous@eval line 1 > Function:74:10
F_a/n</<@eval:3:90
exec_fn@eval:1:144
@eval:12:330
P@eval:11:120
eval line 1 > Function:61:375
    na eval line 1 > Function:61
    syntaxCheck eval line 1 > Function:23
    I eval:11
    P eval:11
    (Async: Async)
    n eval:3
    b eval:10
    n eval:3
    c eval:10
    send eval:11
    syntaxCheck eval line 1 > Function:23
    na eval line 1 > Function:60
    create eval line 1 > Function:72
    run eval line 1 > Function:13
    anonymous eval line 1 > Function:73
    n eval:3
    c eval:2
    anonymous eval line 1 > Function:73
    anonymous eval line 1 > Function:73
    TM_back eval line 1 > Function:74
    anonymous eval line 1 > Function:74
    n eval:3
    exec_fn eval:1
    <anonymous> eval:12
    P eval:11
```
Also this syntax error in tampermonkey wihch may or may not be related?
![image](https://user-images.githubusercontent.com/4453789/103188658-322fba80-487e-11eb-8351-ad8a3881e0bd.png)

Any idea what might be causing this?

**Comment by pixeltris** [comment]
Null propagation, not sure if it's implemented by all browsers. I'll remove it.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/commit/9ef9d278ebfcc6e1284af7eed52d84c8a7b24bcb should fix the null propagation errors, not sure if there are other errors.

**Comment by garbb** [comment]
Actually I updated to firefox 84 and it works fine.

**Comment by pixeltris** [comment]
Null propagation is a relatively new feature to JavaScript which is probably why it didn't work in 73. And yea that function is only used by `dyn-skip-midroll`.
