### ISSUE TITLE
Cannot make channel predictions

### ISSUE THREAD

**Issue by Raulsack69** [pixeltris/TwitchAdSolutions#50]
When a twitch channel starts a channel prediction, normally you can click the "Predict" button and a small window in the chat will popup allowing you to make a prediction. When using the Ublock Origin filter method (without the extension) this window pops up only briefly and then disappears. When I comment out the filter, channel predictions works as intended. I have observed the behavior with both the bypass method and the notify-strip method (I have not tested the other two methods).

Relevant system information:
Google Chrome 94.0.4606.81 (64-Bit)
Ublock Origin 1.38.4
Windows 10 21H1 (Build 19043.1237) (64-Bit)

**Comment by pixeltris** [comment]
I'm unable to test as I don't have a Twitch account. Could you test channel predictions using this:

https://gist.githubusercontent.com/pixeltris/8372c223f62999dc7c1d1714eeb791bc/raw/a8357ab576cacd032895297e09fb302f9a3dca68/temp-twitch-test.js

**Comment by pixeltris** [comment]
Fixed both scripts. It should also be fixed on the one enabled by default in the next uBlock Origin update. That gist will be deleted soon.
