### ISSUE TITLE
'Low-res' connection drops after 30s now?

### ISSUE THREAD

**Issue by Dwedit** [pixeltris/TwitchAdSolutions#51]
Right now, I'm using the 'low-res' script, and I'm noticing the stream connection drops after about 30 seconds.  Has Twitch successfully managed to block this now?

**Comment by pixeltris** [comment]
>connection drops

What exactly do you mean by this exactly? Do you see an infinite loading wheel? Or an error code with a "reload player" button? If so what error code?

Seems to be working correctly for me beyond 30 seconds.

**Comment by Dwedit** [comment]
I meant that it required the "reload player" button to proceed.

Anyway, I'm not experiencing the problem now, so it might have been a coincidence.

**Comment by pixeltris** [comment]
I was regularly getting error code 1000 on some streams a little while ago using `notify-strip` but haven't seen it since. Maybe it's related to that. I'll close this for now. Feel free to reopen if the issue comes back.
