### ISSUE TITLE
Getting Ads with Twitch Turbo

### ISSUE THREAD

**Issue by ImpalaPUA** [pixeltris/TwitchAdSolutions#52]
Not really an issue with any of the adblocks, just want to let people know I pay for twitch turbo and now I see pre rolls in every channel.

I will be cancelling that sub for an adblock

**Comment by pixeltris** [comment]
If you're using `bypass` this will interfere with Twitch Turbo due to the authorization removal (aka essentially Turbo removal).

`bypass` is fixed and is now showing ads. Ref https://github.com/pixeltris/TwitchAdSolutions/issues/49

**Comment by ImpalaPUA** [comment]
I'm not

https://www.reddit.com/r/Twitch/comments/qr1y1i/twitch_turbo_running_ads/

They make it so if you're running an adblock it runs ads for you regardless of subscription to streamer or turbo

You now have to use a proxy addon with adblock disabled

**Comment by pixeltris** [comment]
It's probably because the uBlock Origin filter which is being applied by default gives a version of `bypass`. This needs to be removed:

https://github.com/uBlockOrigin/uAssets/blob/6ad7764e535d2b4f7de1ccaf9daecd4df66925dd/filters/filters.txt#L5189

**Comment by ImpalaPUA** [comment]
This actually might be the fix, thanks, will test it out

**Comment by ImpalaPUA** [comment]
How do you disable 1 line of the filter, I thought it was adding this to "My Filters"

~twitch.tv##+js(twitch-videoad)

**Comment by pixeltris** [comment]
I think `twitch.tv#@#+js(twitch-videoad)`

**Comment by thinkpad4** [comment]
> I think `twitch.tv#@#+js(twitch-videoad)`

This worked for me @pixeltris

**Comment by ImpalaPUA** [comment]
This was posted in that reddit

In ublock, go into settings -> my filters and add

twitch.tv#@#+js(no-floc)
ext-twitch.tv#@#+js(no-floc)
twitch.tv#@#+js(twitch-videoad))

**Comment by pixeltris** [comment]
It should just be the `twitch-videoad` one which is having the impact.

**Comment by ImpalaPUA** [comment]
Well that fixed it, I also submit a ticket to twitch threatening to cancel my turbo sub, so I'm curious how they will fix it for other turbo users without allowing that bypass

**Comment by ImpalaPUA** [comment]
Kinda funny to add in to this, is if you are subbed to a streamer and have that in your ublock, you will get ads even if you are subbed

People complained to xqc about it and he said on stream twitch told him to tell them to disable your adblock kekw

**Comment by pixeltris** [comment]
This kind of thing has happened quite a few times now where the Twitch devs fix an ad bypass, but they do so abrasively (i.e. when a bypass is enabled you'll see more ads than normal, or in this case breaking Turbo).

I'm not sure if it's massive oversight, or if the Twitch devs blindly do what their superiors tell them to without much thought and don't care or the potential issues it may cause.

Either way I wouldn't expect them to do anything about it. Case in point; the embed player is still completely broken, albeit in a extremely weird and unintuitive way (at certain times of the day there's a periodic purple screen, others there is not).

**Comment by saucettv** [comment]
From what i've seen from Reddit posts, the Brave browser must of implemented the bypass script also. I think both Brave and UBlock will need to remove the filter because right now the rate-limit isn't being applied, Twitch users are getting ad after ad.

**Comment by pixeltris** [comment]
Yea Brave pulls it in from somewhere.

I don't think Twitch has pushed it out to all their servers so not everyone is impacted and it'll probably only be removed when there are reports on `/r/uBlockOrigin`.

I'm looking for more info for impacted Turbo users. I want to know if the issue occurs on uBlock Origin 1.38.6 where `userResourcesLocation` is `unset`.

**Comment by saucettv** [comment]
Mine is unset with no custom filters, server_ads=true with the GQL request using the bypass device ID, think they have it enabled by default.

**Comment by saucettv** [comment]
I think UBlock has at least put the Auth header back in though, or never removed it, so for UBlock users at least it won't be affecting Turbo users, as long as Twitch isn't just over-riding Turbo if the request uses the bypass device ID. It does affect the rate-limit though, but I doubt users are going to blame UBlock for that, they will just think Twitch is pushing a ton of ads.

**Comment by saucettv** [comment]
I'm not sure if the UBlock devs understand the rate-limit issue, which could be a problem because users will blame Twitch.

**Comment by pixeltris** [comment]
I mention 1.38.6 for impacted Turbo users is because anything greater than 1.38.6 (which are currently dev / preview builds) includes the `Authorization` header change, which I would expect to break Turbo in cases where the contacted Twitch server has the `twitch-web-wall-mason` flagged to always serve ads. Brave might pull the script in from a version greater than 1.38.6.

This info was requested to determine if it should be removed from uBlock Origin https://github.com/uBlockOrigin/uBlock-issues/issues/1789#issuecomment-967059621

**Comment by saucettv** [comment]
Oh got ya

**Comment by ImpalaPUA** [comment]
> Yea Brave pulls it in from somewhere.
> 
> I don't think Twitch has pushed it out to all their servers so not everyone is impacted and it'll probably only be removed when there are reports on `/r/uBlockOrigin`.
> 
> I'm looking for more info for impacted Turbo users. I want to know if the issue occurs on uBlock Origin 1.38.6 where `userResourcesLocation` is `unset`.

Yea, it's unset

**Comment by Nojuuu** [comment]
https://www.reddit.com/r/brave_browser/comments/qu2282/question_about_twitch_ads_brave_and_turbo/

**Comment by pixeltris** [comment]
As mentioned above Brave bundles the same script as in uBlock Origin (though not exactly sure where it pulls it in from looking at their various repos).

Related commit which re-enabled it https://github.com/brave/adblock-lists/pull/658 and related issue https://github.com/brave/adblock-lists/issues/2

For anything specific to Brave you'll probably get a better response commenting on that issue instead.
