### ISSUE TITLE
Only one channel blocked

### ISSUE THREAD

**Issue by Immortalis202** [pixeltris/TwitchAdSolutions#53]
Hi, i was wondering how make the first userscript to be available for all the twitch's channels and not for a single one

**Comment by pixeltris** [comment]
`notify-strip`? It should function on all channels.

**Comment by Immortalis202** [comment]
![immagine_2021-11-17_115918](https://user-images.githubusercontent.com/66247326/142188252-86c745bc-77a9-4a24-813f-c755f84ba8de.png)

Maybe i have this problem because of the @match? What I should write in that section?

**Comment by pixeltris** [comment]
Uhh that could be breaking it maybe. It should install just by viewing the url https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-strip/notify-strip.user.js

Alternatively make sure to Ctrl+A Ctrl+V to replace any existing code.

**Comment by Immortalis202** [comment]
Solved! Thank you for the help, reaaly appreciated.
