### ISSUE TITLE
Just a quick question, not really an issue.

### ISSUE THREAD

**Issue by saucettv** [pixeltris/TwitchAdSolutions#55]
Have you noticed any of the new audio ads or video poll ads? I'm not sure if blocking the original amazon-adsystem URL also stops them kind of ads or not. I'm also not sure if the in-stream type ads are stitched or not. Haven't seen one myself.

I know Twitch loads:

https://static.twitchcdn.net/assets/features.video-player.components.video-ads.video-ad-poll.container*
https://static.twitchcdn.net/assets/features.video-player.components.video-ads.audio-ad-overlay.component*

But as they are supposed to be rare, I can't find any to test. Would rather not add another host permission to a script, so I'm hoping they are blocked by blocking the original amazon-adsystem script. Haven't seen any complains on UBlock either about them.

**Comment by pixeltris** [comment]
I don't want enough to see this kind of thing. I saw a "Multiplayer Ad" some time ago when using the `bypass` script, but haven't seen anything like that since. I think the streamer needs to manually invoke it.

I probably wouldn't worry too much until people start reporting that they see them.
