### ISSUE TITLE
Notify Strip might need to be tweaked again...

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#56]
Twitch has been overaggressive in their midrolling, to the point some streams can be nigh unwatchable. Example: https://www.twitch.tv/grimmyhunter gets A LOT of midrolls during their regular content rather than on breaks..

**Comment by pixeltris** [comment]
Aren't streamers limited to showing a midroll a max of once every 30 minutes? How frequently are you seeing them on an individual stream?

**Comment by TsukiZero** [comment]
Yeah, but before the new adpocalypse started going on, you'd barely or not notice that midrolls and the like are happening. Now they can even KILL the stream when it happens and there's a distinct pause or, in worst case scenarios, stacking latency.

**Comment by pixeltris** [comment]
I saw that `Video Ad-Block, for Twitch` made some tweaks to the logic a little while ago. It might fair a little better. For now I'm happy enough with the logic of `notify-strip`. But yes, it could be better.

I personally avoid streamers who spam midrolls. I know it's their job, but even top streamers unapologetically spam the hell out of it purely out of greed. I'm more than happy to avoid them.

**Comment by TsukiZero** [comment]
Yeah, making the switch to that one for the time being. At times I suspect Twitch is automatically activating Midrolls in secret, because they happen even with streamers who swears they have turned midrolls off.

**Comment by pixeltris** [comment]
Well if you use Brave or uBlock Origin (and don't override twitch-videoad.js) then you'll pull in a variant of `bypass`. Some people observe the method as patched and will see way more ads (preroll every time, and potentially more midrolls).

But yea midrolls will only normally show if if the streamer invokes it. Typically they wont do it manually and have it set to automatically run every X minutes. Maybe a tool is doing it for them without their knowledge.

**Comment by TsukiZero** [comment]
Now that you mentioned "twitch-videoad.js", there is a possibility I did override it at some point but undid when the problem was "fixed". I'll go see if that may be the case

**Comment by pixeltris** [comment]
Closing this as I don't have any plans of changing the logic of `notify-swap`.
