### ISSUE TITLE
multiChat for Twitch removed from Play Store, may no longer work after February

### ISSUE THREAD

**Issue by adamf30** [pixeltris/TwitchAdSolutions#57]
multiChat for Twitch isn't really available on the Play Store anymore, and it only plays at 480p. Worst case, it may no longer function once Twitch removes the V5 Manifest API. There needs to be an alternative to this.

**Comment by pixeltris** [comment]
Yea its been gone for a while, I just keep forgetting to remove it from the list. `Xtra for Twitch` is back and is using the `ttv.lol` proxy as its ad blocking method https://github.com/AndreyAsadchy/Xtra

I'll update the list at some point.

**Comment by pixeltris** [comment]
I have updated the links. I have changed it to link to https://github.com/crackededed/Xtra (though I'm not 100% sure if it actually blocks ads).
