### ISSUE TITLE
Looking for feedback on a fix for Firefox freezing issue

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/TwitchAdSolutions#59]
Firefox currently has an issue when entering / leaving midroll ads. Audio will keep playing but the video will freeze. When this happens post-ad it will never fix itself (user interaction is required to fix the player).

I've made some changes which modifies how the solution works. I'm looking for feedback on this solution as I'm unable to properly test it.

userscript:

*<removed as the url will 404 at some point, the script is now in the main repo as `notify-swap`>*

Diff against notify-strip:

https://gist.github.com/pixeltris/34bb5a63fdf70091939e321daa59caff/revisions#diff-8c686d86ed7d00cf35e90e75728749a10b20abdd7bb5b5ce99422e68716cd549

---

Details on how this solution works:
- If an ad segment is detected it invokes a full reload of the Twitch player which forces a refetch the main m3u8, which is then replaced with a low resolution version.
- Segments for this low resolution version are let through unmodified. While this happens requests are made to find a non-ad version of the stream.
- Once a non-ad version of the stream is found it does another full reload of the Twitch player, this time inserting the ad-free m3u8.

The biggest difference here is that only the initial m3u8 requests are modified. The original solution modifies every m3u8 request which contains ad segments resulting in sequencing issues (i.e. freezing). This was resolved by invoking a pause / play, but that no longer seems to work on Firefox.

The full player reload means that it takes it slightly longer to transition (~1 second) between ad/no ad compared to the pause/play method which was quite fast (< 1 second). Additionally it causes an interruption on both entering the ad and leaving the ad (as opposed to only when leaving the ad with the old method). But hopefully it shouldn't get stuck like the original solution does sometimes when an ad begins.

Due to the way this solution works when it goes bad it'll probably be very bad (likely re-loading the player unnecessarily until the ad finishes).

NOTE: I haven't had the chance to test this much, so it might be more broken than I think.

**Comment by aommaster** [comment]
For what it's worth, I tested this out. I don't seem to be getting the refreshes that you mentioned in this issue and the script works perfectly as it did before without those freezes. Not sure if it might be my own Firefox settings at play though.

**Comment by pixeltris** [comment]
I call it "reload" but it doesn't actually reload/refresh the page, it just reloads the player. It looks almost identical to the old method (pause/play) but takes slightly longer (~1 second instead of < 1 second).

And thank for the feedback. I have been able to test it a little bit myself and it has been working well so far. I think I saw one time it resumed a paused stream, so I'll have to look into that at some point.

**Comment by kotobuki09** [comment]
It seems to fix the freezing issue for me and the player reloaded for sure after the mid ads are blocked. Seem work great for me until this point

**Comment by pixeltris** [comment]
It's currently just a userscript so you'd need to install it in the same way you'd install any userscript. There are some issues I'd like to fix before putting it into the main repo. I'll look at doing that soon.

**Comment by JesseNewman19** [comment]
Tried it out today, seems to work just fine as you described.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/commit/bd96135e245977c7fda8ab66aef86728dca19466 adds this into the main repo as `notify-swap`. Things I have changed since the test script:

- Removed ad notifications on midrolls (it doesn't help with reducing ads and it would spam a huge amount of unnecessary gql requests).
- Fixed issues where ads would cause the tab to pick up player settings from other tabs. E.g. tab A you set to 1080p, tab B you set to 320p, they would end up interfering with each other when ads occur. This should no longer happen.

The script linked at the top of this issue may eventually 404.

I have added `vaft` which is `Video Ad-Block, for Twitch` as a script if you prefer how that one works. Though I am not maintaining it beyond copy / paste from the open source repo at https://github.com/cleanlock/VideoAdBlockForTwitch

**Comment by CaelTheColher** [comment]
While blocking ads with notify-swap the stream cuts off (black screen, no audio) entirely after a few seconds, needing a reload of the player to fix.
Not sure if this is a weird interaction with the twitch extensions I use, but I don't know a reliable way to test it.

**Comment by pixeltris** [comment]
Hmm odd. I have noticed that sometimes it can take a little while to actually resume playback, but I haven't observed it completely stopping the stream.

One reason that might happen is if you have auto playback as disabled in forefox as when `notify-swap` does its transition it reloads the player which will be at the whim of your playback settings.

I might look at integrating the fix-up method used by `Video Ad-Block, for Twitch` into `notify-strip` and just keep `notify-swap` as an unlisted backup script. I need to spend some time investigating the nuances of that method.

**Comment by TheEnhas** [comment]
`notify-swap` works fine for me, the reload is fast and it seems to work faster than `notify-strip` if that makes any sense (ad breaks are shorter).

I used to use `Purple AdBlock` (called `Purple Ads Blocker` on Firefox) and while that blocks all ads I get serious buffering issues and lag to the point it's not worth it so I went back to using a userscript instead. `vaft` works but has a habit of not putting the resolution back to what it was before once the ad break is done and I get the freezing issues and buffering with `notify-strip` so (for now) `notify-swap` works best for me.

**Comment by pixeltris** [comment]
Unfortunately it seems under firefox my localStorage hooks don't work which means things like volume / mute / resolution settings will conflict between tabs.

I also played around with the `vaft` method of fixup to possibly bring to `notify-strip`. It somewhat works but not well enough for my liking. So I'm leaving everything as-is for now which isn't great for firefox users, but at least there are some options to pick from.
