### ISSUE TITLE
Remove my URL from your Code

### ISSUE THREAD

**Issue by ChoosenEye** [pixeltris/TwitchAdSolutions#6]
Hey there,

could you please remove my URL to my Proxy Server from your Code and your User/uBlock Script.

I have no Problems in Sharing my Chrome Extension but please don't use the URL in other Scripts, it will maybe be changed over time and the old Scripts won't work then anymore, with the Chrome and Firefox Extension i can update them if needed.

There are the official Links to both Versions.

https://chrome.google.com/webstore/detail/twitch-adblock/mipdalemhlhfenbikcloloheedmmecme
https://addons.mozilla.org/de/firefox/addon/twitch-adblock/

**Comment by lukix29** [comment]
As the Dev of the Extensions, i support this.

**Comment by pixeltris** [comment]
The purpose of this repo is to provide a number of solutions for blocking ads without using specialized extensions. I also include links to solutions which work as specialized extensions, applications, external sites, etc.

I will happily change the README in any way you see fit with regard to your extension (I think it currently incorrectly attributes @lukix29, I can change that if you're the host). However, I will not remove the url as it doesn't make any logical sense to do so. If someone offers to host a similar proxy server I will happily switch the url.

You're obviously free to modify your server in any way you wish. If any solution stops working I will either update the solution, remove the solution, or describe the steps required to get the solution to work.

**Comment by pixeltris** [comment]
M3U8 proxies are currently the most reliable method of avoiding ads. As such I've changed the README to include a "Recommendations" section at the very top, and I've listed your extension (with links to chrome/firefox) as the first entry as your implementation is more ideal than the other proxy that popped up (as that one leaks user info).

I will remove your url from this repo if/when someone offers to host one themselves. I know it's not quite the answer you want, but hopefully someone else offers to host at some point.

**Comment by AugusDogus** [comment]
@ChoosenEye Are you open to sharing or opensourcing your proxy server implementation?

**Comment by lukix29** [comment]
The implementation is nearly the same as the Code that youtube-dl uses for fetching the live-stream-url, but with some custom parameters in the m3u8 request URL that we can't share because it would leak privat information. Also we don't save any information about the User calling the URL in any way, we only see how often it got called.

yt-dl twitch extractor script: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/twitch.py

**Comment by pixeltris** [comment]
Honestly I think that's a wise approach to take given that Twitch is consistently patching the various workarounds that had previously been used. Do note though there's information that Twitch can use to uniquely identify your requests. Even if you stripped information, they could simply resolve an m3u8 on a channel with 0 viewers and find your parameters. It would be extremely trivial for Twitch to find out the parameters you're using.

It isn't actually necessary to fiddle with the parameters as some countries simply don't get ads (this has been mentioned throughout the years). Someone on reddit did a test of this recently https://old.reddit.com/r/Twitch/comments/kisdsy/i_did_a_little_test_regarding_ads_on_twitch_and/

I'll remove the names from the README as-per your request. The url will stay in the code for the time being (for the reasons I've stated above).

**Comment by lukix29** [comment]
Thank you, we use another aproach to this, but the info with countries is something i will look into!

**Comment by ChoosenEye** [comment]
i remove my URL and Endpoint at the end of 2020 including both extensions.
