### ISSUE TITLE
Notify Strip let some ads through

### ISSUE THREAD

**Issue by Rage-X** [pixeltris/TwitchAdSolutions#60]
Hi, this just happened. Looks like Notify Strip may be letting Twitch ads through again. Please do have a look.

**Comment by pixeltris** [comment]
Preroll / midroll are fine for me. If you see an ad could you open the network inspector, filter for `.m3u8` and copy / paste the contents of the m3u8 here.

**Comment by Rage-X** [comment]
Does not replicate right now, will try again and update if I see the ads breaking through again.
