### ISSUE TITLE
Please remove "Video Ad-Block, for Twitch" as an alternative. They switched to the dark site

### ISSUE THREAD

**Issue by VitusCitrus** [pixeltris/TwitchAdSolutions#62]
Has removed the source code from GitHub and completely privatized it. The latest update requires new permissions to "read and change your data on all amazon.co.uk sites" adding ""aradb-21" as a referral tag to product URLs.

https://twitter.com/CdrPasta/status/1509084483215048706

**Comment by pixeltris** [comment]
Closing in favor of https://github.com/pixeltris/TwitchAdSolutions/issues/61
