### ISSUE TITLE
[Question] Should I run other TTV ad blockers alongside this? 

### ISSUE THREAD

**Issue by RedSnt** [pixeltris/TwitchAdSolutions#66]
I've noticed that when the "notify-strip" script that's supposed to be added in µBlock origin is active alongside this extension, streams refuse to load.  
So is it enough to run this alone? Or can I run other scripts and extensions alongside like "TTV LOL" and "Purple Ads Blocker"?

**Comment by AmCarte** [comment]
https://github.com/pixeltris/TwitchAdSolutions/blob/master/README.md

**Comment by pixeltris** [comment]
I wouldn't recommend applying multiple Twitch specific ad blocking solutions as they can conflict as you've observed.

The solutions have different pros / cons. I'd recommend going through them and see which works best for you.

**Comment by RedSnt** [comment]
Thanks for the replies. @AmCarte I do read up on pixeltris' repo (and didn't take offense), but wasn't sure where to post this question.   
Ok, will keep an eye on what works or not.
