### ISSUE TITLE
Ads not blocked when Twitch's warp protocol is used

### ISSUE THREAD

**Issue by frank-owen** [pixeltris/TwitchAdSolutions#68]
Twitch are currently testing a QUIC based streaming protocol they call warp. The scripts seem to be not blocking ads when streams are loaded over warp. This may be responsible for some non-reproducible blocking failures.

The warp protocol can be tested reliably by setting the twitch experiment flag "warp_web_prod" to treatment (this can be accessed through ffz). If you look at video stats in the twitch player you will see "warp" instead of "HLS".

**Comment by TheEnhas** [comment]
Changing that setting does nothing for me regardless if I reload the page or browser. Using Firefox though if that makes any difference.

**Comment by RedSnt** [comment]
@TheEnhas You might need to enable quic streaming in the engine. You need FF v. 98 or later. You can access the setting in "about:config" -> network.http.http3.enabled -> enable setting.  

I've been using this experiment all morning so far, and not seen ads as of yet. 
![image](https://user-images.githubusercontent.com/6242718/170816867-200c1ec2-7117-4099-ab07-c02acc32dce7.png)
But I have noticed a more seamless switching between stream resolution and a noticeable smaller delay, so from a performance perspective it looks pretty great. I just hope it doesn't mean baked-in, impossible to remove ads.

**Comment by pixeltris** [comment]
Twitch uses the `WebTransport` API under chrome to utilize QUIC which would need hooks to block ads. I wont be coding anything for this until it's taken out of testing.

Firefox doesn't implement this API, I'm not sure if their http3 protocol uses any different APIs. If it doesn't it shouldn't be impacted.

**Comment by TheEnhas** [comment]
I have 100.0.2 and HTTP3 is already enabled, so this only works in Chromium-based browsers for now

**Comment by AlyoshaVasilieva** [comment]
It doesn't appear to affect proxy-based solutions, at least so far.

>The warp protocol can be tested reliably by setting the twitch experiment flag "warp_web_prod" to treatment

Also seems to need a live stream with latency mode set to "Low Latency". Most streams are set that way, but some (e.g. riotgames) are not and will use HLS anyway.
