### ISSUE TITLE
This one works

### ISSUE THREAD

**Issue by SRCApps** [pixeltris/TwitchAdSolutions#7]
https://addons.mozilla.org/en-GB/firefox/addon/twitch-video-ad-blocker/

**Comment by pixeltris** [comment]
Thanks for the link. This one works by proxying the main m3u8 (similar to `Twitch AdBlock`). It forwards the full `https://usher.ttvnw.net/api/channel/hls/XXXXX.m3u8` request (including search params).

The proxy url is `https://got-greedy.corblimey.workers.dev/` and an example request url would be as follows: `https://got-greedy.corblimey.workers.dev/https://usher.ttvnw.net/api/channel/hls/XXXX.m3u8?ZZZZ` (where XXXX / ZZZZ are supplied correctly).

One drawback of this method is that it leaks information about the user (login name and a unique id that might be able to be used to make requests on the clients behalf). I'll add this solution to the `Other solutions / projects` list, but for now I wont be creating a ublock/userscript solution based on this.

**Comment by SRCApps** [comment]
That's not quite right. For example this is the actual request it makes for me:

https://got-greedy.corblimey.workers.dev/https://usher.ttvnw.net/api/channel/hls/summit1g.m3u8?allow_source=true&fast_bread=true&p=4198&play_session_id=69bdcd699156e69bcdb20b1&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=a9a0a685072cfecf05cb22f30a8fe5ea32&supported_codecs=vp09,avc1&token={"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"summit1g","channel_id":26490481,"chansub":{"restricted_bitrates":[],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":"sl7SnvuImTmzOiyfx6fjPfo","expires":1609253844,"extended_history_allowed":false,"game":"","hide_ads":false,"https_required":true,"mature":false,"partner":false,"platform":"web","player_type":"site","private"{"allowed_to_view":true},"privileged":false,"role":"","server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":70557918,"user_ip":"109.149.89.91","version":2}&cdm=wv&player_version=1.2.0

So the only two bits of interesting info is user ID which is public info, I can get anybodys user ID using the public Twitch API (you can't do anything bad with it without an OAuth token and matching client-id), so there is no risk to that and IP address, but the proxy would get that from the request anyway, so it makes no difference.

I would be worried if it shared an OAuth, but it doesn't. So it can't do anything bad on gql or the API without the OAuth and client id.

**Comment by pixeltris** [comment]
Yea I haven't actually looked into it that much. All I know in terms of the unique id is that it's used by requests used to resolve the stream (and is essential for avoiding ads in the `video_ad_quartile_complete` scenario). Not sure the extent of the unique id, but I doubt Twitch expected unique ids to be shared so there might be some potential issues there.

Are you the developer? Would you consider opting for taking just the channel name and resolving the m3u8 url yourself? This is what ChoosenEye's `Twitch AdBlock` does. Privacy wise it would be a lot better. Not sending information is better than sending information (which is essentially all privacy fiasco's are about, sending information that isn't necessary).

The client side change would be:

```
var channelName = (new URL(requestDetails.url)).pathname.match(/([^\/]+)(?=\.\w+$)/)[0];
redirectUrl: "https://got-greedy.corblimey.workers.dev/" + channelName
```

**Comment by SRCApps** [comment]
I'm a Twitch dev, that's how I knew about the gql and api, theres nothing there that could be used to get anything sensitive from gql or the api without a client-id with the oauth. You would need both of those to actually do anything in gql and the normal api and it doesn't have either. I agree though changing to channelName only would be better.

**Comment by c133** [comment]
@SRCApps Can you comment on what things are like internally at Twitch right now, is this all because of Amazon? Does Twitch have devs dedicated to patching ad blocking methods around the clock? Really hoping the proxy method doesn't get patched somehow.

**Comment by c133** [comment]
...Why was this taken off of Chrome store? Sigh

**Comment by pixeltris** [comment]
It was the other proxy which was removed. This one still exists on chrome/firefox. The m3u8 proxy url in this repo has been updated to point to it.

**Comment by c133** [comment]
RIP I'm fairly certain twitch patched proxy method.

I had been using https://chrome.google.com/webstore/detail/twitch-video-ad-blocker/gggloiaahekkkndacnpecpgafnehmlja
past few days with no issue, today all streams display "There was a network error. Please try again. (Error #2000)"

Removed that extension and tried the pixeltris proxy-m3u8 script via ublock, same network error message. Disabled that, and twitch streams play normally again.

Should I go back to using dyn-mid-skip? I'm so sad right now :(

**Comment by pixeltris** [comment]
I'm sure it will be back. It looks like there's some exception occurring on the server end. The owner was testing server sided caching which caused the previous issues, maybe this is related.

Closing this issue as this is listed as the recommended solution in the README. Hopefully the issues resolve. If not then refer to https://github.com/ttvintrusiveadblocker/ttv-intrusive-blocker/issues

**Comment by pixeltris** [comment]
They've deleted their repo, github account, chrome, and firefox extensions. Removing this from the recommendations as it no longer exists.
