### ISSUE TITLE
Script not working in Google Chrome (2022-06-11)

### ISSUE THREAD

**Issue by lunamoth** [pixeltris/TwitchAdSolutions#71]
there is a problem
- Google Chrome 104.0.5110.0 dev
- "Applying a script (uBlock Origin)" (userResourcesLocation~)
- Loading continues with a black screen. Loading is not complete. no video/audio.

no problem
- Firefox Nightly 103.0a1 2022-06-10
- "Applying a script (uBlock Origin)" (userResourcesLocation~)
- works fine

All of a sudden it doesn't work in Google Chrome. Is there a way to make it work in Google Chrome?

**Comment by pixeltris** [comment]
Apparently clearing cookies fixes this. I'm not sure what happened exactly, it didn't happen to me.

Ref:
- https://github.com/pixeltris/TwitchAdSolutions/issues/69
- https://reddit.com/r/uBlockOrigin/comments/v8f8as/ublockorigin_causing_twitch_to_be_unusable/

**Comment by cleanlock** [comment]
@pixeltris some problem with the Twitch Adblock extension, as it is using the same method. Not sure what's happening, I didn't face that issue at all too.

**Comment by lunamoth** [comment]
@pixeltris @cleanlock 

Thank you for answer. Deleting cookies seems to have fixed the problem

**Comment by FlyingCake** [comment]
@pixeltris Getting the same issue (constantly looping / stuck on the black screen). This is happening on both Edge and Chrome. I've cleared all cookies & cache and rebooted the PC.
![image](https://user-images.githubusercontent.com/30985123/173986454-d94f71aa-c135-4f7c-9ac4-7edde5edad57.png)

**Comment by FlyingCake** [comment]
Seems resolved by updating the link.

Old: https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/notify-reload/notify-reload-ublock-origin.js

New: https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-strip/notify-strip-ublock-origin.js
