### ISSUE TITLE
"Blocking ads..." on every page load

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/TwitchAdSolutions#72]
Something has recently changed and the notification that ads have been watched is failing resulting in `Blocking ads...` on every page load. I'll look into this soon.

**Comment by Frumpy9** [comment]
Since you have posted this issue I have started receiving banner ads under streams. Maybe a result of the same change?

I'm using the tampermonkey script.

**Comment by TsukiZero** [comment]
It's happening way too often as of late and way too badly. Neither Notify-Strip nor Notify-Swap remedies it. Testing Vaft for some time.
