### ISSUE TITLE
Notify-strip problem

### ISSUE THREAD

**Issue by placchio** [pixeltris/TwitchAdSolutions#74]
Im using notify-strip + twitch.tv##+js(twitch-videoad) on chrome for months, and everything was mostly fine.
Lately tho i noticed sometimes i have to clear twitch cookies to make twitch streams to load (never had this problem ever before) plus yesterday it started this thing that everytime there were midrolls the streams instead of going low resolution and then back to normal, they kept refreshing like 9-10 times for the duration of the midrolls, almost losing the purpose of having the script in the first place.
Am i the only one having this problem?

**Comment by Fluffz** [comment]
I have the same issue with the refreshing a handful to a dozen times everytime the blocking midroll ads happens. It started today.

**Comment by trump2020eth** [comment]
same issue here

**Comment by pixeltris** [comment]
I'm aware of the new issues but unfortunately I haven't had the time to look into them in depth.

The midroll issue occurs where ad segments don't immediately appear. The initial request is detected a "clean" but this is followed by the ad segment so it re-requests and it creates the loop. `notify-swap` goes a few requests in before treating the stream as clean so it shouldn't be impacted by that issue so maybe try that.

The clearing cookies thing I'm really not sure as it hasn't happened to me yet. The only thing I can think of is that something is being applied multiple times as that is known to break the stream. As for why that might be happening... I have no idea.

**Comment by placchio** [comment]
Unfortunately i cant use notify-swap because it weirdly screws up my youtube: basically the videoplayer is covered half screen and i cant scroll down; also cant see the comments. No idea whats going on there.

Are you going to look into fixing notify-strip? The refreshing loop issue unfortunately is still there.

**Comment by GeorgeXCV** [comment]
> Yeah this has been happening to me where it refreshes dozen of time during midroll ads that are being blocked. Please update, it annoys the f... outta me

Yeah, I see "Blocking Midroll Ads..." and the player gets stuck in an infinite refresh loop, a manual page refresh sometimes fixes the issue but not always.

**Comment by amerrin** [comment]
I am also getting the reload loop during mid-roll ads.  When this happens, I can see the following logging to the console:

`Backup m3u8 failed with 200
Ad blocking failed. Stream might break.`

Coming from this if/else statement:

`                    if (backupM3u8 != null && !backupM3u8.includes(AD_SIGNIFIER)) {
                        return backupM3u8;
                    } else {
                        console.log('Backup m3u8 failed with ' + backupM3u8Response.status);
                    }`

`            // Backups failed. Return nothing and reload the player (reload required as an empty result will terminate the stream).
            console.log('Ad blocking failed. Stream might break.');
            postMessage({key:'UboReloadPlayer'});
            streamInfo.BackupFailed = false;
            streamInfo.BackupUrl = null;
            return '';`

I hope this is helpful. I'm not familiar with M3u8 backups so I cannot tell in detail what is triggering the failed backup.

**Comment by bntaylor929** [comment]
I am experiencing this as well, and the issue seems to have only started today.

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

No ads are playing, but the stream reloads over and over every time the "Blocking midroll ads..." message is displayed, going from smooth 1080p, briefly changing to 360p, then black, then back to 1080p -- the cycle repeats 10+ times about every 15 minutes.

Have purged uBlock cache and updated all filter lists multiple times.

**Comment by eduardoftdo** [comment]
Started experiencing this issue today. Stream is playing fine, then I get the blocking midroll ads message and the stream starts reloading in 360p for some time

```
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 81377
  cosmetic: 47572
  scriptlet: 17684
  html: 0
listset (total-discarded, last updated): 
  added: 
    spa-1: 4564-80, 2d.9h.42m
  default: 
    user-filters: 1-0, never
    easylist: 68528-51, 2d.9h.46m
    easyprivacy: 27423-123, 2d.9h.45m
    plowe-0: 3646-780, 9d.23h.59m
    ublock-abuse: 75-0, 10d.1m
    ublock-badware: 4224-95, 2d.9h.44m
    ublock-filters: 32207-151, 2d.9h.43m
    ublock-privacy: 226-3, 10d
    ublock-quick-fixes: 231-1, 13h.51m
    ublock-unbreak: 1837-43, 2d.9h.41m
    urlhaus-1: 5172-0, 13h.52m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 310 ms
  maxAssetCacheWait: 196 ms
```

**Comment by Nerxxy** [comment]
I had been getting this issue so I swapped to the VAFT script and haven't had an issue since, or at least I've not noticed the problem.
