### ISSUE TITLE
Bypassing ads

### ISSUE THREAD

**Issue by StevensND** [pixeltris/TwitchAdSolutions#76]
Hi. I'm using the vaft option (which works better for me) and sometimes ads appears instead of being block. It's like some ads are not being block but others yes.

Same happens if I use notify-strip. I'm using Chromium and I'm from Spain, EU.

Any fix?.

**Comment by Parzivus** [comment]
Getting a similar issue where ads will cause the stream to reload over and over. Currently only using the ublock script.

**Comment by AgmarTorres** [comment]
Was reported a similar issue [`here`](https://github.com/pixeltris/TwitchAdSolutions/issues/79). Maybe the script of ['Valf'](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js) or another code is not working as expected because of some update
