### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by structuredskully** [pixeltris/TwitchAdSolutions#77]
Hello, I recently discovered an issue with your script. Every time I click to watch a streamer the stream is all black and it keeps pausing and resuming. The browser I use to watch twitch is Opera GX. It was working perfectly;y fine for a couple of months I don't really know how this happened. It would be greatly appreciated if you can help resolve this issue. (i also delted and re-installed the script and it still kept happening

**Comment by structuredskully** [comment]
> 
do you know how i could do that?

**Comment by amartini** [comment]
@vegardheimdal thanks, that worked for me! @structuredskully go to home (https://github.com/pixeltris/TwitchAdSolutions) and check "vaft" under "scripts"

**Comment by cikez** [comment]
> Switching to the VAFT script fixed it for me

Thanks! Fixed my issue.

**Comment by Chron24** [comment]
For those confused on how to use vaft script with uBlock Origin under the advanced settings where the cog is for userresourcelocation replace the old script url: https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-strip/notify-strip-ublock-origin.js REPLACE THIS WITH: https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js
