### ISSUE TITLE
it doesn't work.

### ISSUE THREAD

**Issue by zxcvbmm** [pixeltris/TwitchAdSolutions#78]
notify-strip, vaft both doesn't work in korea. Now i'm using ublock origin.

**Comment by FlyingCake** [comment]
Having issues with the scripts as well.. Most of the time the video is stuck infinitely reloading.

**Comment by zxcvbmm** [comment]
> Having issues with the scripts as well.. Most of the time the video is stuck infinitely reloading.

If you are really in a hurry, try "Alternate Player for Twitch.tv" chrome extention. this works.

**Comment by RedSnt** [comment]
Twitch is experimenting with P2P in Korea, so that probably has something to do with that: https://help.twitch.tv/s/article/p2p-faq?language=en_US

**Comment by zxcvbmm** [comment]
> Twitch is experimenting with P2P in Korea, so that probably has something to do with that: https://help.twitch.tv/s/article/p2p-faq?language=en_US

thanks man

**Comment by lunamoth** [comment]
I also have an infinite loading problem.

  The "Alternate Player for Twitch.tv" extension seems to work fine.

  It would be nice if there is a way to apply the "Alternate Player for Twitch.tv" method to the userResourcesLocation method.
