### ISSUE TITLE
Stopped working (nz)

### ISSUE THREAD

**Issue by callumhalo** [pixeltris/TwitchAdSolutions#79]
working fine earlier today, not it just says blocking ads and then swaps between a black screen and the play button

**Comment by freakexeuLow** [comment]
yeah, same problem

**Comment by Kanui** [comment]
Same issue here, also from New Zealand, using uBlock (Ver 1.43.0) script on Microsoft Edge (Ver 103.0.1264.77).

**Comment by Famicorps** [comment]
Getting the same error, It's very frequent when it does the behaviour that @callumhalo mentions. Refreshing the stream rarely helps.

**Comment by Abhishekj2096** [comment]
> ~Same issue here, also from New Zealand, using uBlock (Ver 1.43.0) script on Microsoft Edge (Ver 103.0.1264.77).~ EDIT: Using the [Vaft script](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js) appears to have solved the issue, for now.

Do I paste this script in the My filters tab of ublock origin?

**Comment by EAC51** [comment]
When first joining a stream I had a ad slip through while using the [Vaft Script](https://github.com/pixeltris/TwitchAdSolutions/raw/0fd419cc94bd86be8c787813c0928b65b789abaa/vaft/vaft-ublock-origin.js) , but after closing the tab and reopening the issue appears to have resolved itself.

**Comment by Kanui** [comment]
> > ~Same issue here, also from New Zealand, using uBlock (Ver 1.43.0) script on Microsoft Edge (Ver 103.0.1264.77).~ EDIT: Using the [Vaft script](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js) appears to have solved the issue, for now.
> 
> Do I paste this script in the My filters tab of ublock origin?

No, follow the instructions [here](https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin).

**Comment by Kanui** [comment]
> > ~Same issue here, also from New Zealand, using uBlock (Ver 1.43.0) script on Microsoft Edge (Ver 103.0.1264.77).~ EDIT: Using the [Vaft script](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js) appears to have solved the issue, for now.
> 
> Do I paste this script in the My filters tab of ublock origin?

No, follow the instructions [here](https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin), but use the Vaft Script in place of the notify-strip.

**Comment by tucomel** [comment]
im was using notify-strip + tempermonkey userscript but not it gets black screen and stop playing the stream.
Im changed to vaft script (low res480 until ad ends)
There is a way to fix the notify-strip function? (which used to works better than vaft option)
