### ISSUE TITLE
Notify overall doesn't seem to work.

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#80]
As soon as you hit refresh or Reset Player, guess what? Ads. And even worse:
Notify-Strip gets stuck in a black screen
Notify-Swap is INCREDIBLY delayed
Vaft seems to be the only that works, but messed with the Latency Info and gives an inaccurate reading (Indicator says 2 seconds, it's 5+)
Low-Res is the only that consistently works nonissue.

**Comment by Nikralx** [comment]
Notify-Swap on Firefox works, but has a tendency to stop working and then show the Streamer as Offline until a refresh of the page, which fixes it until the next time it says they are offline.
