### ISSUE TITLE
Low-res now has "Commercial Break in Progress" screen

### ISSUE THREAD

**Issue by Dwedit** [pixeltris/TwitchAdSolutions#81]
It appears that using the "Low-Res" extension is now giving a "Commercial Break in Progress" screen when loading a stream, rather than the stream itself.

**Comment by dushipunda** [comment]
FYI this is not limited to the low-res script. Getting the same thing with vaft.

**Comment by Beet4** [comment]
Noticed the same for me this morning with the vaft script in Tampermonkey. Worked good until up to a few days ago when I noticed some streams stayed at 480p after the script ran. Had to manually change to source and then it worked. And today I just got the "Commercial Break in Progress". Seems like a new way to combat ad-blockers, and seems integrated into the stream itself so could be hard to overcome.

Is this the death of ad-blockers for Twitch? :(

**Comment by pixeltris** [comment]
Can confirm. Try changing this to `'pop_tart'`

https://github.com/pixeltris/TwitchAdSolutions/blob/40c5f4b18fb46014c4b5d8e77b764627a8727491/low-res/low-res.user.js#L15

**Comment by StevensND** [comment]
> Noticed the same for me this morning with the vaft script in Tampermonkey. Worked good until up to a few days ago when I noticed some streams stayed at 480p after the script ran. Had to manually change to source and then it worked. And today I just got the "Commercial Break in Progress". Seems like a new way to combat ad-blockers, and seems integrated into the stream itself so could be hard to overcome.
> 
> Is this the death of ad-blockers for Twitch? :(

Try using the uBlock Origin method instead.

**Comment by Beet4** [comment]
> > Noticed the same for me this morning with the vaft script in Tampermonkey. Worked good until up to a few days ago when I noticed some streams stayed at 480p after the script ran. Had to manually change to source and then it worked. And today I just got the "Commercial Break in Progress". Seems like a new way to combat ad-blockers, and seems integrated into the stream itself so could be hard to overcome.
> > Is this the death of ad-blockers for Twitch? :(
> 
> Try using the uBlock Origin method instead.

I'm currently using AdGuard instead of uBlock so can verify if it's working in uBlock or not. That's why I am using the userscript.

**Comment by StevensND** [comment]
> > > Noticed the same for me this morning with the vaft script in Tampermonkey. Worked good until up to a few days ago when I noticed some streams stayed at 480p after the script ran. Had to manually change to source and then it worked. And today I just got the "Commercial Break in Progress". Seems like a new way to combat ad-blockers, and seems integrated into the stream itself so could be hard to overcome.
> > > Is this the death of ad-blockers for Twitch? :(
> > 
> > 
> > Try using the uBlock Origin method instead.
> 
> I'm currently using AdGuard instead of uBlock so can verify if it's working in uBlock or not. That's why I am using the userscript.

I'm using uBlock and 0 problems for now. Also I check if there's "pop_tart" and "thunderdome" in the script. 

Link that I'm using:

[https://github.com/pixeltris/TwitchAdSolutions/raw/0fd419cc94bd86be8c787813c0928b65b789abaa/vaft/vaft-ublock-origin.js](url)

**Comment by Dwedit** [comment]
Tried editing the script, replacing all "thunderdome" with "pop_tart", but that just resulted in some streams having actual ads.

**Comment by pixeltris** [comment]
So this appears to be an issue where you apply it as a userscript and have a default install of ublock origin.

ublock origin is apply a modification to the device id. When this is combined with the low res tweak it results in the commercial break screen.

Please add `twitch.tv#@#+js(twitch-videoad)` to your ublock origin filters to disable it. Or kindly ask someone like @gwarser to remove it from the default install as it no longer does anything useful anyway.

**Comment by Beet4** [comment]
> So this appears to be an issue where you apply it as a userscript and have a default install of ublock origin.
> 
> ublock origin is apply a modification to the device id. When this is combined with the low res tweak it results in the commercial break screen.
> 
> Please add `twitch.tv#@#+js(twitch-videoad)` to your ublock origin filters to disable it. Or kindly ask someone like @gwarser to remove it from the default install as it no longer does anything useful anyway.

I do not have uBlock installed, only AdGuard. I use the vaft script in Tampermonkey and I am seeing the commercial break screen for 5-10 seconds then it jumps to the 480p stream until the ad has run.

**Comment by pixeltris** [comment]
It's possible that AdGuard also applies something similar. When the device id isn't altered low-res / vaft work for me, but when it is modified I always get the commercial screen.

Also please refrain from quoting entire messages.

**Comment by pedromoraesh** [comment]
I'm using AdGuard, and added a filter to uBlock but twitch keep showing commercial break :/

**Comment by curya** [comment]
This is happening with the vaft script too.

**Comment by DubCity7274** [comment]
Same issue when using the vaft script in ublock origin.

**Comment by StevensND** [comment]
Due to feedback saying that it's not working using uBlock Origin + Vaft option: I've been testing it today (08/20/2022) around 20 mins and 0 problems. Everything working fine for me despite some bugs (overlay saying 1080p60 quality when it was 480p and 480p all the time during first test). Here's my test: [https://youtu.be/jME06SjofM4](url) 

At the end of the video I show you my settings + what I'm using: uBlock Origin v1.43.0 + Vaft Option + Ungoogled Chromium v104.0.5112.102.

I'm from Spain so I don't know if this is an ad-country problem or not. I tried to test it watching Spanish LoL streams then English + Valorant as you can see.

**Comment by TheKins** [comment]
Applying the uBlock Origin Vaft script just gives me ads, even after a browser restart. Using the Vaft Userscript gives me a blurry low-res commercial break screen. Notify-Swap Userscript seems to work alright for the moment.

**Comment by pixeltris** [comment]
My bad it does seem like they are doing some A/B testing and some people will always see that screen regardless of filters. This will most likely come out of A/B testing soon, so yea that will most likely sign the end for the current solutions which utilize low-res streams. But proxies are still viable.

**Comment by Aryytt** [comment]
Is there a working solution now? If so where can I find it.

**Comment by Dwedit** [comment]
The Android App "Twire" can play twitch videos without ads for now.

**Comment by EatingCarBatteries** [comment]
Yeah does anyone have any solutions yet this is driving me nuts

**Comment by Aryytt** [comment]
I'm using ttv lol but it's very finicky. It works, but can stop anytime.

**Comment by iznawh** [comment]
been using [purple ads blocker](https://chrome.google.com/webstore/detail/purple-ads-blocker/lkgcfobnmghhbhgekffaadadhmeoindg) its using a proxy so its kinda delayed, but it works

**Comment by michaelchany** [comment]
> been using [purple ads blocker](https://chrome.google.com/webstore/detail/purple-ads-blocker/lkgcfobnmghhbhgekffaadadhmeoindg) its using a proxy so its kinda delayed, but it works

Purple Ads Blocker (Firefox version) initially worked, but today it wasn't loading streams at all.  It didn't give me any kind of error either, just wouldn't load.  The problem went away when I disabled Purple Ads Blocker.

**Comment by TheKins** [comment]
Notify-Strip and Notify-Swap have been updated. Notify-Strip seems to be working fine for me. See where that takes you.

**Comment by StevensND** [comment]
> Notify-Strip and Notify-Swap have been updated. Notify-Strip seems to be working fine for me. See where that takes you.

I start to getting the problem today with vaft option. Going to try this.

**Comment by StevensND** [comment]
> > Notify-Strip and Notify-Swap have been updated. Notify-Strip seems to be working fine for me. See where that takes you.
> 
> I start to getting the problem today with vaft option. Going to try this.

Update: I've been using notify-strip ublock (permalink) and it seems to be fix.

**Comment by JoJoPhantom** [comment]
Notify-Strip ublock (permalink) works for me,   coming from vaft perma

**Comment by iznawh** [comment]
> Notify-Strip ublock (permalink) works for me, coming from vaft perma

dont know why the ublock version doesnt work for me, but the userscript works lol

**Comment by gwarser** [comment]
Maybe you need to add back `twitch.tv##+js(twitch-videoad)` to My filters?

**Comment by iznawh** [comment]
> Maybe you need to add back `twitch.tv##+js(twitch-videoad)` to My filters?

already have that lol...its all good as long as its working one way or another doesnt really matter

**Comment by ssateneth** [comment]
The notify-strip (permalink) doesnt work. It repeatedly flashes the play icon on black screen with "blocking ads" top left, repeats this forever.

**Comment by StevensND** [comment]
> The notify-strip (permalink) doesnt work. It repeatedly flashes the play icon on black screen with "blocking ads" top left, repeats this forever.

Try another link or another option + EditThisCookie method.

**Comment by pixeltris** [comment]
If I am not mistaken they have now taken this out of A/B testing and the low res solutions (notify-strip, notify-swap, vaft) are patched. I'll be updating the information in the readme soon and clean up the active issues.

My recommendation will be the proxy solutions followed by the `embed` method which can be found [here (chrome)](https://chrome.google.com/webstore/detail/ttv-ad-block/kndhknfnihidhcfnaacnndbolonbimai) and [here (firefox)](https://addons.mozilla.org/en-US/firefox/addon/ttv-adblock/). `Alternate Player for Twitch.tv` continues to be a good solution (just blanks out the ads).

I'll most likely be creating a new hybrid solution soon which utilizes `embed`, proxy and blacking out the ad when all else fails.

**Comment by pundoo** [comment]
@pixeltris Hi, did they change the PLAYER_TYPE again? Getting those mid-roll ads. so annoying :/

**Comment by Dwedit** [comment]
Have you tried vaft?  It seems to work fine for me.
