### ISSUE TITLE
notify-strip not working. Just flashes the play icon.

### ISSUE THREAD

**Issue by Techwolf** [pixeltris/TwitchAdSolutions#82]
It just display the play icon in the center of the screen and flashes it.

Clearing all cookies did not fix.

Relog did not fix.

**Comment by Dwedit** [comment]
Notify-Swap appears to work for now.

**Comment by pixeltris** [comment]
`notify-strip` is being hit by the `Commercial Break in Progress` screen #81 when it fetches the ad-free stream. It detects it as an ad and reloads the player creating a loop.

I'm honestly not sure why `notify-swap` isn't being impacted in a similar way... interesting...

**Comment by pixeltris** [comment]
A fix for `notify-strip` has been created. If you are using the userscript with a default install of uBlock Origin you will also need to add `twitch.tv#@#+js(twitch-videoad)` to your filter list. This is now stated under the install instructions of the readme.

**Comment by Dwedit** [comment]
I just tested the fixed version of Notify-Strip.  I am not getting ads, but I am getting a frozen picture after a particular point.

Meanwhile, Notify-Swap is giving a stream hiccup (video goes black and play button appears, then it starts playing again).  This happens at the point when Notify-Strip would be giving the frozen picture.

**Comment by pixeltris** [comment]
Yea `notify-strip` has been bugged on Firefox for a while. I created `notify-swap` as a replacement to fix the issues but as you mentioned it has its own issues... I'd like to try experiment with some things but I've been struggling to find a channel which plays mid-rolls frequently enough to test things.

Maybe try `vaft`, a proxy, or `Alternate Player for Twitch.tv`.

**Comment by Dwedit** [comment]
It appears that notify-swap is now no longer working.

**Comment by pixeltris** [comment]
See https://github.com/pixeltris/TwitchAdSolutions/issues/83#issuecomment-1222836195
