### ISSUE TITLE
Scripts seem to have stopped working, sadly

### ISSUE THREAD

**Issue by Suzaru** [pixeltris/TwitchAdSolutions#84]
Hey guys,

as of today 08/25/22 streams seem to normally play pre-roll and mid-roll ads. I tried installing all various scripts and nothing seems to work :( I'm a western european watcher and use uBlock on Brave browser, if that helps. If I can help in any other way, let me know. Thank you for your work! <3

**Comment by FlyingCake** [comment]
I can confirm that all versions of the scrip no longer works.
