### ISSUE TITLE
What is the perfect twitch method for me?

### ISSUE THREAD

**Issue by meatdude4** [pixeltris/TwitchAdSolutions#87]
I recently started  using Purple Ads Blocker because they added the new annoyance with the "commercial break in progress" screen.

It works great literally 1080p constantly but a big thing is I'm delayed by like 3 seconds. I hate it.

So I'm looking for adblocker that has 480p during ads or better, no "commercial break in progress" screen, no different site/program and no delay.

Please github gods tell me this is possible. I just want to go back to how it was before this annoyance was added... I miss the 480p during ads but no delay meta :(

**Comment by Suprcheese** [comment]
Have you tried the updated vaft script? https://github.com/pixeltris/TwitchAdSolutions#Scripts

**Comment by pixeltris** [comment]
Try the different recommended solutions and pick the solution that works best for you.
