### ISSUE TITLE
vaft script tries to play offline stream

### ISSUE THREAD

**Issue by llaurenss** [pixeltris/TwitchAdSolutions#88]
I have the updated vaft script installed as userscript, when I open an offline stream vaft continuously tries to play it.

https://user-images.githubusercontent.com/12222665/187050220-00a09454-4337-47b7-8766-4cf0fe3720ce.mp4

.

**Comment by juliocoliveira** [comment]
Indeed it happens to me as well

**Comment by exhale33** [comment]
Yep getting the same error unfortunately.

**Comment by pixeltris** [comment]
Should be fixed.
