### ISSUE TITLE
I think first link on Recommended just got patched

### ISSUE THREAD

**Issue by ChristianMGO** [pixeltris/TwitchAdSolutions#9]
The link doesnt work anymore and twitch player fails to load whenever I have it enabled, it was working like an hour ago tho

**Comment by pixeltris** [comment]
I've now changed the url to the other m3u8 proxy. Removed the one which was purged by the owner.

**Comment by TheHungryGeek** [comment]
I had to unset and refresh the settings in ublock to get the updated proxy server to work, FYI

**Comment by PureFallen** [comment]
"The first link on Recommended" might wasn't the best choice with the file keep changing, but what apparently happened is that the Addon got removed from Chrome Webstore, AMO and the server shut down at the same time. Apparently the developer removed the project by itself.
Now that the topic is solved, it might be time to clean the issue?
