### ISSUE TITLE
Midroll ads getting through with latest vaft script

### ISSUE THREAD

**Issue by bntaylor929** [pixeltris/TwitchAdSolutions#90]
Issue in the title.

Have purged/updated all filter lists in uBlock Origin and have the extension configured properly from what I can tell:
My Filters:
twitch.tv##+js(twitch-videoad)

userResourcesLocation: https://github.com/pixeltris/TwitchAdSolutions/blob/master/README.md#:~:text=userResourcesLocation%20https%3A//github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft%2Dublock%2Dorigin.js

I'm not having any issues with the stream not starting (black screen with flashing play button) as I was with notify-strip, but now I'm seeing midroll ads.

I don't have any conflicting extensions or scripts. Any theories/suggestions?

Also just wanted to say I hugely appreciate the work pixeltris has done with this. Keep fighting the good fight!

**Comment by pixeltris** [comment]
Just to clarify your userResourcesLocation is:

`https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js`

And not:

`https://github.com/pixeltris/TwitchAdSolutions/blob/master/README.md#:~:text=userResourcesLocation%20https%3A//github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft%2Dublock%2Dorigin.js`

Right? Because that second one isn't correct. I haven't had a chance to test midrolls, it should work though. Even if the main method fails it should try using a proxy, and if that fails you should see the commercial warning screen (no actual ad).

**Comment by tkien212** [comment]
Didn't mean to hijack thread but I'm getting ads. It was working perfectly yesterday
I also tried to purge the cache for my browser

![image](https://user-images.githubusercontent.com/8452990/187319933-682aa330-455d-4d40-9427-baa9191a51e5.png)
![image](https://user-images.githubusercontent.com/8452990/187319946-d4402df0-346d-4a99-9ec5-61ecacc55616.png)

**Comment by Oglaf** [comment]
Can confirm, twitch changed something and script no longer works.

**Comment by bntaylor929** [comment]
> https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js

Umm...yeah I was using the wrong URL. Surprised it seemed to be working at all! Must've added that by mistake after switching from vaft back to notify-strip temporarily. I'll monitor for any ads, like tkien212 mentioned, but if I don't see any then seems like this was user error.

**Comment by pixeltris** [comment]
@tkien212 @Oglaf prerolls? midrolls? both?

**Comment by tkien212** [comment]
Both for me when I tested yesterday

**Comment by Oglaf** [comment]
> @tkien212 @Oglaf prerolls? midrolls? both?

Both, I had to disable the script or else the video won't start.

**Comment by iznawh** [comment]
weird i have been watching twitch all day today and havent got any ads

**Comment by tkien212** [comment]
Tested again today, using this one: https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js

Prerolls: Yes, multiple channels. Sometimes 1 ads, sometimes 2
Midrolls: Watched for 45minutes, no ads so far. Will update this comment if run into an ad

**Comment by pixeltris** [comment]
@Oglaf based on the console log the script failed to load for some reason. When the script loads successfully you should see this in your console output:

https://github.com/pixeltris/TwitchAdSolutions/blob/8eb946fd1a9569ca3dfc26a949b914c0f4307245/vaft/vaft-ublock-origin.js#L267

Make sure that message appears in your console log or the script isn't set up correctly. If you're having problems with that you could always try the userscript version or the original extension version as that's now updated.
