### ISSUE TITLE
Commercial Break in Progress Twitch Streamer

### ISSUE THREAD

**Issue by mebihicaw** [pixeltris/TwitchAdSolutions#92]
Hey, I don't know to want to talk with, but every time I search on Google I always see this, btw I'm a streamer on twitch.
it's been 7 days my stream can't show the ads. The ads just running with "Commercial Break in Progress" text.
Every website I came but there isn't a way to fix it. I just saw your post on google but I still don't understand how to fix it and lit a bit frustrated never finding the way.
By creating this ticked how anyone can help me, please?

**Comment by pixeltris** [comment]
I'm not quite sure what your question is. Recently an ad blocking method was patched by Twitch and the result was that "commercial break in progress" screen. Many people haven't updated their adblocking solution so they still see it. When updated they should see no ads and no commercial break screen.

If you'd like your viewers to see ads you could ask them to disable their ad blocker for Twitch.
