### ISSUE TITLE
TTV LOL is not working

### ISSUE THREAD

**Issue by mewnm** [pixeltris/TwitchAdSolutions#93]
The extension is letting Ads go through as of today.
Hope a fix is coming
Regards

**Comment by beef682** [comment]
I'm running both TTV LOL and Vaft script (previously 480P Watched ad flag), both are failing now. TTV as you said failed yesterday for me August 30. I wonder what Twitch is doing. Purple Ads Block (Purple Ad Block) hasent worked for me in a few months and its addon ratting is poor.

side note is that once done sitting through the 130P ad break slide and going to other streams I dont see it again for a while, same if I go back. Before it was pre-roll all the time no matter what, maybe its my mix of everything adblock installed :)

Commercial Break in Progress (29 Seconds)

**Comment by Aryytt** [comment]
I use [this](https://chrome.google.com/webstore/detail/twitch-adblock/ljhnljhabgjcihjoihakgdiicdjncpkd) with the notify swap ublock link. I don't seem to have too many issues. It works 95% of the time. Sometimes I get an ad, so I just reload the page.

**Comment by maplepy** [comment]
Neither is any https://addons.mozilla.org/en-US/firefox/addon/purpleadblock/

**Comment by maplepy** [comment]
> I use [this](https://chrome.google.com/webstore/detail/twitch-adblock/ljhnljhabgjcihjoihakgdiicdjncpkd) 

This never works for me Sadge

**Comment by Aryytt** [comment]
Use that extension. Then copy [THIS](https://github.com/pixeltris/TwitchAdSolutions/blob/master/notify-swap/notify-swap-ublock-origin.js) in ublock and "twitch.tv##+js(twitch-videoad)" w/o the quotes in your filters. When one extension does not work, use the other, same with the script.

**Comment by pixeltris** [comment]
@Aryytt the `notify-swap` / `notify-strip` scripts are broken. I've now taken them down as I've noticed some people are confused why their player is bugged. You can fetch a permalink if you still want to use it for some reason.

TTV LOL probably received more users recently which is probably expensive. Who knows if it'll return. The developer is active on github but never comments on anything related to the extension anymore.

Purple Adblock seems to be going in a different direction with their extension away from a proxy solution.

I should probably update this in the readme...

**Comment by pixeltris** [comment]
It forces a change of your device id which is shared between anyone else who uses the script. That may help reduce ads but when an ad is shown it will fail to block ads / keep trying to restart the player.

**Comment by thinkpad4** [comment]
@pixeltris TTVLOL is working again

**Comment by EldritchEevee** [comment]
TTVLOL works, if you don't mind the extension buffering Twitch all the time. Regardless of subscription status.

**Comment by pixeltris** [comment]
@EldritchEevee extension devs can send their users emails? Weird. Anyway, as long as the extension itself doesn't contain anything dodgy I'll keep it listed. Though `Purple Adblock` is less than ideal now and essentially does the same as the fork of `Video Ad-Block, for Twitch`.
