### ISSUE TITLE
vaft blocking bonus channel points

### ISSUE THREAD

**Issue by FlareHeart** [pixeltris/TwitchAdSolutions#95]
With the new vaft userscript in my uBlockOrigin, the bonus channel points are also being blocked. 
Is this a known issue?

**Comment by pixeltris** [comment]
Does it also impact https://github.com/cleanlock/VideoAdBlockForTwitch? If so it would be better to open an issue there as vaft just gets pulled in from that repo.

**Comment by FlareHeart** [comment]
I will try and let you know shortly.

**Comment by FlareHeart** [comment]
The alternative addon you linked allows the bonuses as normal. So it's something in the script form that is blocking the bonuses.

**Comment by FlareHeart** [comment]
OK hang on a second...I just put the script back into my uBlock and now the bonuses are coming in normally again. Twitch has been just...ugh...lately. Sorry to cause unnecessary alarm.
