### ISSUE TITLE
No issue just wondering where all the other userscripts have gone?

### ISSUE THREAD

**Issue by Nerxxy** [pixeltris/TwitchAdSolutions#96]
title

**Comment by pixeltris** [comment]
I explained it a bit here https://github.com/pixeltris/TwitchAdSolutions/issues/93#issuecomment-1234581307

>the `notify-swap` / `notify-strip` scripts are broken. I've now taken them down as I've noticed some people are confused why their player is bugged. You can fetch a permalink if you still want to use it for some reason.

Obviously taking down the scripts only impacts the non-permalink uBlock Origin links. The permalinks and installed userscripts will stay active until manually removed.

There aren't any plans of bringing the scripts back. I contributed an update to [this extension](https://github.com/cleanlock/VideoAdBlockForTwitch) which was originally a fork by [@saucettv](https://github.com/saucettv) of my `notify-strip` script. He handled some edge cases which fixed player freezing issues better than my scripts and he already had some stuff set up to use multiple player types so it made sense to tweak that.

If you'd like to look at the scripts and you're not sure how to do that here's a link to the final updated versions of them before they were removed https://github.com/pixeltris/TwitchAdSolutions/tree/874766a5ed565e139cd4352f81a33bbb97c9c58e
